--[[--------------------------------------------------
002-TirisfalGlades.lua
Authors: mrmr, lanjelin, GabHST (rewrite v2)
Version: 2.0.0
------------------------------------------------------
Description: Tirisfal Glades 1-12 Horde
    2.0.0 - Full rewrite: 1 action per step, all coords,
            all NPC tags, optimized route, direct language
------------------------------------------------------
--]]--------------------------------------------------
Table_002_TirisfalGlades = {
	[0106] = {
		title = "1-6 Deathknell (Tirisfal Glades)",
		items = {
			[1] = { str = "1-6 DeathKnell (Tirisfal Glades)" },
			[2] = { str = "Saia da Cripta.", x = 30, y = 71, zone = "Tirisfal Glades" },
			[3] = { str = "Va ate #NPCUndertaker Mordothen# em #COORD[30,71]#.", x = 30, y = 71, zone = "Tirisfal Glades" },
			[4] = { str = "Aceite #GETRude Awakening#.", x = 30, y = 71, zone = "Tirisfal Glades" },
			[5] = { str = "Va ate #NPCShadow Priest Sarvis# em #COORD[31,66]#.", x = 31, y = 66, zone = "Tirisfal Glades" },
			[6] = { str = "Entregue #INRude Awakening#.", x = 31, y = 66, zone = "Tirisfal Glades" },
			[7] = { str = "Aceite #GETThe Mindless Ones#.", x = 31, y = 66, zone = "Tirisfal Glades" },
			[8] = { str = "Mate 8 #NPCMindless Zombie# e 8 #NPCWretched Zombie# na colina abaixo em #COORD[32,63]#.", x = 32, y = 63, zone = "Tirisfal Glades" },
			[9] = { str = "Volte pra #NPCShadow Priest Sarvis# em #COORD[31,66]#.", x = 31, y = 66, zone = "Tirisfal Glades" },
			[10] = { str = "Entregue #INThe Mindless Ones#.", x = 31, y = 66, zone = "Tirisfal Glades" },
			[11] = { str = "Aceite #GETRattling the Rattlecages#.", x = 31, y = 66, zone = "Tirisfal Glades" },
			[12] = { str = "Aceite #GETThe Damned# (mesmo NPC).", x = 31, y = 66, zone = "Tirisfal Glades" },
			[13] = { str = "Aceite #GETTainted Scroll# (mesmo NPC).", x = 31, y = 66, zone = "Tirisfal Glades" },
			[14] = { str = "Va ate seu class trainer na igreja #COORD[31,66]#.", x = 31, y = 66, zone = "Tirisfal Glades" },
			[15] = { str = "Entregue #INTainted Scroll# e aprenda novas habilidades.", x = 31, y = 66, zone = "Tirisfal Glades" },
			[16] = { str = "Mate #NPCRattlecage Skeleton# nos arredores da vila em #COORD[30,63]# para #DORattling the Rattlecages#.", x = 30, y = 63, zone = "Tirisfal Glades" },
			[17] = { str = "Colete 6 #ITEM[Scavenger Paw]# e 6 #ITEM[Duskbat Wing]# na mesma area para #DOThe Damned#.", x = 30, y = 63, zone = "Tirisfal Glades" },
			[18] = { str = "Volte pra #NPCShadow Priest Sarvis# em #COORD[31,66]#.", x = 31, y = 66, zone = "Tirisfal Glades" },
			[19] = { str = "Entregue #INRattling the Rattlecages#.", x = 31, y = 66, zone = "Tirisfal Glades" },
			[20] = { str = "Entregue #INThe Damned#.", x = 31, y = 66, zone = "Tirisfal Glades" },
			[21] = { str = "Aceite #GETMarla's Last Wish#.", x = 31, y = 66, zone = "Tirisfal Glades" },
			[22] = { str = "Saia da igreja. Aceite #GETNight Web's Hollow# de #NPCExecutor Arren# em #COORD[32,66]#.", x = 32, y = 66, zone = "Tirisfal Glades" },
			[23] = { str = "Aceite #GETScavenging Deathknell# de #NPCDeathguard Saltain# em #COORD[32,65]#.", x = 32, y = 65, zone = "Tirisfal Glades" },
			[24] = { str = "Colete 6 #ITEM[Scavenged Goods]# dentro dos predios da vila em #COORD[30,64]#.", x = 30, y = 64, zone = "Tirisfal Glades" },
			[25] = { str = "Va ate #COORD[37,62]# e mate #NPCSamuel Fipps# para #DOMarla's Last Wish#.", x = 37, y = 62, zone = "Tirisfal Glades" },
			[26] = { str = "Va ate a caverna em #COORD[27,59]#.", x = 27, y = 59, zone = "Tirisfal Glades" },
			[27] = { str = "Mate 10 #NPCNight Web Spider# e 8 #NPCYoung Night Web Spider# dentro da caverna para #DONight Web's Hollow#.", x = 27, y = 59, zone = "Tirisfal Glades" },
			[28] = { str = "Va ate o cemiterio em #COORD[31,64]#.", x = 31, y = 64, zone = "Tirisfal Glades" },
			[29] = { str = "Clique no #ITEMgrave# para enterrar o cranio (#INMarla's Last Wish#).", x = 31, y = 64, zone = "Tirisfal Glades" },
			[30] = { str = "Va ate #NPCExecutor Arren# em #COORD[32,66]#.", x = 32, y = 66, zone = "Tirisfal Glades" },
			[31] = { str = "Entregue #INNight Web's Hollow#.", x = 32, y = 66, zone = "Tirisfal Glades" },
			[32] = { str = "Entregue #INScavenging Deathknell# em #NPCDeathguard Saltain# #COORD[32,65]#.", x = 32, y = 65, zone = "Tirisfal Glades" },
			[33] = { str = "Aceite #GETThe Scarlet Crusade# de #NPCExecutor Arren# #COORD[32,66]#.", x = 32, y = 66, zone = "Tirisfal Glades" },
			[34] = { str = "Va ate #COORD[37,67]# e mate 12 #NPCScarlet Convert# para #DOThe Scarlet Crusade#.", x = 37, y = 67, zone = "Tirisfal Glades" },
			[35] = { str = "Volte pra #NPCExecutor Arren# em #COORD[32,66]#.", x = 32, y = 66, zone = "Tirisfal Glades" },
			[36] = { str = "Entregue #INThe Scarlet Crusade#.", x = 32, y = 66, zone = "Tirisfal Glades" },
			[37] = { str = "Aceite #GETThe Red Messenger#.", x = 32, y = 66, zone = "Tirisfal Glades" },
			[38] = { str = "Va ate #COORD[36,68]# e mate #NPCMeven Korgal#.", x = 36, y = 68, zone = "Tirisfal Glades" },
			[39] = { str = "Volte pra #NPCExecutor Arren# em #COORD[32,66]#.", x = 32, y = 66, zone = "Tirisfal Glades" },
			[40] = { str = "Entregue #INThe Red Messenger#.", x = 32, y = 66, zone = "Tirisfal Glades" },
			[41] = { str = "Aceite #GETVital Intelligence#.", x = 32, y = 66, zone = "Tirisfal Glades" },
			[42] = { str = "Pegue novas habilidades no trainer se level 6. Se nao, grinde ate level 6.", x = 31, y = 66, zone = "Tirisfal Glades" },
			[43] = { str = "Va ate #COORD[38,57]# no norte de Deathknell.", x = 38, y = 57, zone = "Tirisfal Glades" },
			[44] = { str = "Aceite #GETA Rogue's Deal# e saia da area inicial.", x = 38, y = 57, zone = "Tirisfal Glades" },
    	}
	},
	[0610] = {
		title = "6-10 Tirisfal Glades",
		items = {
			[1] = { str = "6-10 Tirisfal Glades" },
			[2] = { str = "Va ate #NPCDeathguard Simmer# em #COORD[40.9,54.2]#.", x = 40.9, y = 54.2, zone = "Tirisfal Glades", tip = "Na estrada entre Deathknell e Brill" },
			[3] = { str = "Aceite #GETFields of Grief#.", x = 40.9, y = 54.2, zone = "Tirisfal Glades", tip = "Precisa coletar 10 aboboras na fazenda" },
			[4] = { str = "Va ate a fazenda Solliden em #COORD[37,52]#.", x = 37, y = 52, zone = "Tirisfal Glades", tip = "Fazenda ao oeste, cheia de Tirisfal Farmers lvl 5-7" },
			[5] = { str = "Colete 10 #ITEM[Tirisfal Pumpkin]# nos campos.", x = 37, y = 52, zone = "Tirisfal Glades", tip = "Aboboras brilham no chao, espalhadas pela fazenda" },
			[6] = { str = "Encontre #NPCGordo# na estrada em #COORD[43.1,54.7]#.", x = 43.1, y = 54.7, zone = "Tirisfal Glades", tip = "Gordo patrulha a estrada, pode demorar pra achar. Use /target Gordo" },
			[7] = { str = "Aceite #GETGordo's Task#.", x = 43.1, y = 54.7, zone = "Tirisfal Glades", tip = "Precisa de 3 Gloom Weed, colete no caminho pra Brill" },
			[8] = { str = "Colete 3 #ITEM[Gloom Weed]# pela estrada pra Brill.", x = 50, y = 55, zone = "Tirisfal Glades", tip = "Ervas verdes no chao, ao longo da estrada principal" },
			[9] = { str = "Va ate #NPCJunior Apothecary Holland# em #COORD[57.4,48.8]#.", x = 57.4, y = 48.8, zone = "Tirisfal Glades", tip = "No cemiterio ao norte de Brill, ele anda pela area" },
			[10] = { str = "Entregue #INGordo's Task#.", x = 57.4, y = 48.8, zone = "Tirisfal Glades" },
			[11] = { str = "Aceite #GETDoom Weed#.", x = 57.4, y = 48.8, zone = "Tirisfal Glades", tip = "Faremos mais tarde no circuito norte" },
			[12] = { str = "Va ate #NPCDeathguard Dillinger# em #COORD[58.2,51.4]#.", x = 58.2, y = 51.4, zone = "Tirisfal Glades", tip = "Na entrada de Brill pela estrada" },
			[13] = { str = "Aceite #GETA Putrid Task#.", x = 58.2, y = 51.4, zone = "Tirisfal Glades", tip = "Precisa de 7 Putrid Claw dos Scourge na ponte" },
			[14] = { str = "Va ate #NPCApothecary Johaan# em #COORD[59.4,52.4]#.", x = 59.4, y = 52.4, zone = "Tirisfal Glades", tip = "Predio do boticario, primeira casa em Brill" },
			[15] = { str = "Entregue #INFields of Grief#.", x = 59.4, y = 52.4, zone = "Tirisfal Glades" },
			[16] = { str = "Aceite #GETFields of Grief pt.2#.", x = 59.4, y = 52.4, zone = "Tirisfal Glades" },
			[17] = { str = "Aceite #GETA New Plague#.", x = 59.4, y = 52.4, zone = "Tirisfal Glades", tip = "Chain longa, faremos ao longo do guide" },
			[18] = { str = "Va ate #NPCExecutor Zygand# em #COORD[60.6,51.8]#.", x = 60.6, y = 51.8, zone = "Tirisfal Glades", tip = "Do lado de fora do Town Hall" },
			[19] = { str = "Entregue #INVital Intelligence#.", x = 60.6, y = 51.8, zone = "Tirisfal Glades" },
			[20] = { str = "Aceite #GETAt War with the Scarlet Crusade#.", x = 60.6, y = 51.8, zone = "Tirisfal Glades", tip = "Chain de 4 partes contra os Scarlet Crusade" },
			[21] = { str = "Pegue #GETWanted: Maggot Eye# do #ITEMWanted! sign# atras dele.", x = 60.6, y = 51.8, zone = "Tirisfal Glades", tip = "Placa de Wanted logo atras do Executor" },
			[22] = { str = "Va ate #NPCMagistrate Sevren# em #COORD[61.3,50.8]#.", x = 61.3, y = 50.8, zone = "Tirisfal Glades", tip = "Dentro do Town Hall" },
			[23] = { str = "Aceite #GETProof of Demise#.", x = 61.3, y = 50.8, zone = "Tirisfal Glades" },
			[24] = { str = "Aceite #GETGraverobbers#.", x = 61.3, y = 50.8, zone = "Tirisfal Glades", tip = "Rot Hide Gnolls ao norte, faremos no circuito norte" },
			[25] = { str = "Va ate a Inn em #COORD[61.7,52.3]#.", x = 61.7, y = 52.3, zone = "Tirisfal Glades", tip = "Gallows' End Tavern, a Inn de Brill" },
			[26] = { str = "Entregue #INA Rogue's Deal# em #NPCInnkeeper Renee#.", x = 61.7, y = 52.3, zone = "Tirisfal Glades" },
			[27] = { str = "Sete seu Hearthstone em #NPCInnkeeper Renee#.", x = 61.7, y = 52.3, zone = "Tirisfal Glades", tip = "IMPORTANTE: Hearth aqui, vamos usar varias vezes" },
			[28] = { str = "Aprenda First Aid com #NPCNurse Neela# na Inn.", x = 61.7, y = 52.3, zone = "Tirisfal Glades", tip = "Perto da entrada, aprenda bandages pra curar entre combates" },
			[29] = { str = "Aceite #GETThe Haunted Mills# de #NPCColeman Farthing#.", x = 61.7, y = 52.3, zone = "Tirisfal Glades", tip = "Terreo da Inn, lado direito. Req level 7" },
			[30] = { str = "Aceite #GETThe Chill of Death# de #NPCGretchen Dedmar#.", x = 61.7, y = 52.3, zone = "Tirisfal Glades", tip = "Segundo andar da Inn, suba as escadas. Precisa de Duskbat Pelts" },
			[31] = { str = "Desca pro porao da Inn. Interrogue o #NPCCaptured Scarlet Zealot#.", x = 61.7, y = 52.3, zone = "Tirisfal Glades", tip = "Porao: desca as escadas do terreo" },
			[32] = { str = "Entregue #INFields of Grief pt.2#.", x = 61.7, y = 52.3, zone = "Tirisfal Glades" },
			-- PONTE - PUTRID CLAWS
			[33] = { str = "Va ate a ponte em #COORD[53,53]#.", x = 53, y = 53, zone = "Tirisfal Glades", tip = "Ponte oeste de Brill, Scourge nos dois lados" },
			[34] = { str = "Mate #NPCRotting Dead# e #NPCRavaged Corpse# para 7 #ITEM[Putrid Claw]#.", x = 53, y = 53, zone = "Tirisfal Glades", tip = "Drop ~20%, pode demorar. Tambem em Cold Hearth Manor ao sul" },
			[35] = { str = "Volte pra #NPCDeathguard Dillinger# em #COORD[58.2,51.4]#.", x = 58.2, y = 51.4, zone = "Tirisfal Glades" },
			[36] = { str = "Entregue #INA Putrid Task#.", x = 58.2, y = 51.4, zone = "Tirisfal Glades" },
			[37] = { str = "Aceite #GETThe Mills Overrun#.", x = 58.2, y = 51.4, zone = "Tirisfal Glades", tip = "Faremos em Agamand Mills depois de level 10" },
			-- CIRCUITO OESTE
			[38] = { str = "Siga pela estrada oeste ate #COORD[42,50]#.", x = 42, y = 50, zone = "Tirisfal Glades", tip = "Mate Duskbats e Darkhounds pelo caminho" },
			[39] = { str = "Mate #NPCGreater Duskbat# pelo caminho para 5 #ITEM[Duskbat Pelt]#.", x = 42, y = 50, zone = "Tirisfal Glades", tip = "Voam por toda a zona, nao precisa ir longe" },
			[40] = { str = "Mate #NPCDecrepit Darkhound# pelo caminho para 5 #ITEM[Darkhound Blood]#.", x = 42, y = 50, zone = "Tirisfal Glades", tip = "Cachorros na estrada e campos ao redor" },
			[41] = { str = "Va ate a torre Scarlet em #COORD[32,47]#.", x = 32, y = 47, zone = "Tirisfal Glades", tip = "Torre ao oeste, passando a fazenda Solliden" },
			[42] = { str = "Mate 10 #NPCScarlet Warrior# para #DOAt War with the Scarlet Crusade#.", x = 32, y = 47, zone = "Tirisfal Glades", tip = "Lvl 7-8, espalhados ao redor da torre e estrada" },
			[43] = { str = "Use Hearth pra Brill.", x = 61.7, y = 52.3, zone = "Tirisfal Glades", tip = "Economiza tempo de volta" },
			[44] = { str = "Compre #ITEM[Coarse Thread]# em #NPCAbigail Shiel# #COORD[61.0,52.4]#.", x = 61.0, y = 52.4, zone = "Tirisfal Glades", tip = "Trade Supplies, loja ao lado da Inn" },
			[45] = { str = "Entregue #INThe Chill of Death# em #NPCGretchen Dedmar#.", x = 61.7, y = 52.3, zone = "Tirisfal Glades", tip = "Segundo andar da Inn" },
			[46] = { str = "Entregue #INAt War with the Scarlet Crusade# em #NPCExecutor Zygand# #COORD[60.6,51.8]#.", x = 60.6, y = 51.8, zone = "Tirisfal Glades" },
			[47] = { str = "Aceite #GETAt War with the Scarlet Crusade pt.2#.", x = 60.6, y = 51.8, zone = "Tirisfal Glades" },
			[48] = { str = "Entregue #INProof of Demise# em #NPCMagistrate Sevren# #COORD[61.3,50.8]#.", x = 61.3, y = 50.8, zone = "Tirisfal Glades" },
			[49] = { str = "Entregue #INA New Plague# em #NPCApothecary Johaan# #COORD[59.4,52.4]#.", x = 59.4, y = 52.4, zone = "Tirisfal Glades" },
			[50] = { str = "Aceite #GETA New Plague pt.2#.", x = 59.4, y = 52.4, zone = "Tirisfal Glades" },
			-- CIRCUITO NORTE
			[51] = { str = "Saia de Brill pro norte ate o cemiterio em #COORD[57,47]#.", x = 57, y = 47, zone = "Tirisfal Glades", tip = "Cemiterio logo ao norte de Brill" },
			[52] = { str = "Colete 10 #ITEM[Doom Weed]# no chao do cemiterio.", x = 57, y = 47, zone = "Tirisfal Glades", tip = "Ervas roxas/escuras no chao entre as lapides" },
			[53] = { str = "Continue norte ate #COORD[55,42]#.", x = 55, y = 42, zone = "Tirisfal Glades", tip = "Area dos Rot Hide Gnolls, cuidado com adds" },
			[54] = { str = "Mate #NPCRot Hide Gnoll# e #NPCRot Hide Mongrel# para 5 #ITEM[Embalming Ichor]#.", x = 55, y = 42, zone = "Tirisfal Glades", tip = "Gnolls lvl 8-9, dropam Ichor. Mate os Mongrels tambem" },
			[55] = { str = "Va ate a cabana em #COORD[58.7,30.8]#.", x = 58.7, y = 30.8, zone = "Tirisfal Glades", tip = "Garren's Haunt, cabana isolada ao norte" },
			[56] = { str = "Mate #NPCMaggot Eye# (#DOWanted: Maggot Eye#).", x = 58.7, y = 30.8, zone = "Tirisfal Glades", tip = "Boss lvl 10 dentro da cabana. Loote a pata dele" },
			[57] = { str = "Va ate a praia em #COORD[61,29]#.", x = 61, y = 29, zone = "Tirisfal Glades", tip = "Whispering Shore, praia ao norte" },
			[58] = { str = "Mate #NPCVile Fin Puddlejumper# e #NPCVile Fin Minor Oracle# para 5 #ITEM[Vile Fin Scale]#.", x = 61, y = 29, zone = "Tirisfal Glades", tip = "Murlocs lvl 8-9 na praia. Oracle cura, mate primeiro" },
			-- VOLTA PRA BRILL
			[59] = { str = "Volte pra #NPCJunior Apothecary Holland# em #COORD[57.4,48.8]#.", x = 57.4, y = 48.8, zone = "Tirisfal Glades" },
			[60] = { str = "Entregue #INDoom Weed#.", x = 57.4, y = 48.8, zone = "Tirisfal Glades" },
			[61] = { str = "Entregue #INWanted: Maggot Eye# em #NPCExecutor Zygand# #COORD[60.6,51.8]#.", x = 60.6, y = 51.8, zone = "Tirisfal Glades" },
			[62] = { str = "Entregue #INGraverobbers# em #NPCMagistrate Sevren# #COORD[61.3,50.8]#.", x = 61.3, y = 50.8, zone = "Tirisfal Glades" },
			[63] = { str = "Aceite #GETForsaken Duties#.", x = 61.3, y = 50.8, zone = "Tirisfal Glades", tip = "Mandar pra waystation no leste, faremos depois" },
			[64] = { str = "Aceite #GETThe Prodigal Lich#.", x = 61.3, y = 50.8, zone = "Tirisfal Glades", tip = "Entregar na Undercity mais tarde" },
			[65] = { str = "Entregue #INA New Plague pt.2# em #NPCApothecary Johaan# #COORD[59.4,52.4]#.", x = 59.4, y = 52.4, zone = "Tirisfal Glades" },
			[66] = { str = "Aceite #GETA New Plague pt.3#.", x = 59.4, y = 52.4, zone = "Tirisfal Glades" },
			-- CIRCUITO SUL
			[67] = { str = "Va ate a torre sul em #COORD[51,68]#.", x = 51, y = 68, zone = "Tirisfal Glades", tip = "Torre Scarlet ao sul de Brill, pela estrada" },
			[68] = { str = "Mate 3 #NPCScarlet Missionary#, 3 #NPCScarlet Zealot# e #NPCCaptain Perrine#.", x = 51, y = 68, zone = "Tirisfal Glades", tip = "Captain Perrine dentro da torre no andar de cima. Lvl 9-10" },
			[69] = { str = "Volte pra #NPCExecutor Zygand# em #COORD[60.6,51.8]#.", x = 60.6, y = 51.8, zone = "Tirisfal Glades" },
			[70] = { str = "Entregue #INAt War with the Scarlet Crusade pt.2#.", x = 60.6, y = 51.8, zone = "Tirisfal Glades" },
			[71] = { str = "Aceite #GETAt War with the Scarlet Crusade pt.3#.", x = 60.6, y = 51.8, zone = "Tirisfal Glades", tip = "Faremos no guide 10-12 na area leste" },
			-- AGAMAND MILLS
			[72] = { str = "Va ate Agamand Mills em #COORD[47,41]#.", x = 47, y = 41, zone = "Tirisfal Glades", tip = "Fazenda assombrada ao noroeste de Brill. Mobs lvl 9-11" },
			[73] = { str = "Mate #NPCDevlin Agamand# (#DOThe Haunted Mills#).", x = 47, y = 41, zone = "Tirisfal Glades", tip = "Patrulha a area gramada. Lvl 11, cuidado" },
			[74] = { str = "Volte pra Inn em Brill #COORD[61.7,52.3]#.", x = 61.7, y = 52.3, zone = "Tirisfal Glades", tip = "Use Hearth se disponivel" },
			[75] = { str = "Entregue #INThe Haunted Mills# em #NPCColeman Farthing#.", x = 61.7, y = 52.3, zone = "Tirisfal Glades", tip = "Terreo da Inn" },
			[76] = { str = "Aceite #GETDeaths in the Family#.", x = 61.7, y = 52.3, zone = "Tirisfal Glades", tip = "Matar 3 Agamands em Agamand Mills, faremos no guide 10-12" },
			-- FINALIZANDO
			[77] = { str = "Pegue novas habilidades no trainer.", x = 61.7, y = 52.3, zone = "Tirisfal Glades", tip = "Voce deve ser level 10. Se nao, grinde ate level 10" },
			[78] = { str = "Aceite sua #GETClass Quest# mas nao faca ainda.", x = 61.7, y = 52.3, zone = "Tirisfal Glades", tip = "Faremos a Class Quest na Undercity no guide 10-12" },
    	}
	},
	[1012] = {
		title = "10-12 Tirisfal Glades",
		items = {
			[1] = { str = "10-12 Tirisfal Glades" },
			-- AGAMAND MILLS
			[2] = { str = "Va ate Agamand Mills em #COORD[48,43]#.", x = 48, y = 43, zone = "Tirisfal Glades", tip = "Noroeste de Brill. Mobs lvl 9-11, cuidado com pulls" },
			[3] = { str = "Mate #NPCRattlecage Soldier# para 5 #ITEM[Notched Ribs]#.", x = 48, y = 43, zone = "Tirisfal Glades", tip = "Esqueletos melee, dropam Ribs e podem dropar A Letter to Yvette" },
			[4] = { str = "Mate #NPCDarkeye Bonecaster# para 3 #ITEM[Blackened Skull]#.", x = 48, y = 43, zone = "Tirisfal Glades", tip = "Casters ranged, interrupa com Kick. Ficam misturados com os Soldiers" },
			[5] = { str = "Se #ITEM[A Letter to Yvette]# dropar, aceite #GETA Letter Undelivered#.", x = 48, y = 43, zone = "Tirisfal Glades", tip = "Drop raro dos Rattlecage Soldiers. Entrega na Inn de Brill" },
			[6] = { str = "Va ate #COORD[50,36]#.", x = 50, y = 36, zone = "Tirisfal Glades", tip = "Predio no leste de Agamand Mills" },
			[7] = { str = "Mate #NPCNissa Agamand#.", x = 50, y = 36, zone = "Tirisfal Glades", tip = "Lvl 11, dentro do predio. Pode ter adds, limpe antes" },
			[8] = { str = "Va ate #COORD[44,34]#.", x = 44, y = 34, zone = "Tirisfal Glades", tip = "Lado oeste de Agamand Mills" },
			[9] = { str = "Mate #NPCThurman Agamand#.", x = 44, y = 34, zone = "Tirisfal Glades", tip = "Lvl 11, fica numa area aberta. Cuidado com patrulhas" },
			[10] = { str = "Va ate #COORD[46,29]#.", x = 46, y = 29, zone = "Tirisfal Glades", tip = "Fazenda no extremo norte de Agamand" },
			[11] = { str = "Mate #NPCGregor Agamand#.", x = 46, y = 29, zone = "Tirisfal Glades", tip = "Lvl 12, o mais forte dos 3. Use Evasion se precisar" },
			-- VOLTA PRA BRILL
			[12] = { str = "Volte pra #NPCDeathguard Dillinger# em #COORD[58.2,51.4]#.", x = 58.2, y = 51.4, zone = "Tirisfal Glades" },
			[13] = { str = "Entregue #INThe Mills Overrun#.", x = 58.2, y = 51.4, zone = "Tirisfal Glades" },
			[14] = { str = "Va ate a Inn #COORD[61.7,52.3]#.", x = 61.7, y = 52.3, zone = "Tirisfal Glades" },
			[15] = { str = "Entregue #INA Letter Undelivered# em #NPCYvette Farthing#.", x = 61.7, y = 52.3, zone = "Tirisfal Glades", tip = "Segundo andar da Inn. Se nao dropou a carta, pule" },
			[16] = { str = "Entregue #INDeaths in the Family# em #NPCColeman Farthing#.", x = 61.7, y = 52.3, zone = "Tirisfal Glades", tip = "Terreo da Inn" },
			[17] = { str = "Aceite #GETSpeak with Sevren#.", x = 61.7, y = 52.3, zone = "Tirisfal Glades" },
			[18] = { str = "Entregue #INSpeak with Sevren# em #NPCMagistrate Sevren# #COORD[61.3,50.8]#.", x = 61.3, y = 50.8, zone = "Tirisfal Glades", tip = "Town Hall, do lado da Inn" },
			[19] = { str = "Pule #SKIPThe Family Crypt#.", x = 61.3, y = 50.8, zone = "Tirisfal Glades", tip = "Dungeon dificil, nao vale o tempo. Prossiga" },
			-- UNDERCITY
			[20] = { str = "Va ate a Undercity #COORD[62,65]#.", x = 62, y = 65, zone = "Tirisfal Glades", tip = "Entrada ao sul de Brill, desca pela rampa circular" },
			[21] = { str = "Faca sua Class Quest.", x = 62, y = 65, zone = "Tirisfal Glades", tip = "Rogue trainer no Rogues Quarter. Siga as indicacoes" },
			[22] = { str = "Va ate o Weapon Master #NPCArchibald# em #COORD[57,33]#.", x = 57, y = 33, zone = "Undercity", tip = "War Quarter, aprenda Swords pra usar espadas" },
			[23] = { str = "Aprenda Swords.", x = 57, y = 33, zone = "Undercity", tip = "10s pra aprender. Essencial pra Combat Swords" },
			[24] = { str = "Va ate #NPCBethor Iceshard# em #COORD[84,17]#.", x = 84, y = 17, zone = "Undercity", tip = "Mage Quarter, plataforma elevada" },
			[25] = { str = "Entregue #INThe Prodigal Lich#.", x = 84, y = 17, zone = "Undercity" },
			[26] = { str = "Aceite #GETThe Lich's Identity#.", x = 84, y = 17, zone = "Undercity", tip = "Precisa ir a Gunther's Retreat buscar um livro" },
			-- WAYSTATION LESTE
			[27] = { str = "Saia da Undercity. Va ate #NPCDeathguard Linnea# em #COORD[65.5,60.3]#.", x = 65.5, y = 60.3, zone = "Tirisfal Glades", tip = "Death's Watch Waystation, estrada leste de Brill" },
			[28] = { str = "Entregue #INForsaken Duties#.", x = 65.5, y = 60.3, zone = "Tirisfal Glades" },
			[29] = { str = "Aceite #GETReturn to the Magistrate#.", x = 65.5, y = 60.3, zone = "Tirisfal Glades" },
			[30] = { str = "Aceite #GETRear Guard Patrol#.", x = 65.5, y = 60.3, zone = "Tirisfal Glades", tip = "Matar Horrors e Spirits na farmstead ao leste" },
			[31] = { str = "Va ate Balnir Farmstead em #COORD[75,61]#.", x = 75, y = 61, zone = "Tirisfal Glades", tip = "Fazenda fantasma ao leste. Mobs lvl 10-12" },
			[32] = { str = "Mate 8 #NPCBleeding Horror#.", x = 75, y = 61, zone = "Tirisfal Glades", tip = "Fantasmas melee, espalhados pela fazenda" },
			[33] = { str = "Mate 8 #NPCWandering Spirit#.", x = 75, y = 61, zone = "Tirisfal Glades", tip = "Fantasmas casters, mesma area" },
			[34] = { str = "Continue norte ate #COORD[79,56]#.", x = 79, y = 56, zone = "Tirisfal Glades", tip = "Torre Scarlet no sudeste de Tirisfal" },
			[35] = { str = "Mate 5 #NPCScarlet Friar#.", x = 79, y = 56, zone = "Tirisfal Glades", tip = "Friars sao healers! Interrupa ou mate rapido" },
			[36] = { str = "Mate #NPCCaptain Vachon#.", x = 79, y = 56, zone = "Tirisfal Glades", tip = "Lvl 12, na torre. Pode ter 2 guards com ele" },
			[37] = { str = "Va ao leste ate #COORD[85,53]#.", x = 85, y = 53, zone = "Tirisfal Glades", tip = "Area de aranhas no extremo leste" },
			[38] = { str = "Mate #NPCVicious Night Web Spider# para 4 #ITEM[Vicious Night Web Spider Venom]#.", x = 85, y = 53, zone = "Tirisfal Glades", tip = "Aranhas lvl 10-11, drop rate bom" },
			-- GUNTHER'S RETREAT
			[39] = { str = "Va ate Gunther's Retreat em #COORD[68,42]#.", x = 68, y = 42, zone = "Tirisfal Glades", tip = "Ilha no Brightwater Lake. Nade ate la" },
			[40] = { str = "Clique em #ITEMGunther's Books# para pegar #ITEM[The Lich's Spellbook]#.", x = 68, y = 42, zone = "Tirisfal Glades", tip = "Pilha de livros na mesa ao lado de Gunther" },
			[41] = { str = "Volte pra #NPCDeathguard Linnea# em #COORD[65.5,60.3]#.", x = 65.5, y = 60.3, zone = "Tirisfal Glades" },
			[42] = { str = "Entregue #INRear Guard Patrol#.", x = 65.5, y = 60.3, zone = "Tirisfal Glades" },
			-- UNDERCITY NOVAMENTE
			[43] = { str = "Va ate a Undercity, #NPCBethor Iceshard# #COORD[84,17]#.", x = 84, y = 17, zone = "Undercity" },
			[44] = { str = "Entregue #INThe Lich's Identity#.", x = 84, y = 17, zone = "Undercity" },
			[45] = { str = "Aceite #GETReturn the Book#.", x = 84, y = 17, zone = "Undercity" },
			-- BRILL ENTREGAS
			[46] = { str = "Use Hearth pra Brill.", x = 61.7, y = 52.3, zone = "Tirisfal Glades" },
			[47] = { str = "Entregue #INAt War with the Scarlet Crusade pt.3# em #NPCExecutor Zygand# #COORD[60.6,51.8]#.", x = 60.6, y = 51.8, zone = "Tirisfal Glades" },
			[48] = { str = "Aceite #GETAt War with the Scarlet Crusade pt.4#.", x = 60.6, y = 51.8, zone = "Tirisfal Glades", tip = "Ultima parte! Torre no nordeste de Tirisfal" },
			[49] = { str = "Entregue #INReturn to the Magistrate# em #NPCMagistrate Sevren# #COORD[61.3,50.8]#.", x = 61.3, y = 50.8, zone = "Tirisfal Glades" },
			[50] = { str = "Entregue #INA New Plague pt.3# no porao da Inn em #NPCCaptured Scarlet Zealot#.", x = 61.7, y = 52.3, zone = "Tirisfal Glades", tip = "Porao da Inn, desca as escadas" },
			-- GUNTHER'S RETREAT - PROVING ALLEGIANCE
			[51] = { str = "Va ate Gunther's Retreat em #COORD[68,42]#.", x = 68, y = 42, zone = "Tirisfal Glades", tip = "Nade pelo lago novamente" },
			[52] = { str = "Entregue #INReturn the Book# em #NPCGunther Arcanus#.", x = 68, y = 42, zone = "Tirisfal Glades" },
			[53] = { str = "Aceite #GETProving Allegiance#.", x = 68, y = 42, zone = "Tirisfal Glades", tip = "Precisa invocar e matar Lillith na ilha ao sul" },
			[54] = { str = "Pegue uma #ITEM[Candle of Beckoning]# do #ITEMCrate of Candles#.", x = 68, y = 42, zone = "Tirisfal Glades", tip = "Caixa de velas ao lado de Gunther" },
			[55] = { str = "Nade ate a ilha ao sul em #COORD[67,45]#.", x = 67, y = 45, zone = "Tirisfal Glades", tip = "Pequena ilha com uma mesa" },
			[56] = { str = "Use a vela na #ITEMDinner Table#. Mate #NPCLillith Nefara#.", x = 67, y = 45, zone = "Tirisfal Glades", tip = "Lillith e lvl 12 elite-like. Use CDs se precisar" },
			[57] = { str = "Volte pra #NPCGunther Arcanus# em #COORD[68,42]#.", x = 68, y = 42, zone = "Tirisfal Glades" },
			[58] = { str = "Entregue #INProving Allegiance#.", x = 68, y = 42, zone = "Tirisfal Glades" },
			[59] = { str = "Aceite #GETThe Prodigal Lich Returns#.", x = 68, y = 42, zone = "Tirisfal Glades", tip = "Entrega na Undercity, faremos no final" },
			-- SCARLET PT4 - TORRE NORTE
			[60] = { str = "Va ate a torre norte em #COORD[79,26]#.", x = 79, y = 26, zone = "Tirisfal Glades", tip = "Torre ao nordeste, passando Faol's Rest. Caminho longo" },
			[61] = { str = "Mate #NPCCaptain Melrache# e 2 #NPCScarlet Bodyguard#.", x = 79, y = 26, zone = "Tirisfal Glades", tip = "Lvl 13, dentro da torre no topo. Bodyguards lvl 12. Pull com cuidado" },
			-- ENTREGAS FINAIS
			[62] = { str = "Volte pra #NPCExecutor Zygand# em #COORD[60.6,51.8]#.", x = 60.6, y = 51.8, zone = "Tirisfal Glades", tip = "Use Hearth se disponivel" },
			[63] = { str = "Entregue #INAt War with the Scarlet Crusade pt.4#.", x = 60.6, y = 51.8, zone = "Tirisfal Glades", tip = "Chain completa! Boa XP" },
			[64] = { str = "Va ate a Undercity, #NPCBethor Iceshard# #COORD[84,17]#.", x = 84, y = 17, zone = "Undercity" },
			[65] = { str = "Entregue #INThe Prodigal Lich Returns#.", x = 84, y = 17, zone = "Undercity" },
			[66] = { str = "Pegue treinamento level 12 no trainer.", x = 84, y = 17, zone = "Undercity", tip = "Rogue trainer no Rogues Quarter. Pegue tudo disponivel" },
			-- PARTINDO PRA BARRENS
			[67] = { str = "Saia da Undercity. Va ate a Zeppelin Tower em #COORD[61,59]#.", x = 61, y = 59, zone = "Tirisfal Glades", tip = "Torre com 2 zeppelins. Pegue o pra Orgrimmar (nao Grom'gol)" },
			[68] = { str = "Pegue o zeppelin para Orgrimmar.", x = 61, y = 59, zone = "Tirisfal Glades", tip = "Espere na plataforma. Zeppelin demora ~5 min entre viagens" },
			[69] = { str = "Pegue o flight path em Orgrimmar #COORD[45,64]#.", x = 45, y = 64, zone = "Orgrimmar", tip = "Wind Rider Master perto da entrada sul de Orgrimmar" },
			[70] = { str = "Saia de Orgrimmar ao sul. Va ate Razor Hill.", x = 51, y = 44, zone = "Durotar", tip = "Siga a estrada principal ao sul" },
			[71] = { str = "Aceite #GETConscript of the Horde# de #NPCTakrin Pathseeker# #COORD[51,44]#.", x = 51, y = 44, zone = "Durotar", tip = "Na estrada perto de Razor Hill" },
			[72] = { str = "Va pro oeste e entre nos Barrens #COORD[35,42]#.", x = 35, y = 42, zone = "Durotar", tip = "Proximo guide: 12-15 Barrens. Boa jornada!" },
    	}
	},
}
