--[[--------------------------------------------------
003_Horde_50to60.lua
Authors: mrmr, lanjelin
Version: 1.04.3
------------------------------------------------------
Description: Guide Serie - 003 From Lvl 50 to Lvl 60
    1.04.1
        -- First Release
            Horde's Guide
            from level 50 to lever 60
    1.04.2
    	-- no changes in here for this revision
    1.04.3
	    -- Cleanup in text, changed formatting of coords
------------------------------------------------------
Connection:
--]]--------------------------------------------------

Table_003_Horde_50to60 = {
-----------50-50 Azshara
	--[501] = {
	[5049] = {
		title = "50-50 Azshara",
		n = "50-50 Azshara",
		pID = 414, nID = 502,
		itemCount = 23,
		items = {
			[1] = { str = "50-50 Azshara" },
			[2] = { str = "Aceite: #GETStealing Knowledge# " },
			[3] = { str = "Va fazer:" },
			[4] = { str = "#DOStealing Knowledge# Feito nas Ruins of Eldarath, #COORD[36,54]#", x = 36, y = 54, zone = "Azshara" },
			[5] = { str = "#DOSeeping Corruption# Tide Pools estao em: 1=#COORD[47,61]#, 2=#COORD[47,51]#, 3=#COORD[48,48]#, 4=#COORD[47,46]#", x = 47, y = 61, zone = "Azshara" },
			[6] = { str = "Quando estiverem prontas, entregue #INStealing Knowledge# ..aceite TODAS as 4 quests de entrega." },
			[7] = { str = "Entregue #INDelivery to Archmage Xylem#, tem um teleportador em #COORD[28,50]#,#VIDEOSee Video# ... aceite #GETXylem's Payment to Jediga# ", x = 28, y = 50, zone = "Azshara" },
			[8] = { str = "Depois voe pra Thunder Bluff.." },
			[9] = { str = "Entregue #INDelivery to Magatha# (em Elder Rise) ... aceite #GETMagatha's Payment to Jediga# " },
			[10] = { str = "Use Hearthstone pra Orgrimmar." },
			[11] = { str = "Va entregue #INRise of the Silithid# ... aceite #GETMarch of the Silithid# em #COORD[56,46]#", x = 56, y = 46, zone = "Azshara" },
			[12] = { str = "Entregue #INDelivery to Jes'rimon# em #COORD[55,34]# ... aceite #GETJes'rimon's Payment to Jediga# e #GETBone-Bladed Weapons# ", x = 55, y = 34, zone = "Azshara" },
			[13] = { str = "Depois entregue #INRipple Delivery# em #COORD[59,36]#  (Se voce fez a secao de Hinterlands)", x = 59, y = 36, zone = "Azshara" },
		--L- Remove Ripple Delivery as the quest cannot be accepet at given level
			[14] = { str = "Depois va pra The Undercity, va ate o Apothecarium Quarter..." },
			[15] = { str = "Entregue #INDelivery to Andron Gant# ... aceite #GETAndron's Payment to Jediga# " },
			[16] = { str = "Depois entregue #INSeeping Corruption# e #INReturn to Apothecary Zinge# ... aceite #GETVivian Lagrave# enquanto estiver la." },
			[17] = { str = "Depois aceite #GETSeeping Corruption# ... depois entregue (no tauren bem do lado dele) ..." },
			[18] = { str = "... Depois complete #INSeeping Corruption# pela ultima vez." },
			[19] = { str = "Depois aceite #GETA Sample of Slime...# e #GET... and a Batch of Ooze# " },
			[20] = { str = "Depois voe pra Raventusj Village..." },
			--[22] = { str = "." },
			--[23] = { str = "." },
		}
	},

-----------50-50 Hinterlands
	--[502] = {
	[5050] = {
		title = "50-50 Hinterlands",
		--n = "50-50 Hinterlands",
		--pID = 501, nID = 503,
		--itemCount = 20,
		items = {
			[1] = { str = "50-50 Hinterlands" },
			[2] = { str = "Aceite: #GETSnapjaws, Mon!# #GETGammerita, Mon!# (Elite) e #GETLard Lost His Lunch# " },
			[3] = { str = "Va fazer na seguinte ordem:" },
			[4] = { str = "#DOSnapjaws, Mon!# junto com #DOGammerita, Mon!# e #DOWhiskey Slim's Lost Grog# " },
			[5] = { str = "#DOCortello's Riddle# em #COORD[80,46]#, bau pequeno na agua, bolsa de 14 slots junto com 8800 XP", x = 80, y = 46, zone = "The Hinterlands" },
			[6] = { str = "#DOLard Lost His Lunch# em #COORD[84,42]#", x = 84, y = 42, zone = "The Hinterlands" },
			[7] = { str = "Depois va entregue #INSnapjaws, Mon!# #INGammerita, Mon!# e #INLard Lost His Lunch# " },
			[8] = { str = "Depois va fazer #DOSprinkle's Secret Ingredient# em #COORD[41,60]#", x = 41, y = 60, zone = "The Hinterlands" },
			[9] = { str = "Depois use Hearthstone pra Orgrimmar." },
			[10] = { str = "Voe pra Azshara." },
			[11] = { str = "Entregue todas as 4 quests de entrega." },
			[12] = { str = "Voe pra XRs." },
			[13] = { str = "Sete XRs como seu lar." },
			[14] = { str = "Voe pra Ratchet." },
			[15] = { str = "Pegue o #NPCStone Circle# na loja de Liv Rizzlefix ... tambem aceite #GETVolcanic Activity# enquanto estiver la." },
			[16] = { str = "Pegue o barco pra ir pra BB" },
			[17] = { str = "Voe pra Stonard (swamp of sorrows).." },
			[18] = { str = "Entre em Blasted Lands..." },
			--[19] = { str = "." },
			--[20] = { str = "." },
		}
	},

-----------50-51 Blasted Lands
	--[503] = {
	[5051] = {
		title = "50-51 Blasted Lands",
		--n = "50-51 Blasted Lands",
		--pID = 502, nID = 504,
		--itemCount = 27,
		items = {
			[1] = { str = "50-51 Blasted Lands" },
			[2] = { str = "Eu depois encontro todos os itens pra completar essas 5 quests:" },
			[3] = { str = "#DOA Boar's Vitality# " },
			[4] = { str = "#DOSnickerfang Jowls# " },
			[5] = { str = "#DOThe Basilisk's Bite# " },
			[6] = { str = "#DOThe Decisive Striker# " },
			[7] = { str = "#DOVulture's Vigor# " },
			[8] = { str = "Voce precisa encontrar essa quantidade de itens pra completar essas quests:" },
			[9] = { str = "#NPCVulture Gizzards# x14" },
			[10] = { str = "#NPCBasilisk Brain# x11" },
			[11] = { str = "#NPCBlasted Boar Lungs# x6" },
			[12] = { str = "#NPCScorpok Pincers# x6" },
			[13] = { str = "#NPCSnickerfang Jowls# x5" },
			[14] = { str = "Enquanto estiver em Blasted Lands, eu descubro a maioria de todas as areas pra XP." },
			[15] = { str = "Se um #NPCImperfect Draenethyst Fragment dropa entregue pra essa quest: #INEverything Counts In Large Amounts# " },
			[16] = { str = "NOTA: Eu NUNCA encontrei um #NPCFlawless Draenethyst Sphere# pra quest #INTo Serve Kum'isha# ..boa sorte com isso." },
			[17] = { str = "Entregue todas as quests." },
			[18] = { str = "Eu entrego #INThe Decisive Striker# por ultimo pra Ground Scorpok Assay (+50 de agilidade)" },
			[19] = { str = "Depois use Hearthstone pra XRs." },
			[20] = { str = "Voe pra Tanaris (PEGUE UM MITHRIL CASING pra uma quest futura em Un'Goro!!!)" },
			[21] = { str = "Entregue #INSprinkle's Secret Ingredient# ... aceite #GETDelivery for Marin# " },
			[22] = { str = "Entregue #INMarch of the Silithid# ... aceite #GETBungle in the Jungle# " },
			[23] = { str = "Entregue #INDelivery for Marin# ...aceite #GETNoggenfogger Elixir# depois entregue." },
			[24] = { str = "Va entregue #INThe Stone Circle# em #COORD[52,46]# em Tanaris", x = 52, y = 46, zone = "Tanaris" },
			[25] = { str = "Depois entre em Un'Goro Crater..." },
			--[26] = { str = "." },
			--[27] = { str = "." },
		}
	},

-----------51-52 Un'Goro Crater
	--[504] = {
	[5152] = {
		title = "51-52 Un'Goro Crater",
		--n = "51-52 Un'Goro Crater",
		--pID = 503, nID = 505,
		--itemCount = 56,
		items = {
			[1] = { str = "51-52 Un'Goro Crater" },
			[2] = { str = "Va aceitar: #GETThe Apes of Un'Goro# e #GETThe Fare of Lar'korwi# em #COORD[71,75]#", x = 71, y = 75, zone = "Un'Goro Crater" },
			[3] = { str = "Va fazer #DOThe Fare of Lar'korwi# em #COORD[68,56]#", x = 68, y = 56, zone = "Un'Goro Crater" },
			[4] = { str = "Depois va comecar a fazer: #DOSuper Sticky# (ao norte no meio) ate esse item dropar #NPCA Mangled Journal#" },
			[5] = { str = "Depois va ate Marshal's Refuge #COORD[43,10]#, aceite TODAS as quests la: #GETChasing A-Me 01# #GETShizzle's Flyer# #GETLost!# #GETBeware of Pterrordax# #GETRoll the Bones# #GETAlien Ecology# #GETExpedition Salvation# #GETLarion and Muigin# ", x = 43, y = 10, zone = "Un'Goro Crater" },
			[6] = { str = "Entregue #INWilliden's Journal# " },
			[7] = { str = "Pegue o FP la, depois va fazer o Grind de Ungoro :) ..." },
			[8] = { str = "NOTA: nao se preocupe com os montes de terra de ungoro, voce vai encontrar terra suficiente dos drops de mobs. Tambem nao me preocupo com os Bloodpetal Sprouts, pois nao sao entregues por nenhum XP." },
			[9] = { str = "Enquanto faz quests, encontre 7 cristais de cada cor (vermelho, azul, verde e amarelo pra quest #DOCrystals of Power#)" },
			[10] = { str = "#DOSuper Sticky# " },
			[11] = { str = "#DOThe Apes of Un'Goro# junto com #DOChasing A-Me 01# (se voce tem um #NPCmithril casing# faca a escolta) #COORD[63,17]#", x = 63, y = 17, zone = "Un'Goro Crater" },
			[12] = { str = "#DOLarion and Muigin# " },
			[13] = { str = "#DOBeware of Pterrordax# junto com #DOShizzle's Flyer# e.." },
			[14] = { str = "#DORoll the Bones# " },
			[15] = { str = "#DOExpedition Salvation# #COORD[68,36]# e #COORD[38,65]#", x = 68, y = 36, zone = "Un'Goro Crater" },
			[16] = { str = "#DO... and a Batch of Ooze# (Certifique-se de pegar pelo menos 30 amostras de ooze)" },
			[17] = { str = "Va entregue #INThe Apes of Un'Goro# ... aceite #GETThe Mighty U'cha# " },
			[18] = { str = "Entregue #INThe Fare of Lar'korwi# ... aceite #GETThe Scent of Lar'korwi# " },
			[19] = { str = "Depois va fazer:" },
			[20] = { str = "#DOBone-Bladed Weapons# junto com #DOThe Scent of Lar'korwi# " },
			[21] = { str = "#GETIt's a Secret to Everybody# ... clique no barco e depois na bolsa debaixo d'agua em #COORD[63,68]#", x = 63, y = 68, zone = "Un'Goro Crater" },
			[22] = { str = "Depois entregue #INThe Scent of Lar'korwi# ... aceite #GETThe Bait for Lar'korwi# #COORD[71,75]#", x = 71, y = 75, zone = "Un'Goro Crater" },
			[23] = { str = "Depois va fazer #DOAlien Ecology# junto com #DOBungle in the Jungle# #COORD[50,80]#", x = 50, y = 80, zone = "Un'Goro Crater" },
			[24] = { str = "Va aceitar #GETFinding the Source# em #COORD[30,50]#, depois faca junto com #DOVolcanic Activity# ", x = 30, y = 50, zone = "Un'Goro Crater" },
			[25] = { str = "O caminho do hotspot pra quest #DOFinding the Source# comeca em #COORD[51,42]# e o hot spot fica em #COORD[50,46]#  (#VIDEOSee Video on where to find the hotspot#)", x = 51, y = 42, zone = "Un'Goro Crater" },
			[26] = { str = "#DOLost!# Certifique-se que todas as quests estejam prontas antes de fazer essa (alem de #NPCThe Mighty U'cha# e #NPCThe Bait for Lar'korwi# ), depois..." },
			[27] = { str = "...Isso leva de volta ao Marshal's Refuge, Entregue TODAS as quests la, aceite novas (incluindo todas as quests de Pylon na caverna)." },
			[28] = { str = "Depois va fazer (na seguinte ordem):" },
			[29] = { str = "#DOThe Northern Pylon# em #COORD[56,13]#", x = 56, y = 13, zone = "Un'Goro Crater" },
			[30] = { str = "#DOThe Mighty U'cha# caverna em #COORD[63,13]#", x = 63, y = 13, zone = "Un'Goro Crater" },
			[31] = { str = "#DOThe Eastern Pylon# em #COORD[77,50]#", x = 77, y = 50, zone = "Un'Goro Crater" },
			[32] = { str = "#DOThe Bait for Lar'korwi# #COORD[80,50]#. Depois entregue junto com #INThe Mighty U'cha# #COORD[71,75]#", x = 71, y = 75, zone = "Un'Goro Crater" },
			[33] = { str = "Va pro oeste matando oozes pelo caminho.." },
			[34] = { str = "Entregue #INFinding the Source# ... aceite #GETThe New Springs# #COORD[30,50]#", x = 30, y = 50, zone = "Un'Goro Crater" },
			[35] = { str = "#DOThe Western Pylon# em #COORD[23,58]#", x = 23, y = 58, zone = "Un'Goro Crater" },
			[36] = { str = "Volte pra Marshal's Refuge matando oozes pelo caminho.." },
			[37] = { str = "Entregue quests. certifique-se de completar #DOMaking Sense of It# (so fale com o gnomo na caverna)" },
			[38] = { str = "Voe pra Tanaris." },
			[39] = { str = "Entregue #INSuper Sticky# e #INBungle in the Jungle# ... Eu PULO #NPCPawn Captures Queen# " },
			[40] = { str = "Depois voe pra Thunder Bluff." },
			[41] = { str = "Va ate Elder Rise." },
			[42] = { str = "Aceite #GETUn'goro Soil# .. depois entregue ... aceite #GETMorrowgrain Research# .. depois entregue..." },
			[43] = { str = "...mas PULE a proxima parte (a parte que diz trazer 10 Morrowgrain)" },
			[44] = { str = "Va pegar novas magias/habilidades." },
			[45] = { str = "Use Hearthstone pra XRs." },
			[46] = { str = "Depois voe pra Ratchet.." },
			[47] = { str = "Entregue #INVolcanic Activity# e #INMarvon's Workshop# - Eu PULO #NPCZapper Fuel# " },
			[48] = { str = "Pegue o barco pra ir pra BB.." },
			[49] = { str = "Entregue #INWhiskey Slim's Lost Grog# " },
			[50] = { str = "Tambem entregue #INRescue OOX-17/TN!# (se voce fez)" },
			[51] = { str = "Voe pra Kargath (Badlands).." },
			[52] = { str = "Entregue #INVivian Lagrave# " },
			[53] = { str = "Aceite: #GETDreadmaul Rock# e #GETThe Rise of the Machines# " },
			[54] = { str = "Depois voe pra Burning Steppes..." },
			--[55] = { str = "." },
			--[56] = { str = "." },
		}
	},

-----------52-53 Burning Steppes
	--[505] = {
	[5253] = {
		title = "52-53 Burning Steppes",
		--n = "52-53 Burning Steppes",
		--pID = 504, nID = 506,
		--itemCount = 18,
		items = {
			[1] = { str = "52-53 Burning Steppes" },
			[2] = { str = "Aceite: #GETBroodling Essence# e #GETTablet of the Seven# " },
			[3] = { str = "Depois va fazer:" },
			[4] = { str = "#DOBroodling Essence# (pro leste) (tambem mate o maximo de dragon whelps que voce ver, sao mobs fracos que morrem bem rapido)" },
			[5] = { str = "#DODreadmaul Rock# #COORD[79,45]#... depois #DOKrom'Grul# (Krom'Grul tem 2 pontos de spawn diferentes, em qualquer uma das cavernas)", x = 79, y = 45, zone = "Burning Steppes" },
			[6] = { str = "#DOThe Rise of the Machines# " },
			[7] = { str = "#DOTablet of the Seven# fica em #COORD[54,40]#", x = 54, y = 40, zone = "Burning Steppes" },
			[8] = { str = "Va entregue #INTablet of the Seven# e #INBroodling Essence# ... aceite #GETFelnok Steelspring# " },
			[9] = { str = "Depois voe pra Kargath (Badlands)" },
			[10] = { str = "Entregue #INKrom'Grul# " },
			[11] = { str = "Entregue #INThe Rise of the Machines# ... aceite #GETThe Rise of the Machines# parte2" },
			[12] = { str = "Va entregue #INThe Rise of the Machines# parte2 em #COORD[25,46]# em Badlands", x = 25, y = 46, zone = "Badlands" },
			[13] = { str = "Depois use Hearthstone pra XRs." },
			[14] = { str = "Depois voe pra Orgrimmar e sete como seu lar." },
			[15] = { str = "Va entregue #INBone-Bladed Weapons# #COORD[55,34]#", x = 55, y = 34, zone = "Orgrimmar" },
			[16] = { str = "Voe pra Azshara..." },
			--[17] = { str = "." },
			--[18] = { str = "." },
		}
	},

--------------53-54 Azshara
	--[506] = {
	[5354] = {
		title = "53-54 Azshara",
		--n = "53-54 Azshara",
		--pID = 505, nID = 507,
		--itemCount = 28,
		items = {
			[1] = { str = "53-54 Azshara" },
			[2] = { str = "Aceite #GETBetrayed# " },
			[3] = { str = "Va entregue #INThe Hunter's Charm#, essa e uma quest so de hunter, em #COORD[41,42]# ... aceite #GETCourser Antlers# " },
			[4] = { str = "Va aceitar #GETKim'jael Indeed!# em #COORD[52,22]# no topo da colina", x = 52, y = 22, zone = "Azshara" },
			[5] = { str = "Depois va fazer:" },
			[6] = { str = "#DOCourser Antlers# " },
			[7] = { str = "#DOBetrayed# " },
			[8] = { str = "#DOKim'jael Indeed!# " },
			[9] = { str = "NOTA: Eu grindo bastante nos bloodelfs enquanto faco essas 2 quests." },
			[10] = { str = "Quando essas 3 quests estiverem prontas, va entregue #INKim'jael Indeed!# ... aceite #GETKim'jael's Missing Equipment# " },
			[11] = { str = "Entregue #INCourser Antlers# ... aceite #GETWavethrashing# " },
			[12] = { str = "Depois va fazer:" },
			[13] = { str = "#DOKim'jael's Missing Equipment# " },
			[14] = { str = "#DOWavethrashing# " },
			[15] = { str = "Quando ambas estiverem prontas, use Hearthstone pra Orgrimmar." },
			[16] = { str = "Depois voe pra Azshara.." },
			[17] = { str = "Entregue #INBetrayed# ... aceite #GETBetrayed# " },
			[18] = { str = "Entregue #INWavethrashing# ... eu PULO #NPCThe Green Drake# " },
			[19] = { str = "Entregue #INKim'jael's Missing Equipment# " },
			[20] = { str = "Nesse ponto eu geralmente estou a 3/4 do caminho pro lvl 54, eu grindo meu caminho ate o level 54 nos BloodElfs." },
			[21] = { str = "Eu grindo bloodelfs, porque sao mobs fracos (mobs que tem 30% menos vida/armadura que o mob medio desse level). Eu costumava grindar satyrs em speed runs anteriores, mas consegui cortar quase uma hora inteira com os blood elfs." },
			[22] = { str = "OPCIONAL: Em vez do grind voce poderia ir fazer a instancia BRD." },
			[23] = { str = "Quando eu chegar no 54 (ou algumas barras apos), eu uso Hearthstone pra Orgrimmar." },
			[24] = { str = "Eu depois vou entregue #INBone-Bladed Weapons# e #INBetrayed# " },
			[25] = { str = "Depois voe pra Splintertree Post (Ashenvale).." },
			[26] = { str = "Depois entre em Felwood..." },
			--[27] = { str = "." },
			--[28] = { str = "." },
		}
	},

-----------54-54 Felwood
	--[507] = {
	[5454] = {
		title = "54-54 Felwood",
		--n = "54-54 Felwood",
		--pID = 506, nID = 508,
		--itemCount = 16,
		items = {
			[1] = { str = "54-54 Felwood" },
			[2] = { str = "Aceite #GETTimbermaw Ally# em #COORD[50,85]# (??? TBC Quest?) So fale com o NPC la e ele vai te dar.", x = 50, y = 85, zone = "Felwood" },
			[3] = { str = "Va aceitar #GETForces of Jaedenar# e #GETVerifying the Corruption# no Emerald Sanctuary #COORD[51,82]#.", x = 51, y = 82, zone = "Felwood" },
			[4] = { str = "Va aceitar #GETCleansing Felwood# em #COORD[46,84]#", x = 46, y = 84, zone = "Felwood" },
			[5] = { str = "Eu comeco matando oozes, eu me certifico de matar uns 30/40 oozes aqui no total pra quest #DOA Sample of Slime...# #COORD[40,68]#", x = 40, y = 68, zone = "Felwood" },
			[6] = { str = "Depois va completar #DOForces of Jaedenar# #COORD[38,60]#", x = 38, y = 60, zone = "Felwood" },
			[7] = { str = "Depois va ate BloodVenom Post. #COORD[34,52]#", x = 34, y = 52, zone = "Felwood" },
			[8] = { str = "Aceite: #GETA Husband's Last Battle# e #GETWild Guardians# " },
			[9] = { str = "Pegue o FP la." },
			[10] = { str = "Depois va fazer na seguinte ordem:" },
			[11] = { str = "#DOVerifying the Corruption# (Elite) #COORD[41,41]#", x = 41, y = 41, zone = "Felwood" },
			[12] = { str = "#DOCleansing Felwood# #COORD[54,16]#", x = 54, y = 16, zone = "Felwood" },
			[13] = { str = "Va aceitar #GETDeadwood of the North# (em 64.8) mas NAO faca agora.", x = 64, y = 8, zone = "Felwood" },
			[14] = { str = "Grinde seu caminho pela caverna pra ir pra Winterspring..." },
			--[15] = { str = "." },
			--[16] = { str = "." },
		}
	},

-----------54-55 Winterspring
	--[508] = {
	[5455] = {
		title = "54-55 Winterspring",
		--n = "54-55 Winterspring",
		--pID = 507, nID = 509,
		--itemCount = 31,
		items = {
			[1] = { str = "54-55 Winterspring" },
			[2] = { str = "Saia da caverna e aceite #GETWinterfall Activity# logo na saida." },
			[3] = { str = "Va ate Donova Snowden em #COORD[31,45]#", x = 31, y = 45, zone = "Winterspring" },
			[4] = { str = "Entregue #INThe New Springs# e #INIt's a Secret to Everybody# e aceite #GETStrange Sources#" },
			[5] = { str = "NOTA: Eu PULO #NPCThe Videre Elixir# e o resto dessa cadeia." },
			[6] = { str = "Va ate Everlook.. #COORD[61,38]#", x = 61, y = 38, zone = "Winterspring" },
			[7] = { str = "Aceite: #GETAre We There, Yeti?# #GETThe Everlook Report# #GETDuke Nicholas Zverenhoff# #GETSister Pamela# #GETTrouble in Winterspring# e #GETUrsius of the Shardtooth#" },
			[8] = { str = "Entregue #INFelnok Steelspring# ... aceite #GETChillwind Horns# " },
			[9] = { str = "Sete Everlook como seu lar." },
			[10] = { str = "Va fazer #DOUrsius of the Shardtooth# (so fique grindando mobs na colina ao norte de everlook ate #NPCUrsius# aparecer)" },
			[11] = { str = "Depois entregue #INUrsius of the Shardtooth# ... aceite #GETBrumeran of the Chillwind# " },
			[12] = { str = "Va fazer #DOBrumeran of the Chillwind# ele patrulha perto de #COORD[60,60]#", x = 60, y = 60, zone = "Winterspring" },
			[13] = { str = "Depois va descobrir Darkwhisper Gorge em #COORD[59,73]# pra quest #DOStrange Sources# ", x = 59, y = 73, zone = "Winterspring" },
			[14] = { str = "Depois use Hearthstone de volta pra Everlook." },
			[15] = { str = "Entregue #INBrumeran of the Chillwind# ... PULE #NPCShy-Rotam# " },
			[16] = { str = "Depois va fazer as seguintes quests (passos 17-20, em qualquer ordem) pro oeste e algumas ao norte. Quando estiver no oeste lembre-se de entregar #INTrouble in Winterspring# e aceitar #GETThreat of the Winterfall#:" },
			[17] = { str = "#DOAre We There, Yeti?# " },
			[18] = { str = "#DOThreat of the Winterfall# voce deveria encontrar #NPCEmpty Firewater Flask# que inicia #GETWinterfall Firewater# enquanto faz essa quest. Quando o item #NPCWinterfall Ritual Totem# dropar, guarde e coloque no seu banco, voce vai precisar depois." },
			[19] = { str = "#DOWild Guardians# (os Ragged Owls ficam a oeste de Everlook, e os Raging Owls ficam ao norte de Everlook)" },
			[20] = { str = "#DOChillwind Horns#, voce pode encontrar uma concentracao maior de chimaera perto de #COORD[66,29]#", x = 66, y = 29, zone = "Winterspring" },
			[21] = { str = "Quando #DOThreat of the Winterfall# e #DOWinterfall Firewater# estiverem completas va entregar junto com #INStrange Sources# em #COORD[31,45]#... aceite #GETFalling to Corruption# ", x = 31, y = 45, zone = "Winterspring" },
			[22] = { str = "Quando o resto dessas quests estiverem completas, volte pra Everlook e entregue #INAre We There, Yeti?# ...aceite #GETAre We There, Yeti?# parte2. Entregue #INChillwind Horns# ... eu PULO #NPCReturn to Tinkee# " },
			[23] = { str = "Depois va fazer:" },
			[24] = { str = "#DOWinterfall Activity# #COORD[67,37]#", x = 67, y = 37, zone = "Winterspring" },
			[25] = { str = "#DOAre We There, Yeti?# (encontre 2 Pristine Yeti Horns) #COORD[66,43]#", x = 66, y = 43, zone = "Winterspring" },
			[26] = { str = "Depois use Hearthstone pra Everlook e aceite #GETA Strange One #" },
			[27] = { str = "Va entregue #INAre We There, Yeti?# ... aceite #GETAre We There, Yeti?# parte3" },
			[28] = { str = "Va assustar Legacki com o mechanical yeti pra quest #DOAre We There, Yeti?# parte3" },
			[29] = { str = "Depois voe pra Felwood..." },
			--[30] = { str = "." },
			--[31] = { str = "." },
		}
	},

-----------55-55 Felwood
	--[509] = {
	[5554] = {
		title = "55-55 Felwood",
		--n = "55-55 Felwood",
		--pID = 508, nID = 510,
		--itemCount = 31,
		items = {
			[1] = { str = "55-55 Felwood" },
			[2] = { str = "Entregue #INWild Guardians# ... Aceite #GETWild Guardians# parte2 e #GETWell of Corruption#" },
			[3] = { str = "Va entregue #INCleansing Felwood# ... depois pegue um cenarion beacon pra quest #DOSalve Via Hunting# (so fale com o NPC pra pegar) #COORD[46,83]#", x = 46, y = 83, zone = "Felwood" },
			[4] = { str = "Va entregue #INVerifying the Corruption# e #INForces of Jaedenar# ... aceite #GETCollection of the Corrupt Water# #COORD[51,82]#", x = 51, y = 82, zone = "Felwood" },
			[5] = { str = "Va fazer na seguinte ordem:" },
			[6] = { str = "Va fazer #DOA Husband's Last Battle# junto com #DOTimbermaw Ally# #COORD[48,94]#", x = 48, y = 94, zone = "Felwood" },
			[7] = { str = "Quando estiverem prontas va entregue #INTimbermaw Ally# em #COORD[50,85]# ... aceite #GETSpeak to Nafien#", x = 50, y = 85, zone = "Winterspring" },
			[8] = { str = "Va fazer #DOWell of Corruption# em #COORD[32,66]#. Tambem certifique-se de coletar 6 #NPCCorrupted Soul Shards# pra quest #DOSalve Via Hunting# ", x = 32, y = 66, zone = "Felwood" },
			[9] = { str = "#DOCollection of the Corrupt Water# #COORD[35,59]#", x = 35, y = 59, zone = "Felwood" },
			[10] = { str = "Depois va ate Bloodvenom Post" },
			[11] = { str = "Entregue #INA Husband's Last Battle# e #INWell of Corruption# ... aceite #GETCorrupted Sabers# " },
			[12] = { str = "Va entregue #INSalve Via Hunting# (os 6 Corrupted Soul Shards) #COORD[46,83]#", x = 46, y = 83, zone = "Felwood" },
			[13] = { str = "Va entregue #INCollection of the Corrupt Water# ... Eu PULO #NPCSeeking Spiritual Aid# #COORD[51,82]# ", x = 51, y = 82, zone = "Felwood" },
			[14] = { str = "Va fazer #DOCorrupted Sabers# #COORD[32,66]# depois va entregue. (NOTA: quando voce entregar, voce tem que falar com o gato primeiro quando chegar no NPC)", x = 32, y = 66, zone = "Felwood" },
			[15] = { str = "Depois va pro norte e faca:" },
			[16] = { str = "#DODeadwood of the North# (61.9) Quando o item Deadwood Ritual Totem dropar, guarde e coloque no seu banco quando tiver chance, voce vai precisar depois.", x = 61, y = 9, zone = "Felwood" },
			[17] = { str = "#DOFalling to Corruption# (o caldeirao em 60.5) (dica: eu uso meu pet pra distrair os mobs enquanto faco essa quest) ... depois aceite #GETMystery Goo# ", x = 60, y = 5, zone = "Felwood" },
			[18] = { str = "Va entregue #INDeadwood of the North# (64.8) ... aceite #GETSpeak to Salfa# . E entregue #INSpeak to Nafien# ", x = 64, y = 8, zone = "Felwood" },
			[19] = { str = "Depois corra pela caverna (voce deveria estar Unfriendly com Timbermaw, entao eles nao deveriam te atacar).." },
			[20] = { str = "Entregue #INWinterfall Activity# e #INSpeak to Salfa# " },
			[21] = { str = "Depois va entregue #INMystery Goo# em #COORD[31,45]# em Winterspring ... PULE #NPCToxic Horrors# ", x = 31, y = 45, zone = "Winterspring" },
			[22] = { str = "Depois use Hearthstone pra Everlook." },
			[23] = { str = "Voe pra Orgrimmar e sete como seu lar." },
			[24] = { str = "Se voce encontrar #NPCWarcaller Gorlach#, aceite #GETA Call To Arms: The Plaguelands!# " },
			[25] = { str = "Voe pra Thunder Bluff, depois direto pra Camp Mojache, Ferelas" },
			[26] = { str = "Entregue #INThe Strength of Corruption# " },
			[27] = { str = "Depois voe pra Tanaris..." },
			[28] = { str = "Va assustar #NPCSprinkle# com o mechanical yeti pra quest #DOAre We There, Yeti?# parte3" },
			[29] = { str = "Depois voe pra Silithus" },
			--[30] = { str = "." },
			--[31] = { str = "." },
		}
	},

-----------55-55 Silithus
	--[510] = {
	[5555] = {
		title = "55-55 Silithus",
		--n = "55-55 Silithus",
		--pID = 509, nID = 511,
		--itemCount = 25,
		items = {
			[1] = { str = "55-55 Silithus" },
			[2] = { str = "Aceite: #GETThe Twilight Mystery# #GETSecuring the Supply Lines# e #GETDeadly Desert Venom# " },
			[3] = { str = "Va fazer: #DOSecuring the Supply Lines# e #DODeadly Desert Venom# (faca essas 2 quests a nordeste de Cenarion Hold)" },
			[4] = { str = "Depois entregue e aceite novas quests." },
			[5] = { str = "Depois va fazer:" },
			[6] = { str = "#DOStepping Up Security# " },
			[7] = { str = "#DOThe Twilight Mystery# " },
			[8] = { str = "#DONoggle's Last Hope# " },
			[9] = { str = "Quando as tres estiverem prontas, va entregue e aceite novas." },
			[10] = { str = "Va fazer:" },
			[11] = { str = "#DONoggle's Lost Satchel#, fica perto de #COORD[40,90]#", x = 40, y = 90, zone = "Silithus" },
			[12] = { str = "NOTA: Eu pulo #NPCWanted - Deathclasp, Terror of the Sands# (Elite) porque e muito dificil de solar no 55, mas faca se voce encontrar um grupo." },
			[13] = { str = "#DOThe Deserter# Ele esta na caverna em #COORD[67,71]# ... eu PULO #NPCThe Twilight Lexicon# ", x = 67, y = 71, zone = "Silithus" },
			[14] = { str = "Depois eu morro de proposito, pra acabar em Cenarion Hold." },
			[15] = { str = "Entregue #INNoggle's Lost Satchel# " },
			[16] = { str = "Depois va ate Marshal's Refuge em Un'Goro Crater." },
			[17] = { str = "Va assustar Quixxil com o mechanical yeti pra quest #DOAre We There, Yeti?# parte3" },
			[18] = { str = "Depois use Hearthstone pra Orgrimmar." },
			[19] = { str = "Va pra Under City." },
			[20] = { str = "Va completar #INA Sample of Slime...# e #IN... and a Batch of Ooze# " },
			[21] = { str = "Va aceitar #GETA Call To Arms: The Plaguelands!# " },
			[22] = { str = "Sete Under City como seu lar." },
			[23] = { str = "Va ate o Bulwark... (que e uma pequena vila a leste de Tirisfal Glades)" },
			--[24] = { str = "." },
			--[25] = { str = "." },
		}
	},

-----------55-56 Western Plaguelands
	--[511] = {
	[5556] = {
		title = "55-56 Western Plaguelands",
		--n = "55-56 Western Plaguelands",
		--pID = 510, nID = 512,
		--itemCount = 24,
		items = {
			[1] = { str = "55-56 Western Plaguelands" },
			[2] = { str = "Entregue #INA Call To Arms: The Plaguelands!# aceite #GETScarlet Diversions# ..." },
			[3] = { str = "... (certifique-se de pegar uma Flame in a Bottle primeiro, antes de fazer essa quest, esta na caixa)" },
			[4] = { str = "Entregue #INThe Everlook Report# " },
			[5] = { str = "Aceite e complete #DOArgent Dawn Commission# " },
			[6] = { str = "Aceite #GETA Plague Upon Thee# " },
			[7] = { str = "Entre em Western Plaguelands, Felstone field em #COORD[37,56]# e...", x = 37, y = 56, zone = "Western Plaguelands" },
			[8] = { str = "Aceite #GETBetter Late Than Never# (a mulher na casa)" },
			[9] = { str = "Depois va ate o celeiro ao lado, e..." },
			[10] = { str = "Complete #DOBetter Late Than Never# .. clique no bau de novo pra aceitar #GETBetter Late Than Never# de novo." },
			[11] = { str = "Va fazer #DOScarlet Diversions#, queime a tenda, e plante a bandeira #COORD[40,51]#  ", x = 40, y = 51, zone = "Western Plaguelands" },
			[12] = { str = "Volte pra o Bulwark.. (#VIDEONOTE:# Certifique-se de guardar todos os #NPCBone Fragments# que voce encontrar, voce vai precisar de 30 deles pra uma #NPCquest# futura)" },
			[13] = { str = "Entregue #INScarlet Diversions# ... aceite #GETAll Along the Watchtowers# (Elite) e #GETThe Scourge Cauldrons# " },
			[14] = { str = "Entregue #INThe Scourge Cauldrons# ... aceite #GETTarget: Felstone Field# " },
			[15] = { str = "Va completar toda a cadeia de quests do Caldeirao, voce precisa matar o Cauldron Lord em cada campo alvo (listados abaixo), pegar a chave deles e usar no caldeirao grande no meio do campo. (So fique indo e voltando do The Bulwark pro proximo campo completando cada um, entregando e depois aceitando e fazendo o proximo)..." },
			[16] = { str = "#DOTarget: Felstone Field# #COORD[37,56]#", x = 37, y = 56, zone = "Western Plaguelands" },
			[17] = { str = "#DOTarget: Dalson's Tears# #COORD[46,52]#. #VIDEONOTE:# Enquanto voce estiver aqui, tem uma pequena cadeia de quests aqui que comeca com um Diario pequeno no celeiro #COORD[47,50]# chamado #INMrs. Dalson's Diary# , so clique pra completar a quest. Agora, depois de fazer isso, voce precisa matar um #NPCWandering Skeleton# pra pegar uma chave que abre a casinha atras do celeiro. Depois de pegar a chave e abrir a casinha, vai soltar um #NPCFarmer Dalson#, um undead level 56. Mate ele, pegue a chave, e depois corra pra dentro da casa (que fica do lado do celeiro) e suba as escadas, la voce vai encontrar um armario, abra o armario com a chave (Pra quest #DOLocked Away# ) e finalmente acabou. Facil 10200 XP! Ou sera?", x = 46, y = 52, zone = "Western Plaguelands" },
			[18] = { str = "#DOTarget: Writhing Haunt# #COORD[53,65]# (enquanto estiver la aceite #GETThe Wildlife Suffers Too# em #COORD[53,64]#, o tauren quase morto na cabana", x = 53, y = 65, zone = "Western Plaguelands" },
			[19] = { str = "#DOTarget: Gahrron's Withering# #COORD[62,59]#", x = 62, y = 59, zone = "Western Plaguelands" },
			[20] = { str = "So fique indo e voltando completando cada um." },
			[21] = { str = "Depois va aceitar e completar #DOMission Accomplished!# " },
			[22] = { str = "Depois va pra Eastern Plaguelands..." },
			--[23] = { str = "." },
			--[24] = { str = "." },
		}
	},

-----------56-57 Eastern Plaguelands
	--[512] = {
	[5657] = {
		title = "56-57 Eastern Plaguelands",
		--n = "56-57 Eastern Plaguelands",
		--pID = 511, nID = 513,
		--itemCount = 38,
		items = {
			[1] = { str = "56-57 Eastern Plaguelands" },
			[2] = { str = "Va aceitar: #GETDemon Dogs# #GETBlood Tinged Skies# e #GETCarrion Grubbage# (em 7.43)", x = 7, y = 43, zone = "Eastern Plaguelands" },
			[3] = { str = "Grinde seu caminho ate #COORD[26,74]# e aceite: #GETTo Kill With Purpose# e #GETUn-Life's Little Annoyances# . NOTA: Eu PULO #NPCThe Ranger Lord's Behest# ", x = 26, y = 74, zone = "Eastern Plaguelands" },
			[4] = { str = "Desca na cripta em The Undercroft #COORD[27,85]# e aceite #GETHameya's Plea# (o pergaminho no chao). (??? TBC Quest?)", x = 27, y = 85, zone = "Eastern Plaguelands" },
			[5] = { str = "Grinde seu caminho ate Darrowshire #COORD[36,90]# enquanto faz essas quests:", x = 36, y = 90, zone = "Eastern Plaguelands" },
			[6] = { str = "#DODemon Dogs# " },
			[7] = { str = "#DOBlood Tinged Skies# " },
			[8] = { str = "#DOCarrion Grubbage# " },
			[9] = { str = "Depois entregue #INSister Pamela# ... aceite e faca #GETPamela's Doll# (sao 3 partes da boneca)" },
			[10] = { str = "Entregue #INPamela's Doll# ... aceite #GETAuntie Marlene# e #GETUncle Carlin# " },
			[11] = { str = "Depois va completar #DOBlood Tinged Skies# " },
			[12] = { str = "Depois certifique-se de matar 20 Plaguehound Runts pra quest #DODemon Dogs# " },
			[13] = { str = "Depois va ate Light's Hope Chapel em #COORD[81,60]#", x = 81, y = 60, zone = "Eastern Plaguelands" },
			[14] = { str = "Aceite: #GETZaeldarr the Outcast# e #GETThe Restless Souls# " },
			[15] = { str = "Entregue #INDuke Nicholas Zverenhoff# e #INUncle Carlin# ... aceite #GETDefenders of Darrowshire# " },
			[16] = { str = "Pegue o FP la. Depois va fazer:" },
			[17] = { str = "#DOTo Kill With Purpose# " },
			[18] = { str = "#DODefenders of Darrowshire# " },
			[19] = { str = "#DOHameya's Plea# #COORD[72,14]# (??? TBC Quest?)", x = 72, y = 14, zone = "Eastern Plaguelands" },
			[20] = { str = "#DODemon Dogs# " },
			[21] = { str = "#DOCarrion Grubbage# " },
			[22] = { str = "#DOUn-Life's Little Annoyances# " },
			[23] = { str = "#DOA Plague Upon Thee# (feito em Plaguewood ao norte)" },
			[24] = { str = "#DOAugustus' Receipt Book# pegue essa quest na cabana em #COORD[13,34]#, o livro esta la em cima na inn em #COORD[15,33]#", x = 15, y = 33, zone = "Eastern Plaguelands" },
			[25] = { str = "#DOThe Restless Souls# (#NPCEgan# esta na cabana em #COORD[13,34]#) (A proxima parte se refere a Stratholme, que eu pulo)", x = 13, y = 34, zone = "Eastern Plaguelands" },
			[26] = { str = "Depois va entregue: #INAugustus' Receipt Book# " },
			[27] = { str = "Grinde seu caminho pela caverna #COORD[15,29]# (cuidado nao e facil) ", x = 15, y = 29, zone = "Eastern Plaguelands" },
			[28] = { str = "#VIDEONOTE:# Se a caverna for muito dificil pra voce, outra alternativa facil e pegar o voo de Tower Gryphon da Plaguewood Tower #COORD[22,32]# pra Crown Guard tower #COORD[39,75]#, desde que a horde tenha controle das torres. Depois entregue #INDemon Dogs# #INBlood Tinged Skies# e #INCarrion Grubbage# aceite #GETRedemption# ... So fale com o cara pra completar ... Eu PULO #NPCOf Forgotten Memories# (voce pode tentar se encontrar um grupo)", x = 22, y = 32, zone = "Eastern Plaguelands" },
			[29] = { str = "Depois va entregue: #INTo Kill With Purpose# e #INUn-Life's Little Annoyances# em #COORD[26,74]#", x = 26, y = 74, zone = "Eastern Plaguelands" },
			[30] = { str = "Depois va fazer #DOZaeldarr the Outcast# #COORD[27,85]#", x = 27, y = 85, zone = "Eastern Plaguelands" },
			[31] = { str = "Depois va ate o monte de terra atras da cripta e entregue #INHameya's Plea# (??? TBC Quest?)" },
			[32] = { str = "Depois entregue: #INZaeldarr the Outcast# e #INDefenders of Darrowshire# em Light's Hope Chapel" },
			[33] = { str = "Use Hearthstone pra Under City.." },
			[34] = { str = "Entregue #INBetter Late Than Never# ... aceite #GETThe Jeremiah Blues# " },
			[35] = { str = "Entregue #INThe Jeremiah Blues# (logo embaixo do banco) ... aceite #GETGood Luck Charm# " },
			[36] = { str = "Volte pra o Bulwark..." },
			--[37] = { str = "." },
			--[38] = { str = "." },
		}
	},

-----------57-58 Western Plaguelands
	--[513] = {
	[5758] = {
		title = "57-58 Western Plaguelands",
		--n = "57-58 Western Plaguelands",
		--pID = 512, nID = 514,
		--itemCount = 37,
		items = {
			[1] = { str = "57-58 Western Plaguelands" },
			[2] = { str = "Entregue #INA Plague Upon Thee# ... aceite #GETA Plague Upon Thee# parte2." },
			[3] = { str = "Va entregue #INGood Luck Charm# ...aceite #GETTwo Halves Become One# A mulher na casa em #COORD[37,56]#", x = 37, y = 56, zone = "Western Plaguelands" },
			[4] = { str = "Faca #DOTwo Halves Become One# (#NPCJabbering ghouls# no Felstone Field dropam o item que voce precisa, quando pegar o item clique com botao direito no seu inventario), depois volte pra mulher na casa pra entregar." },
			[5] = { str = "Depois faca #DOA Plague Upon Thee# parte2 ... aceite #GETA Plague Upon Thee# parte3, tudo isso e feito em #COORD[48,31]#  " },
			[6] = { str = "Depois va aceitar #GETUnfinished Business# parte1 em #COORD[51,28]#, depois faca. Os mobs dessa quest estao em #COORD[50,42]# e #COORD[53,44]#", x = 51, y = 28, zone = "Western Plaguelands" },
			[7] = { str = "Entregue #INUnfinished Business# parte1 (de volta em #COORD[51,28]#) ... aceite #GETUnfinished Business# parte2, depois va fazer. Os 2 mobs dessa quest estao em #COORD[57,37]# e #COORD[54,24]#.", x = 55, y = 30, zone = "Western Plaguelands" },
			[8] = { str = "Entregue #INUnfinished Business# parte2 (de volta em #COORD[51,28]#) ... aceite #GETUnfinished Business# parte3, depois va fazer. Precisa subir na torre em #COORD[45,19]# em um lugar especifico, cuidado com Elites.", x = 51, y = 28, zone = "Western Plaguelands" },
			[9] = { str = "Depois entregue #INUnfinished Business# parte3" },
			[10] = { str = "Depois va completar e entregue #INThe Wildlife Suffers Too# ... aceite #GETThe Wildlife Suffers Too# parte2 #COORD[53,64]#", x = 53, y = 64, zone = "Western Plaguelands" },
			[11] = { str = "Faca #DOThe Wildlife Suffers Too# parte2, depois entregue ... aceite #GETGlyphed Oaken Branch# " },
			[12] = { str = "Va entregue #INAuntie Marlene#, na casa em #COORD[49,78]# ...aceite #GETA Strange Historian# ", x = 49, y = 78, zone = "Western Plaguelands" },
			[13] = { str = "Va pegar o anel pra #DOA Strange Historian# (o anel esta no cemiterio)" },
			[14] = { str = "Entre em Andorhal.." },
			[15] = { str = "Faca #DOAll Along the Watchtowers# enquanto vai ate a inn em #COORD[39,66]#", x = 39, y = 66, zone = "Western Plaguelands" },
			[16] = { str = "Entregue #INA Strange Historian# pro #NPCChromie# la em cima na inn em #COORD[39,68]# ... aceite #GETThe Annals of Darrowshire# e #GETA Matter of Time# ", x = 39, y = 68, zone = "Western Plaguelands" },
			[17] = { str = "Depois va fazer (enquanto grinda nos mobs):" },
			[18] = { str = "#DOAll Along the Watchtowers# (Elite) " },
			[19] = { str = "#DOA Matter of Time# #COORD[47,62]#", x = 47, y = 62, zone = "Western Plaguelands" },
			[20] = { str = "#DOThe Annals of Darrowshire# o livro pra essa quest esta no predio em #COORD[42,67]#, o livro real Annals of Darrowshire parece diferente dos outros, tem um tom mais claro na parte de cima das paginas, diferente dos outros que tem um tom mais escuro na parte de cima das paginas.", x = 42, y = 67, zone = "Western Plaguelands" },
			[21] = { str = "Va entregue #INA Matter of Time# e #INThe Annals of Darrowshire# ... aceite #GETCounting Out Time# e #GETBrother Carlin# " },
			[22] = { str = "Va fazer #DOCounting Out Time# depois entregue. (e repetivel mas voce so ganha XP uma vez)" },
			[23] = { str = "Eu depois continuo grindando mobs em Andorhal ate ficar Friendly com Argent Dawn, pra poder comprar Enriched Manna Biscuits (que regenera mana mais rapido ao beber). Assim que eu ficar friendly com AD, eu volto pro Bulwark.." },
			[24] = { str = "Entregue #INA Plague Upon Thee# parte3" },
			[25] = { str = "Entregue #INAll Along the Watchtowers# ... aceite #GETScholomance# " },
			[26] = { str = "Entregue #INScholomance# pro undead bem do lado dele ... aceite #GETSkeletal Fragments# " },
			[27] = { str = "Estoque #NPCEnriched Manna Biscuits# (que regenera mana mais rapido ao beber)" },
			[28] = { str = "Eu depois volto pra Andorhal, e grindo ate o level 58 enquanto faco a quest #DOSkeletal Fragments#." },
			[29] = { str = "Assim que eu chegar no 58 e #DOSkeletal Fragments# estiver pronta e voce tambem tiver 30 #NPCBone Fragments# (por favor note, se voce estiver longe dos 30 bone fragments, entao pode pular), depois volte pro Bulwark e entregue #INSkeletal Fragments# .. Eu PULO #NPCMold Rhymes With...# " },
			[30] = { str = "Eu entrego qualquer scourge stones que eu tenha." },
			[31] = { str = "Eu depois estoco #NPCEnriched Manna Biscuits# (umas 600? :D)" },
			[32] = { str = "Depois va pegar o zeppelin pra ir pra Orgrimmar. (enquanto espera, faca heavy runecloth bandages)" },
			[33] = { str = "Quando chegar em Orgrimmar pegue novas magias/habilidades." },
			[34] = { str = "Guarde 2/3 dos meus manna biscuits no banco." },
			[35] = { str = "Depois voe pra Winterspring..." },
			--[36] = { str = "." },
			--[37] = { str = "." },
		}
	},

-----------58-60 Winterspring
	--[514] = {
	[5860] = {
		title = "58-60 Winterspring",
		--n = "58-60 Winterspring",
		--pID = 513, nID = 514,
		--itemCount = 32,
		items = {
			[1] = { str = "58-60 Winterspring" },
			[2] = { str = "Primeira coisa que eu faco aqui e guardar meu pet no estabulo." },
			[3] = { str = "Depois sete Everlook como seu lar." },
			[4] = { str = "Entregue #INAre We There, Yeti?# parte3" },
			[5] = { str = "Aceite: #GETLuck Be With You# (Elite) e #GETUrsius of the Shardtooth# (Elite)" },
			[6] = { str = "Depois va domar um Winterspring Screecher (pra Claw Rank8) (va pro sul pra fazer isso)" },
			[7] = { str = "Depois use esse pet pra fazer #DOLuck Be With You# (so use seu pet pra distrair os gigantes enquanto pega os Frostmaul Shards)" },
			[8] = { str = "Depois use Hearthstone pra Everlook." },
			[9] = { str = "Va fazer #DOUrsius of the Shardtooth# (Elite) (so fique grindando mobs na colina ao norte de everlook ate Ursius aparecer)" },
			[10] = { str = "Va entregue #INLuck Be With You# (se estiver pronta) e #INUrsius of the Shardtooth# ... aceite #GETBrumeran of the Chillwind# (Elite)" },
			[11] = { str = "Depois va pro sul e faca:" },
			[12] = { str = "#DOBrumeran of the Chillwind# (Elite)" },
			[13] = { str = "#DOLuck Be With You# (Elite) (se voce ainda precisar terminar)" },
			[14] = { str = "#DOWild Guardians# parte2 (eu grindo bastante nas corujas no Owl Wing Thicket por algumas horas, antes de sair daqui)" },
			[15] = { str = "Depois quando eu estiver a algumas barras do 59, eu volto pra Everlook (NAO use hearthstone).." },
			[16] = { str = "Entregue #INLuck Be With You# e #INBrumeran of the Chillwind# ... eu PULO #NPCShy-Rotam# (Elite)" },
			[17] = { str = "Voe pra Bloodvenom Post (Felwood).." },
			[18] = { str = "Entregue #INWild Guardians# parte2 ... aceite #GETWild Guardians# parte3" },
			[19] = { str = "Depois use Hearthstone de volta pra Everlook." },
			[20] = { str = "Depois va ate o Owl Wing Thicket e faca #DOWild Guardians# parte3" },
			[21] = { str = "Eu continuo grindando nas Corujas ate estar no 59 e meio, depois..." },
			[22] = { str = "Eu morro de proposito, pra acabar em Everlook (nao use hearthstone)" },
			[23] = { str = "Depois voe pra Bloodvenom Post (Felwood).." },
			[24] = { str = "Entregue #INWild Guardians# parte3 e #INGuarding Secrets# ... aceite #GETGuarding Secrets# parte2" },
			[25] = { str = "Eu depois voo pra XRs, depois pra Thunderbluff, va ate Elder Rise.." },
			[26] = { str = "Entregue #INGuarding Secrets# parte2 e #INGlyphed Oaken Branch# (ambos em Nara Wildmane)" },
			[27] = { str = "Use Hearthstone de volta pra Everlook." },
			[28] = { str = "Nesse ponto eu geralmente estou a 3/4 do caminho pro 60." },
			[29] = { str = "Eu depois volto pro Owl Wing Thicket e Grindo ate 60. (Veja os Creditos Finais)" },
			[30] = { str = "." },
			[31] = { str = "." },
			[32] = { str = "PARABENS, voce e lvl60 agora!"},
			[33] = { str = "." },
			--[34] = { str = "." },
		}
	},
}
