--[[--------------------------------------------------
003_Alliance_40to50.lua
Authors: mrmr, lanjelin
Version: 1.04.3
------------------------------------------------------
Description: Guide Serie - 003 From Lvl 40 to Lvl 50
	1.04.1
		-- First Release
			Alliance's Guide
			from level 40 to lever 50
	1.04.2
		-- no changes in here for this revision
	1.04.3
		-- Added color codes
			Fixed various spelling errors
			Adjustment to coordinate visibility
------------------------------------------------------
Connection:
--]]--------------------------------------------------

Table_003_Alliance_40to50 = {
-----------40-41 Badlands
	--[401] = {
	[4041] = {
		title = "40-41 Badlands",
		--n = "40-41 Badlands",
		--pID = 312, nID = 402,
		--itemCount = 32,
		items = {
			[1] = { str = "40-41 Badlands" },
			[2] = { str = "Va ate #COORD[53,43]# aceite #GETFiery Blaze Enchantment#, #GETMirages#, e #GETA Dwarf and His Tools#", x = 53, y = 43, zone = "Badlands" },
			[3] = { str = "Pare em #COORD[42,52]# e entregue #INMartek the Exiled# aceite #GETIndurium#", x = 45, y = 52, zone = "Badlands" },
			[4] = { str = "Aceite #GETBarbecued Buzzard Wings#, #GETPearl Diving# (se voce tiver)" },
			[5] = { str = "Agora so tem uma area de buzzards. Entao pras 2 quests que precisam dos itens deles, mate sempre que ver um." },
			[6] = { str = "Va ate #COORD[25,44]# e aceite #GETStudy of the Elements: Rock pt.1# e #GETCoolant Heads Prevail# depois entregue de volta e aceite #GETGyro… What?# depois entregue de volta. ", x = 25, y = 44, zone = "Badlands" },
			[7] = { str = "Aceite #GETLiquid Stone# depois entregue de volta" },
			[8] = { str = "Grinde ate #COORD[66,21]# e abra a caixa para #DOMirages#", x = 66, y = 21, zone = "Badlands" },
			[9] = { str = "Grinde ate o dig site em #COORD[53,29]# e mate os anoes para #DOA Dwarf and His Tools# No lado direito do buraco em #COORD[53,33]# toque na nota na tenda para #DOA Sign of Hope#", x = 53, y = 29, zone = "Badlands" },
			[10] = { str = " Grinde ate #COORD[53,43]# e entregue #INMirages# aceite #GETScrounging#", x = 53, y = 43, zone = "Badlands" },
			[11] = { str = "Tambem entregue #INA Dwarf and His Tools# e #INA Sign of Hope# aceite a proxima parte pra Uldaman" },
			[12] = { str = "Grinde ate #COORD[61,54]# e aceite #GETTremors of the Earth# Os ogros spawnam em #COORD[62,70]# e andam ate #COORD[29,56]# entao mate se voce ver. O boss e facil de puxar pelas costas, com o add pequeno ou nenhum.", x = 61, y = 54, zone = "Badlands" },
			[13] = { str = "Va pro sul ate #COORD[62,70]# e mate ogros aqui para #DOScrounging# e esperamos que o boss esteja aqui. Nao tem muitos ogros entao nao se preocupe ", x = 62, y = 70, zone = "Badlands" },
			[14] = { str = "Grinde ate #COORD[50,62]#, entregue #INFind Agmond# aceite #GETMurdaloc#", x = 50, y = 62, zone = "Badlands" },
			[15] = { str = "Va logo ao sul ate o camp de gnolls e faca #DOMurdaloc# e #DOIndurium#" },
			[16] = { str = "Va ate #COORD[42,52]# e entregue #INBarbecued Buzzard Wings# e #INIndurium# aceite #GETNews for Fizzle#", x = 45, y = 52, zone = "Badlands" },
			[17] = { str = "Va ate #COORD[18,41]# e mate os lesser rock elementals para #DOStudy of the Elements: Rock pt.1# e #DOBadlands Reagent Run#", x = 18, y = 41, zone = "Badlands" },
			[18] = { str = "Volte pra #COORD[26,44]# entregue #INStudy of the Elements: Rock pt.1# aceite #GETStudy of the Elements: Rock pt.2# e faca matando rock elementals", x = 26, y = 44, zone = "Badlands" },
			[19] = { str = "Volte pra #COORD[26,44]# entregue #INStudy of the Elements: Rock pt.2# aceite #GETStudy of the Elements: Rock pt.3#", x = 26, y = 44, zone = "Badlands" },
			[20] = { str = "Mate buzzards em #COORD[15,60]# e coyotes em #COORD[33,62]# para #DOBadlands Reagent Run# se ainda precisar", x = 33, y = 62, zone = "Badlands" },
			[21] = { str = "Grinde ate #COORD[11,77]# e mate ogros para #DOScrounging#", x = 11, y = 77, zone = "Badlands" },
			[22] = { str = "Mate greater rock elementals em #COORD[14,88]# para #DOStudy of the Elements: Rock#", x = 14, y = 88, zone = "Badlands" },
			[23] = { str = "Volte pra #COORD[26,44]# entregue #INStudy of the Elements: Rock pt.3# aceite #GETThis Is Going To Be Hard pt.1# vire e entregue, aceite #GETThis Is Going To Be Hard pt.2# depois vire e entregue, aceite #GETThis Is Going To Be Hard pt.3#", x = 26, y = 44, zone = "Badlands" },
			[24] = { str = "Mate o elemental que e invocado, ele e level 45. Depois entregue de volta pra pegar seu Nifty Stopwatch" },
			[25] = { str = "Va ate #COORD[53,43]# e entregue #INScrounging#", x = 53, y = 43, zone = "Badlands" },
			[26] = { str = "Va ate #COORD[61,54]# e entregue #INTremors of the Earth# PULE a proxima parte", x = 61, y = 54, zone = "Badlands" },
			[27] = { str = "Agora voce deve ser level 41, se nao for va a leste no ravine e mate os whelps ate upar. Eu geralmente venho aqui e grindo por pelo menos 30 min sendo 41 ou nao e tento pegar o heart para #DOFiery Blaze Enchantment# Se nao achar em 30 min apenas abandone" },
			[28] = { str = "Use Hearthstone pra Thelsamar" },
			[29] = { str = "Entre na casa atras da Inn e entregue #INBadlands Reagent Run# aceite a parte de Uldaman" },
			[30] = { str = "Va ate #COORD[65,65]# entregue #INMurdaloc# aceite a parte de Uldaman. Estou quase 25% no 41 agora", x = 65, y = 65, zone = "Loch Modan" },
			[31] = { str = "Voe pra Duskwood, sete seu Hearthstone la. Voe pra SW Va ate #COORD[64,20]# e aceite #GETIn Search of The Temple#", x = 64, y = 20, zone = "Stormwind" },
			[32] = { str = "Voe de volta pra Duskwood, va ate Swamp of Sorrows" },
		}
	},

-----------41-41 Swamp of Sorrows
	--[402] = {
	[4141] = {
		title = "41-41 Swamp of Sorrows",
		--n = "41-41 Swamp of Sorrows",
		--pID = 401, nID = 403,
		--itemCount = 27,
		items = {
			[1] = { str = "41-41 Swamp of Sorrows" },
			[2] = { str = "Va ate Swamp of Sorrows, va ate #COORD[12,58]# e mate os whelps para #DODream Dust In the Swamp# drop rate baixo mas respawnam rapido", x = 12, y = 58, zone = "Swamp of Sorrows" },
			[3] = { str = "Va ate #COORD[26,59]# e aceite #GETEnroaching Wildlife# e va fazer. Mate os 3 tipos de mob ao redor dele e ao norte. Fica tudo perto do quest giver", x = 26, y = 59, zone = "Swamp of Sorrows" },
			[4] = { str = "Suba e encontre Noboru the Cudgel ele circula em #COORD[43,38]# e dropa um item que inicia #GETNoboru the Cudgel#", x = 43, y = 38, zone = "Swamp of Sorrows" },
			[5] = { str = "Volte pra #COORD[26,59]# e entregue #INEnroaching Wildlife# aceite #GETThe Lost Caravan#", x = 26, y = 59, zone = "Swamp of Sorrows" },
			[6] = { str = "Grinde ate #COORD[25,31]# e entregue #INNoboru the Cudgel# aceite #GETDraenethyst Crystals#", x = 25, y = 31, zone = "Swamp of Sorrows" },
			[7] = { str = "Suba ate o sanctuary que comeca em #COORD[54,29]# e comece coletando os #DODraenethyst Crystals#", x = 54, y = 29, zone = "Swamp of Sorrows" },
			[8] = { str = "Quando chegar no ultimo camp com o npc na gaiola em #COORD[65,18]# primeiro pegue o bau da carreta a esquerda para #DOThe Lost Caravan#", x = 65, y = 18, zone = "Swamp of Sorrows" },
			[9] = { str = "Certifique-se de limpar o camp ao lado do npc na gaiola." },
			[10] = { str = "Depois aceite #GETGalen's Escape# e muito facil se voce limpou o camp" },
			[11] = { str = "Grinde ate #COORD[48,39]# ate a tenda destruida e abra o bau pra completar #DOGalen's Escape#", x = 48, y = 39, zone = "Swamp of Sorrows" },
			[12] = { str = "Volte pra #COORD[26,31]# e entregue #INDraenethyst Crystals#", x = 26, y = 31, zone = "Swamp of Sorrows" },
			[13] = { str = "Va ate #COORD[26,59]# e entregue #INThe Lost Caravan# aceite #GETDriftwood#", x = 26, y = 59, zone = "Swamp of Sorrows" },
			[14] = { str = "Va pelo swamp e va pro sul ate Blasted Lands em #COORD[36,59]# e ate Nethergarde Keep em #COORD[54,78]#. Pegue o FP e voe pra Darkshire.", x = 54, y = 78, zone = "Blasted Lands" },
			[15] = { str = "Guarde seu gato e pegue o gato de Badlands de volta" },
			[16] = { str = "Aceite #GETSupplies for Nethergarde# no seu caminho de volta NE" },
			[17] = { str = "Voe de volta pra Nethergarde, entregue #INSupplies for Nethergarde# xp facil." },
			[18] = { str = "Volte pra Swamp of Sorrows." },
			[19] = { str = "Va ate o lago ao redor do Sunken Temple em #COORD[70,54]# e voce deve receber uma mensagem de completo para #DOIn Search of The Temple#", x = 70, y = 54, zone = "Swamp of Sorrows" },
			[20] = { str = "Va ate mais ou menos 76,6 e comece matando silt e monstrous crawlers e va descendo pro sul para #DO… and bugs# ate terminar. Tambem procure planks de madeira no chao para #DODriftwood#", x = 76, y = 6, zone = "Swamp of Sorrows" },
			[21] = { str = "Use Hearthstone pra Darkshire e pegue seu gato de volta." },
			[22] = { str = "Voe pra Nethergarde e volte pra Swamp" },
			[23] = { str = "Va ate #COORD[26,59]# e entregue #INDriftwood# aceite #GETDeliver the Shipment#", x = 26, y = 59, zone = "Swamp of Sorrows" },
			[24] = { str = "Desca pra Blasted Lands e entregue #INDeliver the Shipment# em #COORD[66,21]#", x = 66, y = 21, zone = "Blasted Lands" },
			[25] = { str = "Voe pra BB e entregue #INDream Dust In the Swamp# no topo da Inn e aceite #GETRumors for Kravel#" },
			[26] = { str = "Pegue o navio pra Rachet e voe pra Theramore e entregue #IN… and bugs# na Inn" },
			[27] = { str = "Voe pra Desolace" },
		}
	},

-----------41-42 Desolace
	--[403] = {
	[4142] = {
		title = "41-42 Desolace",
		--n = "41-42 Desolace",
		--pID = 402, nID = 404,
		--itemCount = 16,
		items = {
			[1] = { str = "41-42 Desolace" },
			[2] = { str = "Sete seu Hearthstone em Nijel's Point" },
			[3] = { str = "Aceite #GETDown the Scarlet Path#" },
			[4] = { str = "Desca e aceite #GETReagents For Reclaimers Inc pt.3#" },
			[5] = { str = "Va ate #COORD[47,61]# e aceite #GETGhost-O-Plasm Round Up#", x = 47, y = 61, zone = "Desolace" },
			[6] = { str = "Mate os demonios em #COORD[51,75]# para #DOReagents For Reclaimers Inc pt.3#", x = 51, y = 75, zone = "Desolace" },
			[7] = { str = "Mate undead ravagers em #COORD[61,90]# para #DODown the Scarlet Path# e #DOGhost-O-Plasm Round Up# entre os 2 esqueletos no meio", x = 61, y = 90, zone = "Desolace" },
			[8] = { str = "Voce deve bater level 42 quando terminar de matar esses" },
			[9] = { str = "Volte pra #COORD[47,61]# e entregue #INGhost-O-Plasm Round Up#", x = 47, y = 61, zone = "Desolace" },
			[10] = { str = "Use Hearthstone pra Nijel's Point" },
			[11] = { str = "Entregue #INDown the Scarlet Path# PULE a proxima parte" },
			[12] = { str = "Va logo ao sul da Inn, entregue #INReagents For Reclaimers Inc pt.3# aceite #GETReagents For Reclaimers Inc pt.4#" },
			[13] = { str = "Voe pra Theramore, navegue pra Menethil e voe pra IF" },
			[14] = { str = "Entregue #INReagents For Reclaimers Inc pt.4# em #COORD[67,17]#", x = 67, y = 17, zone = "Ironforge" },
			[15] = { str = "Pegue novas skills" },
			[16] = { str = "Voe pra Booty Bay" },
		}
	},
-----------42-43 Stranglethron Vale
	--[404] = {
	[4243] = {
		title = "42-43 Stranglethron Vale",
		--n = "42-43 Stranglethron Vale",
		--pID = 403, nID = 405,
		--itemCount = 29,
		items = {
			[1] = { str = "42-43 Stranglethron Vale" },
			[2] = { str = "Entre na Inn, aceite #GETTran'Rek#" },
			[3] = { str = "Sete seu Hearthstone em BB" },
			[4] = { str = "Aceite #GETZanzil's Secret# e #GETWhiskey Slim's Lost Grog#" },
			[5] = { str = "Va perto do Banco, aceite #GETAkiris By the Bundle pt.1#" },
			[6] = { str = "Entre na casa ao lado do meio navio, aceite #GETStoley's Debt#" },
			[7] = { str = "Onde o dock se divide pra cima e pra baixo, va pra cima e vire a esquina, aceite #GETKeep An Eye Out#" },
			[8] = { str = "Saia de BB e va pra direita e pro sul. Tudo em #COORD[31,79]# Voce vai matar os buccaneers para #DOUp To Snuff# e #DOKeep An Eye Out#", x = 31, y = 79, zone = "Stranglethorn Vale" },
			[9] = { str = "Mate os swashbucklers nos dois camps em #COORD[29,81]#(bloodsail charts ficam aqui na caixa) e #COORD[27,82]# (bloodsail orders, na caixa, tenda NE) para #DOThe Bloodsail Buccaneers pt.4#", x = 27, y = 82, zone = "Stranglethorn Vale" },
			[10] = { str = "Volte pra BB, e vire a esquerda" },
			[11] = { str = "Entregue #INKeep An Eye Out# perto da forja" },
			[12] = { str = "Suba na Inn, entregue #INUp To Snuff#" },
			[13] = { str = "Va logo la fora e entregue #INThe Bloodsail Buccaneers pt.4# aceite #GETThe Bloodsail Buccaneers pt.5#" },
			[14] = { str = "Mate naga em #COORD[25,63]# para #DOAkiris By the Bundle pt.1#", x = 25, y = 63, zone = "Stranglethorn Vale" },
			[15] = { str = "Grinde nos nagas ate estar pelo menos 50% no level 43" },
			[16] = { str = "Suba ate as Ruins of Aboraz e mate #NPCChucky# (#COORD[40,58]#) para #DOVoodoo Dues# enquanto mata os mobs para #DOZanzil's Secret# voce so precisa de 8-10", x = 40, y = 58, zone = "Stranglethorn Vale" },
			[17] = { str = "Suba ate as Ruins of Jubawal e mate #NPCJon-Jon# (#COORD[34,51]#) e #NPCMaury# (#COORD[35,51]#) para #DOVoodoo Dues# e o resto de #DOZanzil's Secret#", x = 35, y = 51, zone = "Stranglethorn Vale" },
			[18] = { str = "Mate #NPCTethis# para #DORaptor Mastery pt.4# atras da arena em #COORD[31,43]# depois entregue no nessingways em #COORD[35,10]# aceite #GETBig Game Hunter#", x = 31, y = 43, zone = "Stranglethorn Vale" },
			[19] = { str = "Va ate o rebel camp em 38,3 e aceite #GETColonel Kurzen#", x = 38, y = 3, zone = "Stranglethorn Vale" },
			[20] = { str = "Va ate a caverna em 45,8 va ate a bifurcacao e desca como antes mate os elites e subchiefs (quando eles ficarem com aura vermelha pare seu pet de bater neles ou ele vai morrer) para #DOColonel Kurzen# Kurzen fica em 49,3 ", x = 49, y = 3, zone = "Stranglethorn Vale" },
			[21] = { str = "Morra de proposito pra aparecer perto do rebel camp" },
			[22] = { str = "Va ate o rebel camp em 38,3 e entregue #INColonel Kurzen#", x = 38, y = 3, zone = "Stranglethorn Vale" },
			[23] = { str = "Mate os trolls em #COORD[44,34]# ate estar a mais ou menos 9k xp de upar", x = 44, y = 34, zone = "Stranglethorn Vale" },
			[24] = { str = "Use Hearthstone pra BB" },
			[25] = { str = "Entregue #INZanzil's Secret#" },
			[26] = { str = "Va ate o Banco, entregue #INAkiris By the Bundle pt.1# aceite #GETAkiris By the Bundle pt.2#" },
			[27] = { str = "Va ate a casa em frente ao meio barco, entregue #INVoodoo Dues# aceite #GETCracking Maury's Foot#" },
			[28] = { str = "Pegue o barco pra Rachet depois voe pra Theramore" },
			[29] = { str = "Entregue #INAkiris By the Bundle pt.2# na sua frente, voe pra Gadgetzan" },
		}
	},

-----------43-43 Tanaris
	--[405] = {
	[4343] = {
		title = "43-43 Tanaris",
		--n = "43-43 Tanaris",
		--pID = 404, nID = 406,
		--itemCount = 34,
		items = {
			[1] = { str = "43-43 Tanaris" },
			[2] = { str = "Aceite #GETWastewander Justice# e #GETWater Pouch Bounty#" },
			[3] = { str = "Sete seu Hearthstone em Gadgetzan" },
			[4] = { str = "Va em frente da gaiola e pegue as 2 quests na placa #GETWANTED: Caliph Scorpidsting# e #GETWANTED: Andre Firebeard#" },
			[5] = { str = "Entregue #INTran'Rek# PULE a proxima parte" },
			[6] = { str = "No lado esquerdo da cidade na colina aceite #GETGadgetzan Water Survey#" },
			[7] = { str = "Va ate Shimmering Flats em #COORD[77,77]# e entregue #INRumors for Kravel# aceite #GETBack to Booty Bay#", x = 77, y = 77, zone = "Thousand Needles" },
			[8] = { str = "Logo ao lado dele entregue #INNews for Fizzle#" },
			[9] = { str = "Va ate #COORD[80,75]# e aceite #GETKeeping Pace# faca falando com zamek logo ao sul daqui, tem um ? azul na cabeca. Nao siga ele, va ate a casa do rizzle em #COORD[77,77]# e quando ele sair pegue os planos desprotegidos que entregam #INKeeping Pace# aceite #GETRizzle's Schematics# entregue em #COORD[80,75]#", x = 80, y = 75, zone = "Thousand Needles" },
			[10] = { str = "Use Hearthstone pra Gadgetzan" },
			[11] = { str = "Va ate Steamwheedle Port em #COORD[59,80]#", x = 59, y = 80, zone = "Tanaris" },
			[12] = { str = "Entregue #INStoley's Debt# na casa mais ao sul, aceite #GETStoley's Shipment# e #GETSouthsea Shakedown#" },
			[13] = { str = "Va ate as casas do norte, aceite #GETPirate Hats Ahoy!# e #GETScreecher Spirits#" },
			[14] = { str = "Va ate #COORD[63,30]# e mate os mobs aqui para #DOWastewander Justice# e #DOWater Pouch Bounty# Procure #NPCCaliph Scorpidsting# e mate ele para #GETWANTED: Caliph Scorpidsting# enquanto estiver aqui. Ele tem 2 guardas em stealth mas e relativamente facil. Ele patrulha pra cima e pra baixo", x = 63, y = 30, zone = "Tanaris" },
			[15] = { str = "Va ate a caverna em #COORD[68,41]# e passe pra Lost Rigger Cove.", x = 68, y = 41, zone = "Tanaris" },
			[16] = { str = "Comece matando os mobs aqui atras para #DOSouthsea Shakedown# e #DOPirate Hats Ahoy!#" },
			[17] = { str = "Voce pode dropar Pirate's Footlocker que pode conter #NPCShip Schedule# e os fragmentos de mapa upper middle e lower que iniciam #GETCuergo's Gold# e #GETShip Schedules# so faca se encontrar. Se eu nao achar todos eu pulo ou vendo o que tenho." },
			[18] = { str = "Mate #NPCAndre Firebeard# em #COORD[73,47]# para #GETWANTED: Andre Firebeard#", x = 73, y = 47, zone = "Tanaris" },
			[19] = { str = "Va ate a unica casa de 2 andares aqui em #COORD[72,46]# e pegue o vinho roubado para #DOStoley's Shipment#. Fica no 2o andar", x = 72, y = 46, zone = "Tanaris" },
			[20] = { str = "Use Hearthstone pra Gadgetzan" },
			[21] = { str = "Entregue #INWastewander Justice# aceite #GETMore Wastewander Justice#" },
			[22] = { str = "Entregue #INWANTED: Caliph Scorpidsting# e #INWater Pouch Bounty#" },
			[23] = { str = "Voce deve estar perto da metade do TNL" },
			[24] = { str = "Va a oeste ate #COORD[39,29]# e faca #DOGadgetzan Water Survey# Corra quando pegar a amostra, um 47 e um 48 vao te atacar.", x = 32, y = 29, zone = "Tanaris" },
			[25] = { str = "Volte pra Gadgetzan e entregue #INGadgetzan Water Survey# aceite #GETNoxious Lair Investigation#" },
			[26] = { str = "Faca #DOMore Wastewander Justice# em #COORD[60,35]# matando os mobs", x = 60, y = 35, zone = "Tanaris" },
			[27] = { str = "Volte ate Steamwheedle Port em #COORD[59,80]# na casa do sul e entregue #INStoley's Shipment# aceite #GETDeliver to MacKinley#", x = 59, y = 80, zone = "Tanaris" },
			[28] = { str = "Entregue #INWANTED: Andre Firebeard# e #INSouthsea Shakedown#" },
			[29] = { str = "Va ate a casa do norte, entregue #INPirate Hats Ahoy!#" },
			[30] = { str = "Use Hearthstone pra Gadgetzan" },
			[31] = { str = "Entregue #INMore Wastewander Justice#" },
			[32] = { str = "Aceite #GETHandle With Care# perto do lado norte da cidade" },
			[33] = { str = "Voce deve estar mais ou menos a 3/4 do TNL agora" },
			[34] = { str = " Voe pra Feralas" },
		}
	},

-----------43-45 Feralas
	--[406] = {
	[4345] = {
		title = "43-45 Feralas",
		--n = "43-45 Feralas",
		--pID = 405, nID = 407,
		--itemCount = 43,
		items = {
			[1] = { str = "43-45 Feralas" },
			[2] = { str = "Do lado da agua da inn no gazebo, aceite #GETThe Mark of Quality#" },
			[3] = { str = "Sete seu Hearthstone em Feralas" },
			[4] = { str = "Entre no predio grande em frente a Inn, aceite #GETThe Missing Courier pt.1# e #GETThe Ruins of Solarsal#" },
			[5] = { str = "Va ate o predio logo a oeste aceite #GETIn Search of Knowledge# e #GETThe High Wilderness#" },
			[6] = { str = "Suba, entregue #INThe Missing Courier pt.1# aceite #GETThe Missing Courier pt.2#" },
			[7] = { str = "Va ate o gazebo em #COORD[26,52]# e entregue #INThe Ruins of Solarsal# aceite #GETReturn to Feathermoon Stronghold#", x = 26, y = 52, zone = "Feralas" },
			[8] = { str = "Volte pra Feathermoon no predio grande, entregue #INReturn to Feathermoon Stronghold# aceite #GETAgainst the Hatecrest pt.1# vire e entregue aceite #GETAgainst the Hatecrest pt.2#" },
			[9] = { str = "Mate naga em #COORD[26,54]# para #DOAgainst the Hatecrest pt.2#", x = 26, y = 54, zone = "Feralas" },
			[10] = { str = "Eu mato os naga ate estar a mais ou menos 2500 TNL porque geralmente estou abaixo de 15k TNL quando chego nessa parte. Eles dao em media 250 xp por kill" },
			[11] = { str = "Volte pra Feathermoon no predio grande, entregue #INAgainst the Hatecrest pt.2# aceite #GETAgainst Lord Shalzaru#" },
			[12] = { str = "Desca ate a caverna em #COORD[26,66]# e mate #NPCLord Shalzaru# no final para #DOAgainst Lord Shalzaru#", x = 26, y = 66, zone = "Feralas" },
			[13] = { str = "Morra pra aparecer em Feathermoon" },
			[14] = { str = "Volte pra Feathermoon no predio grande, entregue #INAgainst Lord Shalzaru# aceite #GETDelivering the Relic# va pro outro lado do predio e entregue." },
			[15] = { str = "Pegue o barco pro continente" },
			[16] = { str = "Va ao sul do dock e mate screechers para #DOScreecher Spirits#" },
			[17] = { str = "Desca ate #COORD[45,65]# e toque no barco destruido pra entregar #INThe Missing Courier pt.2# aceite #GETBoat Wreckage#", x = 45, y = 65, zone = "Feralas" },
			[18] = { str = "Use Hearthstone pra Feathermoon" },
			[19] = { str = "Entre no predinho em frente a Inn no 2o andar, entregue #INBoat Wreckage# aceite #GETThe Knife Revealed#" },
			[20] = { str = "Suba ate o topo da torre espiral grande, entregue #INThe Knife Revealed# aceite #GETPsychometric Reading#" },
			[21] = { str = "Entre no predinho em frente a Inn no 2o andar, entregue #INPsychometric Reading# aceite #GETThe Woodpaw Gnolls#" },
			[22] = { str = "Pegue o barco pro continente" },
			[23] = { str = "Entre na caverna de yetis em #COORD[56,56]# e mate yetis para #DOThe Mark of Quality# voce pode skinnar e tambem e um drop.", x = 56, y = 56, zone = "Feralas" },
			[24] = { str = "Se um #NPCOOX-22/FE Distress Beacon# cair aceite a quest #GETFind OOX-22/FE!# e entregue no fundo da caverna PULE a escolta. " },
			[25] = { str = "Grinde a leste e mate os Brutes em #COORD[60,56]#, e warlocks e shamans em #COORD[59,66]# para #DOThe High Wilderness# Eu mato qualquer um que vejo", x = 60, y = 56, zone = "Feralas" },
			[26] = { str = "Va ate #COORD[65,45]# e aceite #GETFreedom For All Creatures# E bem escondido, logo NW da entrada do camp tem um caminho que nem parece que da pra andar. Pra fazer isso simplesmente escolte ela ate a gaiola, abra e mate tudo ate dizer completo. ", x = 65, y = 45, zone = "Feralas" },
			[27] = { str = "Entregue de volta e aceite #GETDoling Justice pt.1# Os mobs podem ser encontrados nesse camp." },
			[28] = { str = "Entregue #INDoling Justice pt.1# em #COORD[65,45]# e aceite #GETDoling Justice pt.2#", x = 65, y = 45, zone = "Feralas" },
			[29] = { str = "Desca ate #COORD[73,56]# e toque nas Large Leather Backpacks na arvore grande. Entregue #INThe Woodpaw Gnolls# aceite #GETThe Writhing Deep#", x = 73, y = 56, zone = "Feralas" },
			[30] = { str = "Clique com botao direito na Backpack, aceite #GETThalanaar Delivery#" },
			[31] = { str = "Grinde ate a colmeia em #COORD[73,63]# e va ate la embaixo. Entre no tunel ao sul e fique a direita, voce vai ver um Zukk'Ash Pod la. Entregue #INThe Writhing Deep# aceite #GETFreed From the Hive#", x = 73, y = 63, zone = "Feralas" },
			[32] = { str = "Use Hearthstone pra Feathermoon" },
			[33] = { str = "Do lado da agua no gazebo, entregue #INThe Mark of Quality# aceite #GETImproved Quality#" },
			[34] = { str = "Entre na casa pequena em frente a Inn, entregue #INThe High Wilderness# depois suba e entregue #INFreed From the Hive# aceite #GETA Hero's Welcome#" },
			[35] = { str = "Va ate o predio grande ao lado e entregue #INA Hero's Welcome# aceite #GETRise of the Silithid#" },
			[36] = { str = "Voe ate Thalanaar (ponto entre 1k needles e aqui) entregue #INThalanaar Delivery# em #COORD[89,46]#", x = 89, y = 46, zone = "Feralas" },
			[37] = { str = "Voe pra Rut'theran Village (Darnassus)" },
			[38] = { str = "Siga o dock e entre na casa, entregue #INHandle With Care# aceite #GETFavored of Elune?#" },
			[39] = { str = "Suba, entregue #INIn Search of Knowledge# depois va ate o fundo da casa no 2o andar, abra o livro verde e aceite #GETFeralas: A History# entregue de volta pra ela, aceite #GETThe Borrower#" },
			[40] = { str = "Pegue novas skills" },
			[41] = { str = "Va ate o temple of the moon em #COORD[39,86]# e suba ate o 2o andar, entregue #INRise of the Silithid# e #INDoling Justice pt.2#", x = 39, y = 86, zone = "Feralas" },
			[42] = { str = "Compre 2 Elixir of Fortitude pra uma parte posterior dessa quest" },
			[43] = { str = "Use Hearthstone pra Feathermoon e voe pra Gadgetzan e entregue #INThe Borrower# aceite #GETThe Super Snapper FX#" },
		}
	},

-----------45-46 Uldaman
	--[407] = {
	[4546] = {
		title = "45-46 Uldaman",
		--n = "45-46 Uldaman",
		--pID = 406, nID = 408,
		--itemCount = 7,
		items = {
			[1] = { str = "45-46 Uldaman" },
			[2] = { str = "Agora voce pode grindar nos gnolls em Feralas perto de onde achou a mochila na arvore, ou pode fazer Uldaman. Eu recomendo muito fazer Uldaman. Voce pegou algumas quests antes, tem mais algumas em IF e nas badlands. Se conseguir um bom grupo voce pode facilmente fazer quase todas as quests la em menos de 3 horas max. Eu geralmente faco Uldaman completo por dentro e por fora, nao termino todas as quests a menos que precise upar. 1 run completa por dentro e por fora deve dar 75-100% desse level. Eu geralmente faco isso em umas 3 horas sem problema. Alem disso voce pode solar todos os mobs fora da instancia 3 por vez sem problema. O final de Uldaman, depois do boss, (quest dos mini disks) da umas 20k xp entre isso e falar com o npc fantasma que spawna la, alem de dar xp legal pra quests depois. E voce pode perder alguns spots de xp pra quests depois se pular." },
			[3] = { str = "Eu nao listo todas as quests de Uldaman porque tem um bom punhado e voce nao precisa fazer todas pra upar completamente, e de novo e opcional. Isso e muito mais rapido do que grindar seria. Eu realmente odeio fazer instancias quando buscando o melhor tempo mas alliance tem menos quests que horde e eu mencionei que vai ter uns 10-15% de grind no caminho pro 60. Se voce fizesse todas as instancias ia ficar muito lento. Isso nao vai atrasar com um bom grupo, de preferencia grupos de guild de 45+" },
			[4] = { str = "Voce pode parar em mais ou menos 75% do 46 mas de novo eu sugiro que voce upe. Nao e tao ruim quanto parece." },
			[5] = { str = "Um otimo mapa de Uldaman e onde as partes das quests podem ser feitas esta listado aqui no worldofwar.net" },
			[6] = { str = "Quando estiver pronto, voe pra SW e entregue #INIn Search of The Temple# em #COORD[64,20]# e aceite #GETIn Search of The Hinterlands# pegue novas skills depois voe pra Southshore.", x = 64, y = 20, zone = "Stormwind" },
			[7] = { str = " Va ate o caminho em #COORD[84,33]# atras de Durnholde Keep (voce vai ver 2 grifos) em direcao a The Hinterlands", x = 84, y = 33, zone = "Tarren Mill" },
		}
	},

-----------46-47 The Hinterlands
	--[408] = {
	[4647] = {
		title = "46-47 The Hinterlands",
		--n = "46-47 The Hinterlands",
		--pID = 407, nID = 409,
		--itemCount = 29,
		items = {
			[1] = { str = "46-47 The Hinterlands" },
			[2] = { str = "Va ate #COORD[11,46]# e entregue #INIn Search of The Hinterlands# aceite #INGryphon Master Talonaxe#", x = 11, y = 46, zone = "The Hinterlands" },
			[3] = { str = "Pegue o FP em #COORD[11,46]# la em cima depois entre na caverna e entregue #INGryphon Master Talonaxe#, aceite #GETRhapsody Shindigger# e #GETWitherbark Cages#", x = 11, y = 46, zone = "The Hinterlands" },
			[4] = { str = "Entre na Inn e vire a direita, aceite #GETSkulk Rock Clean-Up# e #GETTroll Necklace Bounty#" },
			[5] = { str = "Va la no fundo da Inn ate mais ou menos #COORD[13,41]# e sete seu Hearthstone em Aerie Peak.", x = 13, y = 41, zone = "The Hinterlands" },
			[6] = { str = "Grinde a leste ate #COORD[20,48]# pelo caminho ficando de olho em penas no chao para #DOFavored of Elune?# Voce nao precisa de todas ainda", x = 20, y = 48, zone = "The Hinterlands" },
			[7] = { str = "Siga o caminho ate #COORD[26,48]# e entregue #INRhapsody Shindigger# aceite #GETRhapsody's Kalimdor Kocktail#", x = 26, y = 48, zone = "The Hinterlands" },
			[8] = { str = "Volte e va ate o camp de trolls e limpe a maioria deles em #COORD[23,58]# e abra as 2 gaiolas para #DOWitherbark Cages#", x = 23, y = 58, zone = "The Hinterlands" },
			[9] = { str = "Grinde a leste ate #COORD[31,57]# e abra a 3a gaiola para #DOWitherbark Cages#", x = 31, y = 57, zone = "The Hinterlands" },
			[10] = { str = "Voce tambem deve ter 5 colares para #DOTroll Necklace Bounty# agora" },
			[11] = { str = "Va NE ate #COORD[46,42]#, coletando penas se ainda precisar no caminho, e mate os Green Sludges para #DOSkulk Rock Clean-Up pt.1#", x = 46, y = 62, zone = "The Hinterlands" },
			[12] = { str = "Va ate #COORD[49,37]# se encontrou OOX-09/HL Distress Beacon", x = 49, y = 37, zone = "The Hinterlands" },
			[13] = { str = "Va ate #COORD[56,41]# e mate Jade Oozes pra parte 2 de #DOSkulk Rock Clean-Up#", x = 56, y = 41, zone = "The Hinterlands" },
			[14] = { str = "Va ate a cachoeira em #COORD[81,46]# e pule na agua embaixo, depois va pro sul nessa praia ate ver Gammerita e tire uma foto dela para #DOThe Super Snapper FX# Tambem fique de olho em garrafas na praia para #DOWhiskey Slim's Lost Grog#", x = 81, y = 46, zone = "The Hinterlands" },
			[15] = { str = "Use Hearthstone pra Aerie Peak" },
			[16] = { str = "Va ate a frente da Inn e entregue #INSkulk Rock Clean-Up# e #INTroll Necklace Bounty# e quaisquer 5 colares extras que tiver." },
			[17] = { str = "Suba passando o FP na caverna em 9,44 e entregue #INWitherbark Cages# aceite #GETThe Altar of Zul#", x = 9, y = 44, zone = "The Hinterlands" },
			[18] = { str = "Va ate o topo do Altar of Zul em #COORD[48,68]# para #DOThe Altar of Zul#", x = 48, y = 68, zone = "The Hinterlands" },
			[19] = { str = "Agora eu grindo nos trolls e lobos ao redor de Zul ate estar a 1 barra do level 47. Voce deve estar pelo menos na metade do level 46 nesse ponto." },
			[20] = { str = "Pegue a quest #GETJammal'an the Prophet# em #COORD[33,75]# se planeja fazer Sunken Temple depois.", x = 33, y = 75, zone = "The Hinterlands" },
			[21] = { str = "Tenho certeza que quando voce estiver perto do level 47 vai encontrar OOX-09/HL Distress Beacon aceite #GETFind OOX-09/HL# e entregue em #COORD[49,37]# depois aceite #GETRescue OOX-09/HL# e escolte ate #COORD[78,61]# So tem 2 encontros de 3 mobs, mas cuidado com os lobos em stealth", x = 49, y = 37, zone = "The Hinterlands" },
			[22] = { str = "Quando estiver a mais ou menos 6k ou 1 barra do level 47 use Hearthstone pra Aerie Peak" },
			[23] = { str = "Entregue qualquer #INTroll Necklace Bounty# que tiver antes de sair" },
			[24] = { str = "Suba passando o FP ate 9,44 e entregue #INThe Altar of Zul# aceite #GETThadius Grimshade#", x = 9, y = 44, zone = "The Hinterlands" },
			[25] = { str = "Voe pra Menethil Harbor e pegue o barco pra Auberdine, depois voe pra Rut'theran Village" },
			[26] = { str = "Va ate a casa em #COORD[55,92]# e entregue #INFavored of Elune?#", x = 55, y = 92, zone = "The Hinterlands" },
			[27] = { str = "Suba, entregue #INThe Super Snapper FX# aceite #GETReturn to Troyas#" },
			[28] = { str = "Voce deve ser level 47 agora e mais ou menos 8k dentro dele." },
			[29] = { str = "Voe pra Feralas" },
		}
	},

-----------47-47 Feralas
	--[409] = {
	[4747] = {
		title = "47-47 Feralas",
		--n = "47-47 Feralas",
		--pID = 408, nID = 410,
		--itemCount = 22,
		items = {
			[1] = { str = "47-47 Feralas" },
			[2] = { str = "Sete seu Hearthstone em Feathermoon Stronghold" },
			[3] = { str = "Va em frente a Inn na casa de 2 andares, entregue #INReturn to Troyas# aceite #GETThe Stave of Equinex#" },
			[4] = { str = "Aceite #GETThe Sunken Temple# ao lado dele" },
			[5] = { str = "Nade ou navegue a leste ate o dock." },
			[6] = { str = "Ao lado do dock em #COORD[44,33]# aceite #GETZapped Giants# e #GETFuel for Zapping#", x = 44, y = 33, zone = "Feralas" },
			[7] = { str = "Coloque o Zorbin's Ultra-Shrinker na hotkey. Depois va pro sul pela praia e comece zapando gigantes e matando pra #DOZapped Giants# e mate elementais de agua para #DOFuel for Zapping#" },
			[8] = { str = "Volte pra #COORD[44,33]# e entregue #INZapped Giants# e #INFuel for Zapping# Voce pode fazer de novo agora, mas eu nao faria, por uns 500 xp por entrega. Agora ele abre a loja pra voce.", x = 44, y = 33, zone = "Feralas" },
			[9] = { str = "Va ate o camp grimtotem em #COORD[65,45]# e aceite #GETAn Orphan Looking For A Home#", x = 65, y = 45, zone = "Feralas" },
			[10] = { str = "Desca ate a caverna de yetis em #COORD[56,56]# e faca a escolta do robot chicken se puder, nao tenha medo de pedir ajuda se precisar.", x = 56, y = 56, zone = "Feralas" },
			[11] = { str = "Grinde ate a caverna de yetis em #COORD[51,31]# em Ironfur Bears e Groddoc Gorillas ate pegar 3 figados de cada para #DORhapsody's Kalimdor Kocktail#", x = 51, y = 31, zone = "Feralas" },
			[12] = { str = "Mate os Rage Scar Yeti's aqui para #DOImproved Quality# lembre que voce pode skinnar pra pegar tambem. Se um Pristine Yeti Hide dropar, aceite a quest que ele da #GETPristine Yeti Hide#" },
			[13] = { str = "Va ate Rockbiter em #COORD[42,22]# e aceite #GETThe Giant Guardian#", x = 42, y = 22, zone = "Feralas" },
			[14] = { str = "Faca #DOThe Stave of Equinex# fazendo o seguinte. Pegue o Blytan Essence da fogueira em #COORD[38,15]# #DOThe Stave of Equinex# Pegue o Samha Essence da fogueira em #COORD[40,12]# (no topo do arco em ruinas) pra chegar la, de a volta por tras e pule pelas pedras quebradas (nao e facil de notar) Volte por tras e pegue o Imbel Essence da fogueira em 39,9. Pegue o Lahassa Essence da fogueira em #COORD[37,12]# embaixo do gazebo marrom. Desca ate o Equinex Monolith logo ali no penhasco. Use o Troya's Staff perto dele. Toque no Monolith e entregue #INThe Stave of Equinex# aceite #GETThe Morrow Stone#", x = 38, y = 15, zone = "Feralas" },
			[15] = { str = "Volte pra perto da chama anterior em #COORD[38,10]# e entregue #INThe Giant Guardian# aceite a escolta #GETWandering Shay#", x = 38, y = 10, zone = "Feralas" },
			[16] = { str = "Pegue o sino do bau e coloque na hotkey. Isso e parecido com a quest de druid em Darkshore. Leve ela de volta pro Rockbiter em #COORD[42,21]# e entregue #INWandering Shay# (o truque e ficar na frente dela, se ela estiver do seu lado ela vai desviar muito mais e o sino tem timer de 1 minuto.", x = 42, y = 21, zone = "Feralas" },
			[17] = { str = "Use Hearthstone pra Feathermoon Stronghold" },
			[18] = { str = "Va ate o gazebo perto da agua ao lado do hippogryph master, entregue #INPristine Yeti Hide# e #INImproved Quality#" },
			[19] = { str = "Tire seus 2 Elixirs of Fortitude do correio se ainda nao tiver com voce." },
			[20] = { str = "Va em frente na casa de 2 andares, entregue #INThe Morrow Stone#" },
			[21] = { str = "Voce deve estar perto de 70% no 47" },
			[22] = { str = "Voe pra Gadgetzan" },
		}
	},

-----------47-48 Tanaris
	--[410] = {
	[4748] = {
		title = "47-48 Tanaris",
		--n = "47-48 Tanaris",
		--pID = 409, nID = 411,
		--itemCount = 42,
		items = {
			[1] = { str = "47-48 Tanaris" },
			[2] = { str = "Logo dentro de Gadgetzan a direita, aceite #GETThe Thirsty Goblin#" },
			[3] = { str = "Sete seu Hearthstone em Gadgetzan" },
			[4] = { str = "Va atras da Inn, aceite #GETThe Dunemaul Compound#" },
			[5] = { str = "Perto da entrada norte, aceite #GETThistleshrub Valley#" },
			[6] = { str = "Va pro sul ate o esqueleto no chao em #COORD[49,36]# e #COORD[44,39]# e #COORD[47,45]# mate Rocs para #DORhapsody's Kalimdor Kocktail# Se estiver lotado faca depois.", x = 49, y = 36, zone = "Tanaris" },
			[7] = { str = "Va ate #COORD[52,45]# entregue #INThe Sunken Temple# e aceite #GETThe Stone Circle# e #GETGahz'Ridian#", x = 52, y = 45, zone = "Tanaris" },
			[8] = { str = "Agora coloque o Gahz'Ridian Detector Helm e pontos amarelos no minimapa vao mostrar as pecas que voce precisa pra #DOGahz'Ridian#. Fica a seu criterio usar isso em lutas. Tem por todo lado" },
			[9] = { str = "Va a oeste ate o Dunemaul Compound limpe o caminho ate #COORD[40,58]# e mate Gor'Marok the Ravager para #DOThe Dunemaul Compound# Voce nao precisa dos 20 kills de ogro todos daqui", x = 40, y = 58, zone = "Tanaris" },
			[10] = { str = "Va ate #COORD[47,65]# e termine de matar os ogros pra The Dunemaul Compound enquanto pega o resto dos artefatos pra Gahz'Ridian", x = 47, y = 65, zone = "Tanaris" },
			[11] = { str = "Grinde nos ogros ate estar a #COORD[10,00]#0 do level 48" },
			[12] = { str = "Suba pelo lado esquerdo de Uldum e va ate o pedestal em #COORD[37,81]# e entregue #INSeeing What Happens#", x = 37, y = 81, zone = "Tanaris" },
			[13] = { str = "Fale com o cara que aparece, aceite #GETThe Stone Watcher# e fale com ele ate completar. Depois toque no pedestal pra entregar de volta" },
			[14] = { str = "Toque no pedestal mais uma vez e aceite #GETReturn to Ironforge#" },
			[15] = { str = "Va a oeste ate #COORD[29,66]# e mate Gnarled Thistlegrub e Thistlegrub Rootshapers para #DOThistleshrub Valley# e os dew collectors para #DOThe Thirsty Goblin# Voce deve bater level 48 aqui", x = 29, y = 66, zone = "Tanaris" },
			[16] = { str = "Se encontrar Tooga, aceite #GETTooga's Quest# Eu achei ele em #COORD[29,73]# perto do zepelim, mas voce pode achar em qualquer lugar nesse vale. Ele te segue, voce nao precisa seguir ele ", x = 29, y = 73, zone = "Tanaris" },
			[17] = { str = "Va ate o Noxious Lair em #COORD[34,46]# e mate Centipaar la para #DONoxious Lair Investigation# Se nao conseguir todos antes do tooga ter 10 minutos restantes, va entregar e depois volte.", x = 34, y = 76, zone = "Tanaris" },
			[18] = { str = "Entregue #INTooga's Quest# perto de steamwheedle port em #COORD[66,25]#", x = 66, y = 25, zone = "Tanaris" },
			[19] = { str = "Aceite #GETYuka Screwspigot#" },
			[20] = { str = "Entregue #INScreecher Spirits# em #COORD[66,22]# PULE a parte de ZF", x = 66, y = 22, zone = "Tanaris" },
			[21] = { str = "Use Hearthstone pra Gadgetzan" },
			[22] = { str = "Va perto da entrada e aceite #GETThe Thirsty Goblin# de volta e entregue aceite #GETIn Good Taste#" },
			[23] = { str = "Va atras da Inn perto da fogueira, entregue #INThe Dunemaul Compound#" },
			[24] = { str = "Va perto da entrada norte, entregue #INThistleshrub Valley#" },
			[25] = { str = "Va a oeste ate Sprinkle, entregue #INIn Good Taste# aceite #GETSprinkle's Secret Ingredient#" },
			[26] = { str = "No predio atras dela, entregue #INNoxious Lair Investigation#" },
			[27] = { str = "Va na colina atras do predio, aceite #GETThe Schrimshank Redemption#" },
			[28] = { str = "Desca ate #COORD[52,45]# e entregue #INGahz'Ridian#", x = 52, y = 45, zone = "Tanaris" },
			[29] = { str = "Desca ate a entrada em #COORD[55,70]# pegue a espiral descendo ate a entrada que fica ao norte. primeira bifurcacao va pra direita. depois da sala circular na proxima bifurcacao va pra direita. Voce vai entrar numa sala quadrada grande. Va pra direita ate #COORD[55,71]# e pegue o survey gear para #DOThe Schrimshank Redemption#", x = 55, y = 70, zone = "Tanaris" },
			[30] = { str = "Morra de proposito pra aparecer em Gadgetzan" },
			[31] = { str = "Va ate a colina no lado oeste da cidade, entregue #INThe Schrimshank Redemption# aceite #GETInsect Part Analysis pt.1#" },
			[32] = { str = "Va ate a casa no lado NW da cidade, entregue #INInsect Part Analysis pt.1# aceite #GETInsect Part Analysis pt.2#" },
			[33] = { str = "Volte pra colina, entregue #INInsect Part Analysis pt.2# aceite #GETRise of the Silithid#" },
			[34] = { str = "Va ate Shimmering Flats em #COORD[78,74]# e entregue #INAn Orphan Looking For A Home# aceite #GETA Short Incubation# e como voce ja tem isso, entregue de volta e aceite #GETThe Newest Member of the Family# agora voce tem 1 hora.", x = 78, y = 74, zone = "Thousand Needles" },
			[35] = { str = "Voe pra Theramore e pegue qualquer mageweave que tiver e suba first aid o maximo que puder." },
			[36] = { str = "Navegue pra Menethil e voe pra IF" },
			[37] = { str = "Sete seu Hearthstone em IF e pegue novas skills" },
			[38] = { str = "Va ate #COORD[77,11]# e entregue #INReturn to Ironforge# aceite #GETA Future Task# e #GETPassing the Burden#", x = 77, y = 11, zone = "Ironforge" },
			[39] = { str = "Vire em #COORD[70,18]# e entregue #INA Future Task#", x = 70, y = 18, zone = "Ironforge" },
			[40] = { str = "Va ate 31,4 e entregue #INPassing the Burden# aceite #GETArcane Runes# e #GETAn Easy Pickup#", x = 31, y = 4, zone = "Ironforge" },
			[41] = { str = "Va ate #COORD[70,93]#, entregue #INAn Easy Pickup# aceite #GETSignal For Pickup# depois entregue de volta. Agora voce tem o flare gun pra sinalizar depois.", x = 70, y = 93, zone = "Ironforge" },
			[42] = { str = "Voe pra Hinterlands" },
		}
	},

-----------48-48 The Hinterlands
	--[411] = {
	[4848] = {
		title = "48-48 The Hinterlands",
		--n = "48-48 The Hinterlands",
		--pID = 410, nID = 412,
		--itemCount = 8,
		items = {
			[1] = { str = "48-48 The Hinterlands" },
			[2] = { str = "Va na base la embaixo ate #COORD[14,43]# e entregue #INThe Newest Member of the Family# aceite #GETFood For Baby#", x = 14, y = 43, zone = "The Hinterlands" },
			[3] = { str = "Va ate #COORD[26,48]# e entregue #INRhapsody's Kalimdor Kocktail# Aceite #GETRhapsody's Tale#", x = 26, y = 48, zone = "The Hinterlands" },
			[4] = { str = "Grinde ate o lago em #COORD[40,59]# e pegue Violet Tragan (cogumelo) do fundo do lago para #DOSprinkle's Secret Ingredient#", x = 40, y = 59, zone = "The Hinterlands" },
			[5] = { str = "Grinde ate leste de #COORD[57,47]# e mate Silvermane Stalkers para #DOFood For Baby#", x = 57, y = 47, zone = "The Hinterlands" },
			[6] = { str = "Volte pra Aerie Peak e va ate o andar de baixo da Inn" },
			[7] = { str = "Entregue #INFood For Baby# aceite #GETBecoming A Parent# depois entregue de volta. Pet fofo e xp bom =)" },
			[8] = { str = "Use Hearthstone pra IF e voe pra BB" },
		}
	},

-----------48-49 Stranglethorn Vale
	--[412] = {
	[4849] = {
		title = "48-49 Stranglethorn Vale",
		--n = "48-49 Stranglethorn Vale",
		--pID = 411, nID = 413,
		--itemCount = 27,
		items = {
			[1] = { str = "48-49 Stranglethorn Vale" },
			[2] = { str = "Desca ate o primeiro andar da Inn, sete seu Hearthstone aqui" },
			[3] = { str = "Entregue #INBack To Booty Bay# e #INWhiskey Slim's Lost Grog#" },
			[4] = { str = "Entre na casa ao lado do meio navio de cabeca pra baixo, entregue #INDeliver to MacKinley#" },
			[5] = { str = "Embaixo daquele barco la fora, aceite #GETStranglethorn Fever#" },
			[6] = { str = "Suba a rampa e na primeira casa depois da ponte, entregue todas as escoltas do robot chicken que voce fez. Eu nao peguei a de Tanaris enquanto escrevia esse guia entao perdi a quest pra ganhar 7100 xp extra" },
			[7] = { str = "Perto do barco, aceite #GETThe Captain's Chest#" },
			[8] = { str = "Mate gorilas em #COORD[34,63]# para #DOStranglethorn Fever# depois suba na caverna em #COORD[35,60]# entregue. O cara na caverna pede 10 gorilla fangs, depois ele invoca 3 ondas de gorilas. Mokk esta na 3a onda. Sao todos level 42-44 comeca com 3, depois 5, depois acho que 6 ou 7. Pode ficar dificil. Mate o Mokk primeiro pra caso voce morrer.", x = 35, y = 60, zone = "Stranglethorn Vale" },
			[9] = { str = "Va ate #COORD[38,34]# e mate #NPCKing Bangalash# para #DOBig Game Hunter# ele spawna minions level 33. Voce pode matar ele antes de alguns sairem.", x = 38, y = 34, zone = "Stranglethorn Vale" },
			[10] = { str = "Va ate #COORD[48,25]# e mate os ogros elite aqui ate a Maury's Key dropar para #DOCracking Maury's Foot# Se nao achar depois de uma hora apenas abandone a quest. Tem drop rate baixo. Eu grindo ate estar a 2 barras do level 49 se nao pegar a chave. Geralmente e mais ou menos uma hora.", x = 48, y = 25, zone = "Stranglethorn Vale" },
			[11] = { str = "Va ate Nessingways em #COORD[35,10]# e entregue #INBig Game Hunter#", x = 35, y = 10, zone = "Stranglethorn Vale" },
			[12] = { str = "Use Hearthstone pra Booty Bay, va ate o meio barco logo fora da Inn" },
			[13] = { str = "Entregue #INStranglethorn Fever#" },
			[14] = { str = "Va ate a praia logo a leste de BB e abra garrafas azuis ate pegar Carefully Folded Note que inicia #GETMessage in A Bottle pt.1#" },
			[15] = { str = "Va ate #COORD[36,69]# e mate #NPCGorlash# para #DOThe Captain's Chest# Ele e um elite 47, pode ser dificil mas eu consegui. Use tudo que tiver", x = 36, y = 69, zone = "Stranglethorn Vale" },
			[16] = { str = " Va ate #COORD[38,80]# e entregue #INMessage in A Bottle pt.1# PULE a proxima parte, a menos que consiga um grupo pra matar o macaco 51", x = 38, y = 80, zone = "Stranglethorn Vale" },
			[17] = { str = "Desca ate os navios piratas, 1 fica em #COORD[33,87]# e os outros 2 em #COORD[30,88]# Voce quer ir no 2o andar perto da frente do navio e matar o capitao de cada pra #DOThe Bloodsail Buccaneers pt.5#", x = 33, y = 87, zone = "Stranglethorn Vale" },
			[18] = { str = "Procure um scroll em um dos navios chamado Cortello's Riddle que inicia #GETCortello's Riddle pt.1#" },
			[19] = { str = "Se o hearthstone estiver pronto, use, senao morra pra aparecer em BB" },
			[20] = { str = "Va perto do barco, entregue #INThe Captain's Chest#" },
			[21] = { str = "Suba na Inn, entregue #INThe Bloodsail Buccaneers pt.5#" },
			[22] = { str = "Voe pra SW e va ate #COORD[64,20]# entregue #INRhapsody's Tale# PULE o resto", x = 64, y = 20, zone = "Stormwind" },
			[23] = { str = "Daqui pra frente, confira a AH quando passar por uma, ou use seu char de AH pra procurar suas Beaststalker Bracers. Eu peguei as minhas por 8g tambem procure um mithril casing pra depois em Un'Goro" },
			[24] = { str = "Voe pra Duskwood" },
			[25] = { str = "Va a leste por Deadwind Pass ate Swamp of Sorrows" },
			[26] = { str = "Siga a estrada ate ela se dividir e a bifurcacao da esquerda tem uma ponte em #COORD[22,48]# e embaixo dela tem A Soggy Scroll que entrega #INCortello's Riddle pt.1# aceite #GETCortello's Riddle pt.2#", x = 22, y = 48, zone = "Swamp of Sorrow" },
			[27] = { str = "Desca ate Blasted Lands" },
		}
	},

--------49-50 Blasted Lands
	--[413] = {
	[4950] = {
		title = "49-50 Blasted Lands",
		--n = "49-50 Blasted Lands",
		--pID = 412, nID = 501,
		--itemCount = 30,
		items = {
			[1] = { str = "49-50 Blasted Lands" },
			[2] = { str = "Nao precisa ter pressa nessa zona, entao grinde em qualquer coisa que ver." },
			[3] = { str = "Pare em #COORD[50,14]# e aceite as 5 quests seguintes: #GETThe Basilisk's Bite# #GETVulture's Vigor# #GETSnickerfang Jowls# #GETA Boar's Vitality# e #GETThe Decisive Striker#", x = 50, y = 14, zone = "Blasted Lands" },
			[4] = { str = "Voce vai precisar da seguinte quantidade de itens pra completar todas as 5 quests. Snickerfang Jowls:5, Blasted Boar Lungs:6, Scorpok Pincers:6, Basilisk Brain:11, Vulture Gizzards:14 Vai ser como grindar pegar tudo isso entao voce esta matando 2 coelhos com 1 cajadada. Voce provavelmente vai ganhar meio level antes de entregar." },
			[5] = { str = "So circule o centro do mapa e voce vai achar tudo que precisa matar. Eu marcaria com coords mas seriam muitas. Voce pode querer evitar qualquer coisa level 53+ que fica mais pro sul. Voce deve fazer um bom dinheiro com skinning aqui." },
			[6] = { str = "Voce deve estar perto de 3 barras e meia no level 49 agora" },
			[7] = { str = "Grinde ate #COORD[51,35]# e aceite #GETEverything Counts In Large Amounts# Se voce achar um desses, entregue quando passar por ela, voce com certeza vai achar pelo menos um enquanto estiver aqui. Nem se preocupe com a outra quest voce nunca vai achar. Eu jogo WoW desde o lancamento e nunca achei. ", x = 51, y = 35, zone = "Blasted Lands" },
			[8] = { str = "Va ate #COORD[50,14]# e entregue as 5 quests, #INThe Basilisk's Bite# #INVulture's Vigor# #INSnickerfang Jowls# #INA Boar's Vitality# e #INThe Decisive Striker# mas entregue a que voce mais quer por ultimo, porque voce recebe um buff e um item tambem. Cada uma da 4700 xp", x = 50, y = 14, zone = "Blasted Lands" },
			[9] = { str = "Va ate Nethergarde Keep no topo da torre alta em #COORD[66,19]# e entregue #INThadius Grimshade# PULE a proxima parte.", x = 66, y = 19, zone = "Blasted Lands" },
			[10] = { str = "Voce deve estar perto de 70% no level 49 agora. Se nao quiser fazer ZF pra bater 50, grinde aqui ate estar a mais ou menos 13k do level 50. Se quiser fazer ZF va pro proximo passo." },
			[11] = { str = "Use Hearthstone pra Booty Bay" },
			[12] = { str = "Aceite #GETZanzil's Mixture# e #GETA Fool's Stout#" },
			[13] = { str = "Pegue o barco pra Ratchet" },
			[14] = { str = "Aceite #GETVolcanic Activity# na primeira cabana saindo do dock" },
			[15] = { str = "Logo fora dessa cabana tem um bau verde, abra pra #DOThe Stone Circle#" },
			[16] = { str = "Voe pra Tanaris" },
			[17] = { str = "Va perto da entrada NW, entregue #INSprinkle's Secret Ingredient# aceite #GETDelivery For Marin#" },
			[18] = { str = "Volte pra perto da entrada Sul e entregue #INDelivery For Marin# aceite #GETNoggenfogger Elixir# depois entregue de volta. Voce vai receber 5 elixirs e poder comprar mais." },
			[19] = { str = "Va ate Shimmering Flats em #COORD[77,77]# e entregue #INZanzil's Mixture# e #INA Fool's Stout# aceite #GETGet the Goblins Drunk# va ate #COORD[79,76]# e entregue.", x = 77, y = 77, zone = "Thousand Needles" },
			[20] = { str = "Volte pra #COORD[77,77]# e aceite #GETReport Back to Fizzlebub#", x = 77, y = 77, zone = "Thousand Needles" },
			[21] = { str = "Va ate #COORD[52,45]# e entregue #INThe Stone Circle PULE o resto a menos que planeje fazer Sunken Temple.", x = 52, y = 45, zone = "Thousand Needles" },
			[22] = { str = "Voce deve estar a mais ou menos 30k do level 50 agora, como eu disse acima, va fazer ZF ou voce deveria ter grindado em Blasted Lands." },
			[23] = { str = "Se voce fizer ZF voce so precisa completar pelo menos 2-3 das seguintes quests #DOTroll Temper# #DODivino-matic Rod# #DOGahz'rilla# #DOThe Prophecy of Mosh'Aru# Eu recomendo muito pegar #GETDivino-matic Rod# e #GETGahz'rilla# porque voce ganha um anel otimo e uma trinket de aumento de velocidade de montaria." },
			[24] = { str = "Agora voce deve estar a mais ou menos 1-2 barras no level 50 se foi no ZF. Daqui pra frente tem muito mais conteudo fresco, como voce viu 45-50 e um saco. Ainda temos muitas areas intocadas pra upar agora." },
			[25] = { str = "Use Hearthstone pra BB e entregue #INReport Back to Fizzlebub#" },
			[26] = { str = "Voe pra IF pra pegar novas skills e aceite a quest #GETThe Hunter's Charm#" },
			[27] = { str = "Certifique-se de pegar pelo menos 15 Silk Cloth do correio ou alt da AH" },
			[28] = { str = "Sete seu Hearthstone em IF e aceite #GETAssisting Arch Druid Staghelm#" },
			[29] = { str = "Voe pra Thelsamar" },
			[30] = { str = "Desca ate Badlands ate o oeste em #COORD[01,62]# e entre em Searing Gorge", x = 1, y = 62, zone = "Badlands" },
		}
	},
}
