--[[--------------------------------------------------
003_Alliance_50to60.lua
Authors: mrmr, lanjelin
Version: 1.04.3
------------------------------------------------------
Description: Guide Serie - 003 From Lvl 50 to Lvl 60
	1.04.1
		-- First Release
			Alliance's Guide
			from level 50 to lever 60
	1.04.2
		-- no changes in here for this revision
	1.04.3
		-- Added color codes
			Fixed various spelling errors
			Adjustment to coordinate visibility
------------------------------------------------------
Connection:
--]]--------------------------------------------------

Table_003_Alliance_50to60 = {
-----------50-51 Searing Gorge
	--[501] = {
	[5051] = {
		title = "50-51 Searing Gorge",
		--n = "50-51 Searing Gorge",
		--pID = 413, nID = 502,
		--itemCount = 72,
		items = {
			[1] = { str = "50-51 Searing Gorge" },
			[2] = { str = "Desca ate #COORD[65,62]# e toque na casinha, aceite #GETCaught!#", x = 65, y = 62, zone = "Searing Gorge" },
			[3] = { str = "Va logo abaixo da casinha e mate os geologos para #DOCaught!#" },
			[4] = { str = "Limpe todos os mobs e no fundo do pequeno buraco, aceite #GETSuntara Stones pt.1# escorte ele ate #COORD[74,19]# e quando ele morrer pegue a nota que inicia #GETSuntara Stones pt.2#", x = 74, y = 19, zone = "Searing Gorge" },
			[5] = { str = "Volte perto da casinha em #COORD[65,62]# e pegue os ultimos kills de geologos se precisar e entregue #INCaught!# na casinha, aceite #GETLedger From Tanaris# e pegue o livro que ele desliza por baixo da porta.", x = 65, y = 62, zone = "Searing Gorge" },
			[6] = { str = "Desca ate #COORD[71,72]# e mate #NPCMargol the Rager#, e pegue Margol's Horn dele que inicia #GETThe Horn of the Beast# Isso te da a chave de searing gorge, inutil agora que tem FP aqui mas bom XP", x = 71, y = 72, zone = "Searing Gorge" },
			[7] = { str = "Va ate #COORD[39,38]# e aceite #GETDivine Retribution# depois fale com ele ate completar, aceite #GETThe Flawless Flame#", x = 39, y = 38, zone = "Searing Gorge" },
			[8] = { str = "Suba ate Thorium Point em #COORD[38,26]#", x = 38, y = 26, zone = "Searing Gorge" },
			[9] = { str = "Pegue essas quests na placa: #GETWANTED: Overseer Maltorius# (isso vai precisar de grupo) #GETSTOLEN: Smithing Tuyere and Lookout's Spyglass# e #GETJOB OPPORTUNITY: Culling the Competition#" },
			[10] = { str = "Aceite #GETCurse These Fat Fingers# #GETFiery Menace!# #GETIncendosaurs? Whateverosaur is More Like It# perto da torre" },
			[11] = { str = "Debaixo da tenda aceite #GETWhat The Flux?#" },
			[12] = { str = "Pegue o FP e voe pra IF" },
			[13] = { str = "Pare em #COORD[71,16]# e entregue #INSuntara Stones pt.2# aceite #GETDwarven Justice#", x = 71, y = 16, zone = "Searing Gorge" },
			[14] = { str = "Voe pra Thelsamar" },
			[15] = { str = "Desca ate #COORD[18,83]# e entregue #INThe Horn of the Beast# aceite #GETProof of Deed#", x = 18, y = 83, zone = "Searing Gorge" },
			[16] = { str = "Use Hearthstone pra IF" },
			[17] = { str = "Va ate #COORD[69,11]# entregue #INProof of Deed#, aceite #GETAt Last!#", x = 69, y = 11, zone = "Searing Gorge" },
			[18] = { str = "Va ate #COORD[75,23]# e aceite #GETA Little Slime Goes A Long Way#", x = 75, y = 23, zone = "Searing Gorge" },
			[19] = { str = "Voe pra Thelsamar e va ate #COORD[18,83]#", x = 18, y = 83, zone = "Searing Gorge" },
			[20] = { str = "Entregue #INAt Last!# coloque a chave no seu chaveiro. 12k xp facil" },
			[21] = { str = "Agora a parte divertida, fazer todas essas quests. Alguns dos mobs que voce tem que matar estao em uma area grande entao eu nao vou listar coords deles." },
			[22] = { str = "Daqui para o sul mate glassweb spiders para #DOLedger From Tanaris#" },
			[23] = { str = "Mate qualquer golem que voce ver por aqui para #DOThe Flawless Flame#" },
			[24] = { str = "Va ao redor da parte sul do caldeirao (o buraco) e circule de volta em direcao ao TP e faca o seguinte:" },
			[25] = { str = "Mate heavy war golems e infernal elementals (nao magma elementals) para #DOThe Flawless Flame# e heavy war golems para #DOCurse These Fat Fingers#" },
			[26] = { str = "Mate dark iron lookouts e steamsmiths (so 6 deles, entao volte se nao droparem, eles parecem dropar bastante outhouse key) para #DOSTOLEN: Smithing Tuyere and Lookout's Spyglass#" },
			[27] = { str = "Entregue #INThe Flawless Flame# aceite #GETForging the Shaft# quando voce estiver perto de TB de novo." },
			[28] = { str = "Mate greater lava spiders (nao searing) para #DOFiery Menace!# Mais pro SW" },
			[29] = { str = "Se a Grimesilt Outhouse Key dropou, use para iniciar #GETThe Key to Freedom# e entregue em #COORD[65,62]#", x = 65, y = 62, zone = "Searing Gorge" },
			[30] = { str = "Va ate #COORD[63,38]# e comece a descer no caldeirao.", x = 63, y = 38, zone = "Searing Gorge" },
			[31] = { str = "Mate dark iron taskmasters e slavers aqui embaixo e dentro da caverna se voce ver eles para #DOJOB OPPORTUNITY: Culling the Competition and Forging the Shaft#" },
			[32] = { str = "Entre nas cavernas em #COORD[41,54]#", x = 41, y = 54, zone = "Searing Gorge" },
			[33] = { str = "Va na caverna ate #COORD[41,25]# e passe pela porta de grades, entregue #INDwarven Justice# aceite #GETRelease Them#", x = 41, y = 25, zone = "Searing Gorge" },
			[34] = { str = "Suba a rampa e fique na direita ate #COORD[40,35]# mate o boss aqui para #DOWANTED: Overseer Maltorius# e pegue #DOWhat The Flux?# no trilho atras dele. Se nao conseguir grupo coloque o pet pra pegar aggro e afaste os caras dos planos. E possivel com 2 pessoas mas bem dificil. Se nao conseguir fazer essa quest nao tem problema mas eu geralmente consigo.", x = 40, y = 35, zone = "Searing Gorge" },
			[35] = { str = "Continue seguindo o caminho que vai pra fora e volta pra dentro. Voce vai chegar a uma grande area sem saida com muitos Incendosaur para #DOIncendosaurs? Whateverosaur is More Like It# Guarde as escamas" },
			[36] = { str = "Grinde ate estar 36k de upar" },
			[37] = { str = "Morra de proposito pra voltar no TP e entregue essas quests" },
			[38] = { str = "Va perto da placa, entregue #INWANTED: Overseer Maltorius#" },
			[39] = { str = "A direita da torre, entregue #INCurse These Fat Fingers# #INFiery Menace!# e #INIncendosaurs? Whateverosaur is More Like It#" },
			[40] = { str = "Va ate a tenda atras daqui, entregue #INSTOLEN: Smithing Tuyere and Lookout's Spyglass# e #INJOB OPPORTUNITY: Culling the Competition#" },
			[41] = { str = "Va ate a proxima tenda, entregue #INWhat The Flux?#" },
			[42] = { str = "Depois de entregar tudo voce agora pode fazer quests repetitivas por pouco xp e reputacao com TB. E por isso que eu disse pra guardar as escamas ou vender" },
			[43] = { str = "Voce deve estar quase no level 51 agora, va ao sul da base ate #COORD[38,38]#", x = 38, y = 38, zone = "Searing Gorge" },
			[44] = { str = "Entregue #INForging the Shaft# aceite #GETThe Flame's Casing#" },
			[45] = { str = "Agora voce deve estar entre 1-2 barras no level 51" },
			[46] = { str = "Va ate o caminho subindo a montanha em #COORD[24,32]#", x = 24, y = 32, zone = "Searing Gorge" },
			[47] = { str = "Mate os elites 1 por 1 no caminho ate a piscina de lava em #COORD[29,25]# e limpe os mobs ao redor, os idolaters nao linkam e nao atacam quando voce toca a pedra no centro. Pule na pedra com mount ou pule na lava e depois nela. Abra para #GETRelease Them#", x = 29, y = 25, zone = "Searing Gorge" },
			[48] = { str = "Enquanto mata esses caras ao redor da piscina voce deve ter encontrado um Symbol of Ragnaros para #DOThe Flame's Casing# se nao, mate ate encontrar" },
			[49] = { str = "Certifique-se de falar com o npc preso perto da lava, ele te da #GETPrayer to Elune pt.1# Ouca a historia curta dele e entregue para #GETPrayer to Elune pt.2# Agora voce tem que matar esses para o drop de Rag e a Prayer of Elune, drops faceis" },
			[50] = { str = "Desca ate #COORD[38,38]# e entregue #INThe Flame's Casing# aceite #GETThe Torch of Retribution pt.1# depois entregue de volta aceite #GETThe Torch of Retribution pt.2# depois pegue a tocha na frente dele e complete e aceite #GETSquire Maltrake# e entregue de volta e aceite #GETSet Them Ablaze!#", x = 38, y = 38, zone = "Searing Gorge" },
			[51] = { str = "Agora equipe o cajado e va ate cada uma das 4 torres em N:#COORD[33,53]# W:#COORD[36,60]# S:#COORD[44,61]# E:#COORD[50,54]# e mate os caras la embaixo, suba e acenda o braseiro." },
			[52] = { str = "Quando pegar todas, procure um lugar seguro pra pular e va nas cavernas em #COORD[41,54]# de novo e pela porta de grades em #COORD[37,44]# e va ate a sala com o golem em #COORD[41,25]# e toque na pedra com velas e entregue Release Them PULE a proxima parte a menos que queira fazer com grupo, e muito dificil voce tem que lutar com aquele golem e um anao ambos elites.", x = 41, y = 54, zone = "Searing Gorge" },
			[53] = { str = "Morra de proposito pra voltar no TP e desca ate #COORD[29,38]# e entregue #INSet Them Ablaze!# assista a cutscene enquanto ele se transforma em dragao", x = 29, y = 38, zone = "Searing Gorge" },
			[54] = { str = "Abra o bau no chao aceite #GETTrinkets...# depois abra de novo e complete. Abra e guarde o Black Dragonflight Molt pra depois em Burning Steppes." },
			[55] = { str = "Voe pra Blasted Lands e suba ate Swamp of Sorrows" },
			[56] = { str = "Va ate #COORD[81,91]# e procure um murloc nomeado #NPCJarquia# para #DOLedger From Tanaris#", x = 81, y = 91, zone = "Swamp of Sorrows" },
			[57] = { str = "Depois de matar ele use Hearthstone pra IF depois pegue um portal pra Darnassus ou voe pra Menethil e pegue o barco pra Auberdine e voe pra Darnassus" },
			[58] = { str = "Va ate o topo do temple of the moon em #COORD[38,80]# e entregue #INPrayer to Elune pt.2#", x = 38, y = 80, zone = "darnassus" },
			[59] = { str = "Va ate a proxima secao aqui em cima e entregue #INRise of the Silithid# aceite #GETMarch of the Silithid#" },
			[60] = { str = "Va ate 34,9 no topo da torre e entregue #INAssisting Arch Druid Staghelm# aceite #GETUn'Goro Soil#", x = 34, y = 9, zone = "darnassus" },
			[61] = { str = "Sete seu Hearthstone em Darnassus em #COORD[67,15]#", x = 67, y = 15, zone = "darnassus" },
			[62] = { str = "Agora voe pra Theramore ou pegue o barco pra Menethil e depois pra Theramore" },
			[63] = { str = "Suba first aid ate 290 se ainda nao tiver para heavy runecloth bandages" },
			[64] = { str = "Va ate #COORD[54,55]# no navio destruido e pegue o overdue package para #DOLedger From Tanaris#", x = 54, y = 55, zone = "Duskwallow Marsh" },
			[65] = { str = "Va ate a caverna em #COORD[31,66]# e toque no scroll no fundo da caverna que entrega #INCortello's Riddle pt.2# aceite #GETCortello's Riddle pt.3#", x = 31, y = 66, zone = "Duskwallow Marsh" },
			[66] = { str = "Puxe aggro de todos os raptors e morra pra voltar em Theramore" },
			[67] = { str = "Voe pra Gadgetzan" },
			[68] = { str = "Logo ao entrar em Gadgetzan, entregue #INLedger From Tanaris#" },
			[69] = { str = "Pegue suas luvas do set level 52 do banco ou correio pra depois" },
			[70] = { str = "Entre os 2 portoes do Norte aceite #GETSuper Sticky#" },
			[71] = { str = "Va ate a cabana logo a oeste e entregue #INMarch of the Silithid# aceite #GETBungle in the Jungle#" },
			[72] = { str = "Desca ate Un'Goro Crater em #COORD[26,52]#", x = 26, y = 52, zone = "Tanaris" },
		}
	},

-----------51-52 Un'Goro Crater
	--[502] = {
	[5152] = {
		title = "51-52 Un'Goro Crater",
		--n = "51-52 Un'Goro Crater",
		--pID = 501, nID = 503,
		--itemCount = 34,
		items = {
			[1] = { str = "51-52 Un'Goro Crater" },
			[2] = { str = "Fique de olho nos seguintes itens espalhados pela cratera: Power Crystals (precisa de 7 de red,blue,green,yellow), Un'Goro Dirt Piles (pegue o maximo que puder), e Bloodpetal Sprouts: guarde em sets de 15" },
			[3] = { str = "Eu mando voce grindar nos raptors aqui por 1 motivo. Pra achar o item #NPCA Mangled Journal#. Depois que tiver ele voce nao precisa mais grindar nos raptors." },
			[4] = { str = "Siga o caminho ate a cachoeira em #COORD[71,75]# e aceite #GETThe Apes of Un'Goro# e #GETThe Fare of Lar'Korwi#", x = 71, y = 75, zone = "Un'Goro Crater" },
			[5] = { str = "Grinde ate #COORD[62,68]# e clique na balsa destruida, aceite #GETIt's A Secret to Everybody pt.1# depois de 2 passos debaixo d'agua, entregue e aceite #GETIt's A Secret to Everybody pt.2#", x = 62, y = 68, zone = "Un'Goro Crater" },
			[6] = { str = "Grinde ate #COORD[68,56]# e pegue a carne do dinossauro grande para #DOThe Fare of Lar'Korwi#", x = 68, y = 56, zone = "Un'Goro Crater" },
			[7] = { str = "Volte ate #COORD[71,75]# e entregue #INThe Fare of Lar'Korwi# aceite #GETThe Scent of Lar'Korwi#", x = 71, y = 75, zone = "Un'Goro Crater" },
			[8] = { str = "Grinde pro oeste ate #COORD[67,63]# e tera 2 spots com um monte de ovos. Limpe os raptors ao redor e fique em cima dos ovos pra spawnar os mates para #DOThe Scent of Lar'Korwi#", x = 67, y = 63, zone = "Un'Goro Crater" },
			[9] = { str = "Depois de terminar, volte ate #COORD[71,75]# e entregue #INThe Scent of Lar'Korwi# aceite #GETThe Bait For Lar'Korwi# voce ja deve ter achado o jornal tambem, se nao continue grindando raptors enquanto questa nesse spot. Se tiver inicie a quest #GETWilliden's Journal#", x = 71, y = 75, zone = "Un'Goro Crater" },
			[10] = { str = "Suba ate #COORD[79,49]# fica pro lado leste nas montanhas, atras do eastern pylon. Voce vai ver um esqueleto grande que tambem e o GY. Tem uma pedra grande e plana, fique em cima e use a carne e o feromonio. Isso vai invocar Lar'Korwi para #DOThe Bait For Lar'Korwi# kill super facil mesmo no 51 e ele e 56, tem 3600 hp.", x = 79, y = 49, zone = "Un'Goro Crater" },
			[11] = { str = "Va ate #COORD[46,13]# e aceite #GETChasing A-Me 01# e suba o caminho atras dela ate Marshal's Refuge.", x = 46, y = 13, zone = "Un'Goro Crater" },
			[12] = { str = "Logo a esquerda aceite #GETShizzle's Flyer#" },
			[13] = { str = "Proximo a esquerda, um pouco pra tras, aceite #GETMuigin and Larion#" },
			[14] = { str = "Proximo, perto da placa aceite #GETLost!# e na placa aceite #GETBeware of Pterrordax#" },
			[15] = { str = "Na frente da caverna, aceite #GETRoll the Bones#" },
			[16] = { str = "Se voce tiver pelo menos 15 bloodpetal sprouts, entregue no kodo pra quest repetitiva #GETDadanga is Hungry!# voce pode pegar uma receita muito rara e cara entao vale a pena tentar." },
			[17] = { str = "A direita da caverna, aceite #GETAlien Ecology#" },
			[18] = { str = "A direita de novo, entregue #INWilliden's Journal# aceite #GETExpedition Salvation#" },
			[19] = { str = "Va um pouco ao sul e voce vai achar Linken logo fora de uma arvore oca. Entregue #INIt's A Secret to Everybody pt.2# aceite #GETIt's A Secret to Everybody pt.3#" },
			[20] = { str = "Pegue o FP a direita da caverna (adicionado na 1.11) depois entre na caverna ate o final e aceite #GETCrystals of Power# e depois entregue. Aceite as 3 quests de pylon #GETThe Northern Pylon# #GETThe Eastern Pylon# #GETThe Western Pylon#" },
			[21] = { str = "Sempre que voce ver os seguintes mobs mate eles ate a quest associada estar completa." },
			[22] = { str = "Mate bloodpetals para #DOMuigin and Larion#" },
			[23] = { str = "Mate diametradons e pterrodaxes para #DOShizzle's Flyer# e #DORoll the Bones#" },
			[24] = { str = "Mate pterrodaxes e frenzied pterrodaxes para #DOBeware of Pterrordax#" },
			[25] = { str = "Va pro leste ao longo das montanhas ate #COORD[54,13]# e suba aquele caminho examine o pylon para #DOThe Northern Pylon# e va mais pro norte, deve ter uns pterrodaxes.", x = 54, y = 13, zone = "Un'Goro Crater" },
			[26] = { str = "Va pro leste ate #COORD[63,16]# e mate gorilas para #DOThe Apes of Un'Goro# depois entre na caverna e fique na direita pra entregar #INChasing A-Me 01# PULE a proxima parte por enquanto", x = 63, y = 16, zone = "Un'Goro Crater" },
			[27] = { str = "Voce vai ver uns lagos pretos perto do norte do mapa ao redor de #COORD[52,23]# Mate os tar monsters ao redor dos lagos para #DOSuper Sticky# Os 3 lagos ao sul dos gorilas ao redor de #COORD[61,27]# tem tar monsters de level mais baixo e tambem tem bloodpetals aqui para #DOMuigin and Larion# tambem tem diametradons e pterrodaxes para #DOShizzle's Flyer# rodando por aqui", x = 61, y = 27, zone = "Un'Goro Crater" },
			[28] = { str = "Pare em #COORD[68,36]# e pegue a caixa de comida para #DOExpedition Salvation#", x = 68, y = 36, zone = "Un'Goro Crater" },
			[29] = { str = "Tente coletar tudo para #DOShizzle's Flyer# aqui fora se voce nao estiver so procurando eles. Eu sempre consigo achar todos antes de terminar as bloodpetals." },
			[30] = { str = "Va ate #COORD[76,51]# e siga o caminho ate o pylon para #DOThe Eastern Pylon# e deve ter pterrodaxes mais ao sul em #COORD[75,61]#", x = 76, y = 51, zone = "Un'Goro Crater" },
			[31] = { str = "Va ate #COORD[71,75]# e entregue #INThe Bait For Lar'Korwi# e #INThe Apes of Un'Goro# PULE a proxima parte por enquanto", x = 71, y = 75, zone = "Un'Goro Crater" },
			[32] = { str = "Agora se voce grindou bastante como eu naquelas flores e dinossauros, voce deve estar bem perto do level 52 se nao ja 52." },
			[33] = { str = "Logo a leste do vulcao (centro do mapa) tem pterrodaxes tudo para #DOBeware of Pterrordax# se voce estiver tendo dificuldade pra achar tem um spawn de 6 deles bem ao sul em #COORD[55,90]#", x = 55, y = 90, zone = "Un'Goro Crater" },
			[34] = { str = "Va pro oeste ate #COORD[55,73]# tem um camp de diametradon com uns 5-6. Mate esses se ainda precisar de escamas para #DOShizzle's Flyer# ou #DORoll the Bones#", x = 55, y = 73, zone = "Un'Goro Crater" },
			[35] = { str = "Va pro oeste ate #COORD[50,77]# entrando no slithering scar, na bifurcacao va pra esquerda na sala grande, fique no meio, use o scraping vial para #DOAlien Ecology#", x = 50, y = 77, zone = "Un'Goro Crater" },
			[36] = { str = "Tem outro camp de diametradon se voce ainda precisar de escamas ou ossos para #DOShizzle's Flyer# ou #DORoll the Bones# e eles tambem estao por toda parte agora" },
			[37] = { str = "Va ate o acampamento em #COORD[38,65]# e pegue o equipamento de pesquisa para #DOExpedition Salvation#", x = 38, y = 65, zone = "Un'Goro Crater" },
			[38] = { str = "Mate frenzied pterrodaxes ao redor de #COORD[35,38]# (estao por toda parte) na parte NW do mapa para #DOBeware of Pterrordax# alem de ter muitos diametradons aqui para #DOShizzle's Flyer# ou #DORoll the Bones#", x = 35, y = 38, zone = "Un'Goro Crater" },
			[39] = { str = "Desca ate #COORD[23,59]# e toque no western pylon para #DOThe Western Pylon# e mate qualquer pterrodax que precisar atras dele", x = 23, y = 59, zone = "Un'Goro Crater" },
			[40] = { str = "Va ate #COORD[30,50]# e aceite #DOFinding the Source#", x = 30, y = 50, zone = "Un'Goro Crater" },
			[41] = { str = "Va ate Fire Plume Ridge em #COORD[51,48]# e mate elementais, tente evitar qualquer coisa 56+ para #DOVolcanic Activity# Deixe os blazing invaders em paz", x = 51, y = 48, zone = "Un'Goro Crater" },
			[42] = { str = "Depois de terminar isso, dispense o pet e monte em direcao ao topo do vulcao e procure o que parece com as pedras de espera de instancia mas com rachaduras de fogo. Desmonte e FD depois se tiver mob perto coloque o pet nele e use o termometro para Finding the Source tem mais de um e nao precisa ser no topo eu vejo eles embaixo tambem." },
			[43] = { str = "A menos que voce ainda precise de cinzas va ate #COORD[30,50]# e entregue #INFinding the Source# aceite #GETThe New Springs#", x = 30, y = 50, zone = "Un'Goro Crater" },
			[44] = { str = "Suba na caverna (do mesmo jeito) em #COORD[51,49]# e entregue #INLost!# depois aceite #GETA Little Help From My Friends# ele te segue, depois que voce tirar ele da ridge e facil. So va reto pra fora da caverna pela beirada, se feito certo voce so precisa lutar com 1 elemental. Depois de ir pro norte passando o rio e tranquilo.", x = 51, y = 49, zone = "Un'Goro Crater" },
			[45] = { str = "Quando voce levar ele de volta pra cidade suba perto da placa ao lado da caverna e vai completar depois entregue e #INBeware of Pterrordax#" },
			[46] = { str = "Entregue #INShizzle's Flyer#" },
			[47] = { str = "Entregue #INMuigin and Larion# PULE o resto" },
			[48] = { str = "Entregue #INRoll the Bones#" },
			[49] = { str = "Entregue #INAlien Ecology#" },
			[50] = { str = "Entregue #INExpedition Salvation#" },
			[51] = { str = "No fundo da caverna entregue #INThe Northern Pylon# #INThe Eastern Pylon# #INThe Western Pylon# aceite #GETMaking Sense of It# depois entregue de volta. Ela te fala sobre buffs dos pylons." },
			[52] = { str = "Va ate #COORD[29,22]# e siga o caminho ate Silithus em #COORD[50,34]# pegue o FP e voe pra Gadgetzan.", x = 29, y = 22, zone = "Un'Goro Crater" },
			[53] = { str = "Va ate a parte NW da cidade, entregue #INBungle in the Jungle# PULE a proxima parte depois entregue #INSuper Sticky# entre as 2 entradas" },
			[54] = { str = "Use Hearthstone pra Darnassus e pegue novas skills" },
			[55] = { str = "Voce deve ter pelo menos 50+ soils agora." },
			[56] = { str = "Va ate 31,8 e entregue #INUn'Goro Soil#", x = 31, y = 8, zone = "Darnassus" },
			[57] = { str = "Agora suba ate o topo da torre e aceite #GETMorrowgrain Research pt.1# depois desca e entregue, aceite #GETMorrowgrain Research pt.2#" },
			[58] = { str = "Agora voce pode querer pegar packets de sementes extras dependendo de quantos soils voce tem. Voce pode usar a bolsa a cada 10 minutos e nem sempre vai pegar um morrowgrain. Voce so precisa de 10 mesmo" },
			[59] = { str = "Va ate Rut'theran Village e entre na casa a direita e aceite #GETMoontouched Wildkin# e uma quest de pena de winterspring" },
			[60] = { str = "Voe pra Astranaar, depois va cavalgando todo o caminho pro leste na estrada ate #COORD[91,46]# que vai dar em Azshara", x = 91, y = 46, zone = "Ashenvale" },
		}
	},

-----------52-53 Azshara
	--[503] = {
	[5253] = {
		title = "52-53 Azshara",
		--n = "52-53 Azshara",
		--pID = 502, nID = 504,
		--itemCount = 10,
		items = {
			[1] = { str = "52-53 Azshara" },
			[2] = { str = "Logo ao entrar, na direita em #COORD[11,77]# pegue o FP", x = 11, y = 77, zone = "Azshara" },
			[3] = { str = "Logo atras dele, aceite #GETSpiritual Unrest# e #GETA Land Filled With Hatred#" },
			[4] = { str = "Va um pouco ao norte ate #COORD[14,72]# e #COORD[16,67]# e mate todos os fantasmas por aqui ate completar #DOSpiritual Unrest#", x = 14, y = 72, zone = "Azshara" },
			[5] = { str = "Va um pouco ao norte ate #COORD[19,61]# e mate todos os satyrs por aqui para #DOA Land Filled With Hatred", x = 19, y = 61, zone = "Azshara" },
			[6] = { str = "Volte ate #COORD[11,77]# e entregue #INSpiritual Unrest# e #INA Land Filled With Hatred#", x = 11, y = 77, zone = "Azshara" },
			[7] = { str = "Va ate #COORD[39,55]# e pegue o rubbing de Markri para #DOArcane Runes#", x = 39, y = 55, zone = "Azshara" },
			[8] = { str = "Va ate #COORD[36,53]# e pegue o rubbing de Beth'Amara para #DOArcane Runes#", x = 36, y = 53, zone = "Azshara" },
			[9] = { str = "Va ate #COORD[39,50]# e pegue o rubbing de Jin'yael para #DOArcane Runes#", x = 39, y = 50, zone = "Azshara" },
			[10] = { str = "Va ate #COORD[42,42]# e entregue #INThe Hunter's Charm# aceite #GETCourser Antlers# essa quest e a seguinte sao opcionais pra fazer depois de virar level 53, eu faco entao se voce nao fizer vai ficar um pouco atras no guia. Leva cerca de 1-2 horas pra pegar todas as pecas dessa e da proxima quest mas vai te colocar uns 20-25% dentro do level", x = 42, y = 42, zone = "Azshara" },
		}
	},

------------53-54 Felwood
	--[504] = {
	[5354] = {
		title = "53-54 Felwood",
		--n = "53-54 Felwood",
		--pID = 503, nID = 505,
		--itemCount = 51,
		items = {
			[1] = { str = "53-54 Felwood" },
			[2] = { str = "Pare em #COORD[54,86]# e aceite #GETCleansing Felwood#", x = 54, y = 86, zone = "Felwood" },
			[3] = { str = "Va um pouco ao norte ate #COORD[51,81]# e aceite #GETForces of Jaedenar#", x = 51, y = 81, zone = "Felwood" },
			[4] = { str = "Dentro da casa, aceite #GETThe Corruption of the Jadefire#" },
			[5] = { str = "Debaixo da tenda aceite #GETVerifying the Corruption# e #GETTo Winterspring!#" },
			[6] = { str = "Logo do outro lado da estrada aceite #GETTimbermaw Ally#" },
			[7] = { str = "Va pro SW daqui ao redor de #COORD[48,91]# e mate os Furlbogs ate terminar #DOTimbermaw Ally# So grinde todos eles por rep ate terminar", x = 48, y = 91, zone = "Felwood" },
			[8] = { str = "Volte ate #COORD[50,85]# e entregue #INTimbermaw Ally# aceite #GETSpeak to Nefian# a outra e repetitiva por rep", x = 50, y = 85, zone = "Felwood" },
			[9] = { str = "Suba perto dos 2 lagos em #COORD[40,69]# e mate os cursed oozes para a primeira parte de #DOA Little Slime Goes A Long Way pt.1#", x = 40, y = 69, zone = "Felwood" },
			[10] = { str = "Va pro oeste daqui ate #COORD[37,69]# e mate os demonios jadefire para #DOThe Corruption of the Jadefire# esses sao bons pra farmar tambem.", x = 37, y = 69, zone = "Felwood" },
			[11] = { str = "Suba ate #COORD[39,59]# e mate os tainted oozes para a segunda parte de #DOA Little Slime Goes A Long Way pt.1", x = 39, y = 59, zone = "Felwood" },
			[12] = { str = "Va logo pro oeste daqui ao redor de #COORD[37,59]# e mate os Jaedenar para #DOForces of Jaedenar# Voce nao precisa entrar nas cavernas.", x = 37, y = 59, zone = "Felwood" },
			[13] = { str = "Volte ate #COORD[51,82]# e entregue #INForces of Jaedenar# aceite #GETCollection of the Corrupt Water#.", x = 51, y = 82, zone = "Felwood" },
			[14] = { str = "Dentro da casa entregue #INThe Corruption of the Jadefire# aceite #GETFurther Corruption#" },
			[15] = { str = "Volte ate Jaedenar na piscina verde em #COORD[35,59]# e encha o cantil para #DOCollection of the Corrupt Water#", x = 35, y = 59, zone = "Felwood" },
			[16] = { str = "Volte ate #COORD[51,82]# e entregue #INCollection of the Corrupt Water# aceite #GETSeeking Spiritual Aid#", x = 51, y = 82, zone = "Felwood" },
			[17] = { str = "Suba ate #COORD[42,20]# e mate Entropic beasts e horrors e explore as crateras para #DOVerifying the Corruption#.", x = 42, y = 20, zone = "Felwood" },
			[18] = { str = "Suba ate #COORD[46,14]# e siga ate o fundo, matando os demonios para #DOFurther Corruption# Quando voce matar Xavaric ele vai dropar Flute of Xavaric que inicia #GETFlute of Xavaric# mate os satyrs pra completar essa.", x = 46, y = 14, zone = "Felwood" },
			[19] = { str = "Va ate Irontree Cavern em #COORD[55,17]# e mate 15 dos elementais e deve ser suficiente para #DOCleansing Felwood#", x = 55, y = 17, zone = "Felwood" },
			[20] = { str = "Suba ate #COORD[62,24]# e pegue o FP", x = 62, y = 24, zone = "Felwood" },
			[21] = { str = "Va ao norte ate 64,8 e entregue #INSpeak to Nefian# aceite #GETDeadwood of the North#", x = 64, y = 8, zone = "Felwood" },
			[22] = { str = "Agora pule do penhasco pro oeste e comece a matar para Deadwood of the North, quando terminar voce quer matar ate estar a 150 rep do proximo rank com os timbermaw (coloque a rep como barra de xp pra facilitar)" },
			[23] = { str = "Volte ate 64,8 e entregue #INDeadwood of the North# e voce deve estar unfriendly agora e nao mais com aggro. Aceite #GETSpeak to Salfa# e entregue qualquer 5 sets de penas por rep extra e 550 xp", x = 64, y = 8, zone = "Felwood" },
			[24] = { str = "Va pela caverna ate Winterspring e logo fora da caverna a direita em #COORD[27,34]# entregue #INSpeak to Salfa#", x = 27, y = 34, zone = "Winterspring" },
			[25] = { str = "Va ao sul ate #COORD[31,45]# e entregue #INThe New Springs# aceite #GETStrange Sources# tambem entregue #INIt's A Secret to Everybody pt.3# aceite #GETThe Videre Elixir# e #GETThreat of the Winterfall#", x = 31, y = 45, zone = "Winterspring" },
			[26] = { str = "Volte pela caverna e va pro oeste na bifurcacao ate Moonglade." },
			[27] = { str = "Va ate #COORD[48,67]# e pegue o FP", x = 48, y = 67, zone = "Moodglade" },
			[28] = { str = "Voce deve estar bem perto de upar agora. Voce pode grindar o resto do caminho. Use Hearthstone pra Astranaar e voe pra Feralas" },
			[29] = { str = "Va no Inn, aceite #GETJonespyre's Request#" },
			[30] = { str = "Suba ate o topo da torre, entregue, aceite #GETThe Mystery of Morrowgrain# entregue de volta a menos que voce ainda esteja fazendo o material." },
			[31] = { str = "Suba ate #COORD[45,25]# e compre uma isca e leia sobre como pegar o videre elixir", x = 45, y = 25, zone = "Feralas" },
			[32] = { str = "Em #COORD[45,16]# voce pode ser levado ao topo da torre colossal e usar paraquedas pra descer. So certifique-se de desmontar!", x = 45, y = 16, zone = "Feralas" },
			[33] = { str = "Suba ate #COORD[44,10]# e coloque a isca no chao depois va pegar um everroot", x = 44, y = 10, zone = "Felalas" },
			[34] = { str = "Volte pro sul ate #COORD[45,25]# pra pegar seus 3 videre elixir", x = 45, y = 25, zone = "Felalas" },
			[35] = { str = "Use Hearthstone pra Astranaar" },
			[36] = { str = "Volte subindo ate Felwood em #COORD[54,86]# e entregue #INCleansing Felwood#", x = 54, y = 86, zone = "Felwood" },
			[37] = { str = "Agora ela permite que voce pegue material pra umas pocoes legais que tem cooldowns diferentes das pocoes normais." },
			[38] = { str = "Suba ate #COORD[51,81]# e na casa entregue #INFurther Corruption# e #INFlute of Xavaric# aceite #GETFelbound Ancients#", x = 51, y = 81, zone = "Felwood" },
			[39] = { str = "Debaixo da tenda, entregue #INVerifying the Corruption#" },
			[40] = { str = "Suba ate #COORD[62,23]#", x = 62, y = 23, zone = "Felwood" },
			[41] = { str = "Va pela caverna ate Winterfall e logo fora da caverna aceite #GETWinterfall Activity#" },
			[42] = { str = "Va ate #COORD[31,45]# e entregue #INThe Videre Elixir# aceite #GETMeet at the Grave#", x = 31, y = 45, zone = "Winterspring" },
			[43] = { str = "Va ate #COORD[62,36]# e pegue o FP", x = 62, y = 36, zone = "Winterspring" },
			[44] = { str = "Voe pra Rachet" },
			[45] = { str = "Va pro oeste do dock e entregue #INVolcanic Activity#" },
			[46] = { str = "Desca ate #COORD[65,43]# e entregue #INSeeking Spiritual Aid# aceite Cleansed Water Returns to Felwood", x = 65, y = 43, zone = "The Barrens" },
			[47] = { str = "Voe pra Theramore e pegue o barco pra Menethil depois voe pra IF" },
			[48] = { str = "Logo fora do Military Ward deve ter um npc andando, um fica perto do FP tambem, pegue a quest #GETThe New Frontier pt.1#" },
			[49] = { str = "Va ate #COORD[75,23]# e entregue #INA Little Slime Goes A Long Way pt.1# aceite #GETA Little Slime Goes A Long Way pt.2#", x = 75, y = 23, zone = "Ironforge" },
			[50] = { str = "Va ate 31,4 e entregue #INReturn to Tymor#", x = 31, y = 4, zone = "Ironforge" },
			[51] = { str = "Voe pra Menethil depois pegue o barco pra Theramore e voe pra Gadgetzan" },
		}
	},

-----------54-54 Tanaris
	--[505] = {
	[5453] = {
		title = "54-54 Tanaris",
		--n = "54-54 Tanaris",
		--pID = 504, nID = 506,
		--itemCount = 20,
		items = {
			[1] = { str = "54-54 Tanaris" },
			[2] = { str = "Pegue sua mithril casing do banco ou caixa de correio" },
			[3] = { str = "Va pro leste ate o GY em #COORD[54,28]# e beba seu videre elixir", x = 54, y = 28, zone = "Tanaris" },
			[4] = { str = "Agora voce vai morrer, nao ressuscite so libere e va pro norte ate #COORD[53,23]# e entregue #INMeet at the Grave# aceite #GETA Grave Situation#", x = 53, y = 23, zone = "Tanaris" },
			[5] = { str = "Volte e ressuscite em #COORD[54,28]# e toque na unica lapide ali, entregue #INA Grave Situation# aceite #GETLinken's Sword#", x = 54, y = 28, zone = "Tanaris" },
			[6] = { str = "Entre em Un'Goro, eu diria pra voar mas temos que ir pro SE" },
			[7] = { str = "Suba ate #COORD[71,75]# e aceite #GETThe Mighty U'cha#", x = 71, y = 75, zone = "Un'Goro" },
			[8] = { str = "Continue coletando terra aqui se precisar de mais morrowgrain" },
			[9] = { str = "Agora ao redor de toda a cratera tem slimes mas voce pode achar todos que precisa a oeste do vulcao ao redor de #COORD[37,37]# para #DOA Little Slime Goes A Long Way pt.2# Eu acho que tem mais no lado oeste do vulcao mas voce pode olhar nos dois lados estao espalhados. Se disser que estao clonando, termine eles bem rapido ou atordoe. Se clonarem e um mob com vida cheia que voce nao pode coletar.", x = 37, y = 37, zone = "Un'Goro" },
			[10] = { str = "Va ate a caverna em #COORD[64,16]# e va pra direita, quando voce ver A-Me 01 aceite #GETChasing A-Me 01 pt.1# e entregue de volta. Pule pela beirada e pra direita e suba ao redor ate ver U'cha para #DOThe Mighty U'cha#", x = 64, y = 16, zone = "Un'Goro" },
			[11] = { str = "Volte pra frente e va pra direita de novo e aceite #GETChasing A-Me 01 pt.2# agora escorte ela pra fora" },
			[12] = { str = "Escorte A-Me ate Marshal's em #COORD[46,13]# e entregue #INChasing A-Me 01 pt.2#", x = 46, y = 13, zone = "Un'Goro" },
			[13] = { str = "Entre em Marshal's e entregue #INLinken's Sword# aceite #GETA Gnome's Assistance#" },
			[14] = { str = "Va ate o fundo da caverna e entregue #INA Gnome's Assistance# e aceite #GETLinken's Memory#" },
			[15] = { str = "Desca e deixe os tar monsters te matarem pra voce ficar mais perto do SE" },
			[16] = { str = "Desca ate #COORD[71,75]# e entregue #INThe Mighty U'cha#", x = 71, y = 75, zone = "Un'Goro" },
			[17] = { str = "Voce deve estar passando da metade do level 55 agora" },
			[18] = { str = "Use Hearthstone pra Astranaar e voe pra Darnassus" },
			[19] = { str = "Entre no Temple of the Moon em #COORD[39,84]# e encha o frasco para #DOFelbound Ancients#", x = 39, y = 84, zone = "Darnassus" },
			[20] = { str = "Entre em Felwood" },
		}
	},

-----------54-54 Felwood
	--[506] = {
	[5454] = {
		title = "54-54 Felwood",
		--n = "54-54 Felwood",
		--pID = 505, nID = 507,
		--itemCount = 16,
		items = {
			[1] = { str = "54-54 Felwood" },
			[2] = { str = "Va ate #COORD[51,82]# e entregue #INCleansed Water Returns to Felwood# aceite #GETDousing the Flames of Protection#", x = 51, y = 82, zone = "Felwood" },
			[3] = { str = "Entre na casa, entregue #INFelbound Ancients# aceite #GETPurified!# depois entregue de volta, 10k xp facil. Tambem entregue #INLinken's Memory# aceite #GETSilver Heart#" },
			[4] = { str = "Voce deve estar 70% agora ou perto disso" },
			[5] = { str = "Comece matando todos os ursos e lobos daqui pro norte ate ter 11 silvery claws para #DOSilver Heart#" },
			[6] = { str = "Entre na caverna em #COORD[35,58]#", x = 35, y = 58, zone = "Felwood" },
			[7] = { str = "Na primeira area aberta com o npc preso em #COORD[36,56]# tem um braseiro para #DODousing the Flames of Protection# o 2o esta logo subindo a rampa", x = 36, y = 56, zone = "Felwood" },
			[8] = { str = "Continue passando a sala com velas ao redor do buraco ate a proxima sala aberta em #COORD[36,53]# para o 3o e 4o braseiro para #DODousing the Flames of Protection#", x = 36, y = 53, zone = "Felwood" },
			[9] = { str = "Nem tente fazer a escolta a menos que consiga um grupo, eu sempre pulo mesmo se achar a chave." },
			[10] = { str = "Volte pra fora e suba ate #COORD[51,19]# e mate os elementais arvore para #DOSilver Heart#", x = 51, y = 19, zone = "Felwood" },
			[11] = { str = "Se quiser fazer a escolta com a flauta eu sugiro pegar um grupo voce leva muitos mobs." },
			[12] = { str = "Va todo o caminho de volta ate #COORD[51,82]# (eu sei que ninguem quer voltar aqui, porque o quest hub e tao longe do FP e alem de mim)", x = 51, y = 82, zone = "Felwood" },
			[13] = { str = "Entregue #INDousing the Flames of Protection# PULE a proxima parte por enquanto" },
			[14] = { str = "Na casa entregue #INSilver Heart# aceite #GETAquementas#" },
			[15] = { str = "Se voce tem skinning tenho certeza que voce ja tem pelo menos 5 tainted hides, desca ate #COORD[54,86]# e entregue para #INSalve via Skinning#", x = 54, y = 86, zone = "Felwood" },
			[16] = { str = "Use Hearthstone pra Astranaar e voe pra Winterspring" },
		}
	},

--------------54-55 Winterspring
	--[507] = {
	[5455] = {
		title = "54-55 Winterspring",
		--n = "54-55 Winterspring",
		--pID = 506, nID = 508,
		--itemCount = 34,
		items = {
			[1] = { str = "54-55 Winterspring" },
			[2] = { str = "Entre em Everlook aceite #GETEnraged Wildkin pt.1#" },
			[3] = { str = "Entre no Inn, sete como seu lar" },
			[4] = { str = "Aceite #GETThe Everlook Report# #GETDuke Nicholas Zverenhoff# e #GETSister Pamela#" },
			[5] = { str = "Do outro lado da cidade aceite #GETAre We There, Yeti? pt.1#" },
			[6] = { str = "Fique de olho nas penas azuis de moonkin pra terminar #DOMoontouched Wildkin#" },
			[7] = { str = "Va todo o caminho pro sul ate #COORD[60,73]# pra completar #GETStrange Sources#", x = 60, y = 73, zone = "Winterspring" },
			[8] = { str = "Use Hearthstone pra Everlook, se nao estiver pronto morra de proposito" },
			[9] = { str = "Va ate #COORD[65,45]# e mate yetis para #DOAre We There, Yeti? pt.1#", x = 65, y = 45, zone = "Winterspring" },
			[10] = { str = "Volte pra Everlook e entregue #INAre We There, Yeti? pt.1# aceite #GETAre We There, Yeti? pt.2#" },
			[11] = { str = "Volte ate #COORD[65,45]# e mate matriarcas e patriarcas para #DOAre We There, Yeti? pt.2# tem muitos na caverna em #COORD[67,42]#", x = 67, y = 42, zone = "Winterspring" },
			[12] = { str = "Volte pra Everlook e entregue #INAre We There, Yeti? pt.2# aceite #GETAre We There, Yeti? pt.3#" },
			[13] = { str = "Va logo a leste do Inn e assuste Legacki para #DOAre We There, Yeti? pt.3#" },
			[14] = { str = "Va pro leste de Winterspring ate #COORD[66,34]# e mate os furlbogs ali para #DOWinterfall Activity# e parte de #DOThreat of the Winterfall#", x = 66, y = 34, zone = "Winterspring" },
			[15] = { str = "Tomara que voce ache um #NPCEmpty Firewater Flask# em um deles que inicia #GETWinterfall Firewater#" },
			[16] = { str = "Suba ate Starfall Village em #COORD[51,30]# e entregue #INTo Winterspring!# aceite #GETThe Ruins of Kel'Theril#", x = 51, y = 30, zone = "Winterspring" },
			[17] = { str = "Entregue #INEnraged Wildkin pt.1# PULE a parte 2 por enquanto tambem entregue #INThe Ruins of Kel'Theril# aceite #GETTroubled Spirits of Kel'Theril#" },
			[18] = { str = "Pegue a reliquia em #COORD[55,42]# para #DOTroubled Spirits of Kel'Theril# dispense o pet antes de abrir depois corra e FD. 2a reliquia em #COORD[53,43]#. 3a em #COORD[52,41]# 4a em #COORD[50,41]#" },
			[19] = { str = "Va pro oeste ate #COORD[39,43]# e mate furlbogs aqui para #DOThreat of the Winterfall# tambem certifique-se de ter suas 10 penas para #DOMoontouched Wildkin#", x = 39, y = 43, zone = "Winterspring" },
			[20] = { str = "Va ate #COORD[31,45]# e entregue #INStrange Sources# #INThreat of the Winterfall# e #INWinterfall Firewater# aceite #GETFalling to Corruption#", x = 31, y = 45, zone = "Winterspring" },
			[21] = { str = "Va ate #COORD[27,34]# e entregue #INWinterfall Activity#", x = 27, y = 34, zone = "Winterspring" },
			[22] = { str = "Voce deve estar agora 25-30% no level 55" },
			[23] = { str = "Va pelo tunel ate Felwood" },
			[24] = { str = "Va ate 60,5 e toque no caldeirao no acampamento que entrega #INFalling to Corruption# aceite #GETMystery Goo#", x = 60, y = 5, zone = "Winterspring" },
			[25] = { str = "Use Hearthstone pra Everlook depois voe pra Darnassus" },
			[26] = { str = "Em Rut'theran Village entregue #INMoontouched Wildkin# #COORD[55,92]# aceite #GETFind Ranshalla#", x = 55, y = 92, zone = "Darnassus" },
			[27] = { str = "Entre em Darnassus suba ate 34,8 na torre grande e entregue #INThe New Frontier pt.1# aceite #GETThe New Frontier pt.2# desca 1 andar e entregue, aceite #GETRabine Saturna#", x = 34, y = 8, zone = "Darnassus" },
			[28] = { str = "Voe pra Moonglade ate #COORD[51,45]# e entregue #INRabine Saturna# aceite #GETWasteland#", x = 51, y = 45, zone = "Moonglade" },
			[29] = { str = "Voe pra Auberdine, pegue o barco pra Menethil e voe pra IF, sete como seu lar. Certifique-se de ter seu black dragonflight molt" },
			[30] = { str = "Va ate #COORD[75,23]# e entregue #INA Little Slime Goes A Long Way pt.2#", x = 75, y = 23, zone = "Ironforge" },
			[31] = { str = "Va ate #COORD[38,55]# na sala do trono e aceite #GETThe Smoldering Ruins of Thaurissan pt.1# depois clique nela e ouca a historia e entregue de volta, aceite #GETThe Smoldering Ruins of Thaurissan pt.2#", x = 38, y = 55, zone = "Ironforge" },
			[32] = { str = "Na frente do FP aceite #GETTaking Back Silithus#" },
			[33] = { str = "Voe pra Lakeshire" },
			[34] = { str = "Va ao norte ate 46,6 e entre em Burning Steppes", x = 46, y = 6, zone = "Redridge Mountains" },
		}
	},

-----------55-56 Burning Steppes
	--[508] = {
	[5556] = {
		title = "55-56 Burning Steppes",
		--n = "55-56 Burning Steppes",
		--pID = 507, nID = 509,
		--itemCount = 29,
		items = {
			[1] = { str = "55-56 Burning Steppes" },
			[2] = { str = "Va ate #COORD[83,63]# e siga o caminho subindo e pegue o FP", x = 83, y = 63, zone = "Burning Steps" },
			[3] = { str = "Aceite #GETExtinguish the Firegut# e #GETFIFTY! YEP!#" },
			[4] = { str = "Na frente da casa quebrada, aceite #GETDragonkin Menace# Esse e o inicio da cadeia de chave da Onyxia" },
			[5] = { str = "Comece matando ogros por toda a montanha em #COORD[81,42]# para #DOExtinguish the Firegut# depois volte ate #COORD[84,68]# e entregue, aceite #GETGor'tesh the Brute Lord#", x = 81, y = 42, zone = "Burning Steps" },
			[6] = { str = "Va pro NW ate #COORD[66,40]# e colete as ruinas que parecem lapides para #DOThe Smoldering Ruins of Thaurissan pt.2#", x = 66, y = 40, zone = "Burning Steps" },
			[7] = { str = "Suba ate #COORD[65,24]# e entre na caverna, entregue #INYuka Screwspigot# PULE o resto", x = 65, y = 24, zone = "Burning Steps" },
			[8] = { str = "La fora aceite #GETTablet of the Seven# e #GETBroodling Essence#" },
			[9] = { str = "Va ate #COORD[54,40]# e toque na estatua de anao para #DOTablet of the Seven#", x = 54, y = 40, zone = "Burning Steps" },
			[10] = { str = "Va pro oeste ate #COORD[43,46]# no blackrock stronghold ou pro sul ate #COORD[49,55]# o pillar of ash e mate os orcs para #DOFIFTY! YEP!# eles dropam em grande quantidade", x = 43, y = 46, zone = "Burning Steps" },
			[11] = { str = "Enquanto estiver no pillar of ash em #COORD[40,56]# voce deve matar Gor'tesh para #DOGor'tesh the Brute Lord#", x = 40, y = 56, zone = "Burning Steps" },
			[12] = { str = "Consiga um grupo se puder para #DODragonkin Menace# e depois mate os mobs pra isso logo NE do camp ao longo da parede leste. E soloavel mas apertado. Tambem pegue 8 dos broodlings para #DOBroodling Essence# usando o dispositivo neles antes de atacar." },
			[13] = { str = "Va ate a caverna em #COORD[94,31]# e aceite #GETA Taste of Flame# depois de o molt pra ele e entregue a quest de volta. PULE a proxima parte", x = 94, y = 31, zone = "Burning Steps" },
			[14] = { str = "Volte subindo ate #COORD[65,23]# e entregue #INTablet of the Seven# e #INBroodling Essence# aceite #GETFelnok Steelspring#", x = 65, y = 23, zone = "Burning Steps" },
			[15] = { str = "Cavalge de volta ate #COORD[84,68]# e perto do grifo entregue #INFIFTY! YEP!# e #INGor'tesh the Brute Lord# aceite #GETOgre Head On A Stick = Party#", x = 84, y = 68, zone = "Burning Steps" },
			[16] = { str = "Na frente da casa quebrada, entregue #INDragonkin Menace# aceite #GETThe True Masters pt.1#" },
			[17] = { str = "Suba ate o topo da montanha em #COORD[80,45]# e clique na pilha de terra macia para #DOOgre Head On A Stick = Party# depois volte ate #COORD[84,68]# e entregue", x = 80, y = 45, zone = "Burning Steps" },
			[18] = { str = "Voe pra Lakeshire e va ate o town hall em #COORD[29,44]# e entregue #INThe True Masters pt.1# aceite #GETThe True Masters pt.2#", x = 29, y = 44, zone = "Redridge Mountains" },
			[19] = { str = "Voe pra SW" },
			[20] = { str = "Va ate #COORD[78,18]# no SW keep e entregue #INThe True Masters pt.2# aceite #GETThe True Masters pt.3# depois fale com a senhora e depois entregue de volta e aceite #GETThe True Masters pt.4#", x = 78, y = 18, zone = "Stormwind City" },
			[21] = { str = "Voe de volta pra Lakeshire e va ate o townhall em #COORD[29,44]# e entregue #INThe True Masters pt.4# aceite #GETThe True Masters pt.5#", x = 29, y = 44, zone = "Redridge Mountains" },
			[22] = { str = "Voe pra Burning Steppes e entregue #INThe True Masters pt.5# quando pousar e aceite #GETThe True Masters pt.6#" },
			[23] = { str = "Suba ate #COORD[64,23]# e ouca ragged john depois volte ate #COORD[84,68]# e entregue #INThe True Masters pt.6# Eu PULO a proxima parte, faca depois se estiver preocupado com speed leveling. Foram 30k xp facil por nao fazer nada e sua cadeia de chave da ony esta iniciada.", x = 64, y = 23, zone = "Burning Steps" },
			[24] = { str = "Voce deve estar a uns 10k do level 56, va grindar ate 5k nos orcs em #COORD[49,55]#", x = 49, y = 55, zone = "Burning Steps" },
			[25] = { str = "Use Hearthstone pra IF" },
			[26] = { str = "Va ate a sala do trono em #COORD[38,55]# e entregue #INThe Smoldering Ruins of Thaurissan pt.2#", x = 38, y = 55, zone = "Ironforge" },
			[27] = { str = "Voce deve estar level 56 agora, pegue novas skills" },
			[28] = { str = "Voe pra Menethil e pegue o barco pra Theramore" },
			[29] = { str = "Voe pra Gadgetzan" },
		}
	},

-----------56-56 Tanaris
	--[509] = {
	[5655] = {
		title = "56-56 Tanaris",
		--n = "56-56 Tanaris",
		--pID = 508, nID = 510,
		--itemCount = 9,
		items = {
			[1] = { str = "56-56 Tanaris" },
			[2] = { str = "Va ate o lado NW da cidade e assuste sprinkle para #DOAre We There, Yeti? pt.3#" },
			[3] = { str = "Sete Gadgetzan como seu lar" },
			[4] = { str = "Ao sul de lost rigger cove em #COORD[70,49]# tem um monte de pedras em circulo, Pegue as coisas da mochila azul e use o livro pra invocar Aquementas. Ele e um elemental de agua level 54", x = 70, y = 49, zone = "Tanaris" },
			[5] = { str = "Use Hearthstone pra Gadgetzan ou morra se ainda nao estiver pronto." },
			[6] = { str = "Voe pra Un'goro" },
			[7] = { str = "Ache Quixxil e assuste ele para #DOAre We There, Yeti? pt.3#" },
			[8] = { str = "Va ate o fundo da caverna e entregue #INAquementas# aceite #GETLinken's Adventure# e entregue logo fora da caverna perto da arvore grande PULE a proxima parte" },
			[9] = { str = "Voe pra Silithus" },
		}
	},

-----------56-56 Silithus
	--[510] = {
	[5656] = {
		title = "56-56 Silithus",
		--n = "56-56 Silithus",
		--pID = 509, nID = 511,
		--itemCount = 42,
		items = {
			[1] = { str = "56-56 Silithus" },
			[2] = { str = "Perto do moonwell aceite #GETThe Twilight Mystery#" },
			[3] = { str = "Na frente do Inn, entregue #INTaking Back Silithus# aceite #GETSecuring the Supply Lines#" },
			[4] = { str = "PULE a quest na placa a menos que consiga um grupo" },
			[5] = { str = "Sete Cenarion Hold como seu lar" },
			[6] = { str = "La em cima aceite #GETDeadly Desert Venom#" },
			[7] = { str = "Parece ter muitas quests brancas porque tem muitas quests de AQ que voce nao precisa se preocupar ainda." },
			[8] = { str = "Va fazer #DOSecuring the Supply Lines# e #DODeadly Desert Venom# ao Norte e NE da cidade ao redor de #COORD[55,24]# os dredges, scorpids, e skitterers para essas 2 quests estao por toda essa area.", x = 55, y = 24, zone = "Silithus" },
			[9] = { str = "Suba ate #COORD[81,18]# e entregue #INWasteland# aceite #GETThe Spirits of Southwind#", x = 81, y = 18, zone = "Silithus" },
			[10] = { str = "Suba pro NW ate 22.9 e pegue os twilight tablet fragments para #DOThe Twilight Mystery# Estao espalhados nesse spot", x = 22, y = 9, zone = "Silithus" },
			[11] = { str = "Use Hearthstone pra Cenarion Hold" },
			[12] = { str = "La em cima entregue #INDeadly Desert Venom# aceite #GETNoggle's Last Hope#" },
			[13] = { str = "Na frente do Inn, entregue #INSecuring the Supply Lines# aceite #GETStepping Up Security#" },
			[14] = { str = "Va perto do moonwell e entregue #INThe Twilight Mystery# aceite #GETThe Deserter#" },
			[15] = { str = "Voce deve estar uns 30-35% no level 56" },
			[16] = { str = "Va pro SE ate #COORD[62,53]# e mate os mobs mortos-vivos aqui para #DOThe Spirits of Southwind# cuidado quando eles morrem spawnam 1-2 bugs", x = 62, y = 53, zone = "Silithus" },
			[17] = { str = "Mate os pincers para #DONoggle's Last Hope# e drudges para #DOThe Deserter# ao sul daqui ao redor de #COORD[56,58]#", x = 56, y = 58, zone = "Silithus" },
			[18] = { str = "Va ate a caverna em #COORD[67,69]# e entregue #INThe Deserter# aceite #GETThe Twilight Lexicon#", x = 67, y = 69, zone = "Silithus" },
			[19] = { str = "Voce pode achar flayers e stalkers fora da caverna para #DONoggle's Last Hope# eles tambem estao ao redor de #COORD[43,72]# do outro lado da hive", x = 43, y = 72, zone = "Silithus" },
			[20] = { str = "Use Hearthstone pra Cenarion Hold ou morra pra voltar la" },
			[21] = { str = "Suba e entregue #INNoggle's Last Hope# aceite #GETNoggle's Lost Satchel#" },
			[22] = { str = "Fora do Inn, entregue #INStepping Up Security#" },
			[23] = { str = "Va ate #COORD[29,35]# e mate Twilight Keeper Manya para #DOThe Twilight Lexicon# ela da fear um pouco. Ela fica no canto SE do camp", x = 29, y = 35, zone = "Silithus" },
			[24] = { str = "Va ate #COORD[41,41]# e mate Twilight Keeper Havanuth para #DOThe Twilight Lexicon# ele fica no lado leste do camp, ele tem um aoe forte", x = 41, y = 41, zone = "Silithus" },
			[25] = { str = "Va todo o caminho pro sul ate o pequeno camp em #COORD[42,90]# e suba o morro atras dele, voce vai achar Deathclasp, no meio do caminho na parede tem uma bolsa, pegue quando deathclasp estiver no fundo para #DONoggle's Lost Satchel#", x = 42, y = 90, zone = "Silithus" },
			[26] = { str = "Va pro SW ate #COORD[16,87]# e mate Twilight Keeper Exeter para #DOThe Twilight Lexicon# ele fica no canto SW do camp", x = 16, y = 87, zone = "Silithus" },
			[27] = { str = "Volte ate a caverna em #COORD[67,69]# e entregue #INThe Twilight Lexicon# aceite #GETA Terrible Purpose# Ele tambem oferece outra quest por 10 twilight texts, isso e mais pra rep de cen circle depois", x = 67, y = 69, zone = "Silithus" },
			[28] = { str = "Suba ate #COORD[81,18]# e entregue #INThe Spirits of Southwind# aceite #GETHive in the Tower#", x = 81, y = 18, zone = "Silithus" },
			[29] = { str = "Va ate o topo da torre em #COORD[61,52]# Cuidado 3 bugs spawnam quando voce entra. Shift clique direito no pod porque assim que voce abrir alguns emboscadores spawnam. Mate pelo menos 1 e loote para #DOHive in the Tower#", x = 61, y = 52, zone = "Silithus" },
			[30] = { str = "Suba ate #COORD[81,18]# e entregue #INHive in the Tower# aceite #GETUmber, Archivist#", x = 81, y = 18, zone = "Silithus" },
			[31] = { str = "Use Hearthstone pra Cenarion Hold" },
			[32] = { str = "." },
			[33] = { str = "Suba e entregue #INNoggle's Lost Satchel#" },
			[34] = { str = "Entre no predio longo e entregue #INA Terrible Purpose#" },
			[35] = { str = "Voe pra Moonglade" },
			[36] = { str = "Va ate #COORD[44,35]# e entregue #INUmber, Archivist# aceite #GETUncovering Past Secrets#", x = 44, y = 35, zone = "Moonglade" },
			[37] = { str = "Va ate #COORD[51,44]# e entregue #INUncovering Past Secrets#", x = 44, y = 35, zone = "Moonglade" },
			[38] = { str = "Voce deve estar agora 80-85% pra upar" },
			[39] = { str = "Voe pra Auberdine e pegue o barco pra Menethil depois voe pra IF" },
			[40] = { str = "Sete IF como seu lar, depois ache o comandante anao andando e aceite #GETA Call To Arms: The Plaguelands!#" },
			[41] = { str = "Voe pra Southshore" },
			[42] = { str = "Va ao norte ate Alterac Mountains e siga pro NE ate #COORD[80,34]# e entre em Western Plaguelands (WPL)", x = 80, y = 34, zone = "Alterac Mountains" },
		}
	},

------------56-57 Western Plaguelands
	--[511] = {
	[5657] = {
		title = "56-57 Western Plaguelands",
		--n = "56-57 Western Plaguelands",
		--pID = 510, nID = 512,
		--itemCount = 43,
		items = {
			[1] = { str = "56-57 Western Plaguelands" },
			[2] = { str = "Perto da cabana aceite #GETA Plague Upon Thee pt.1#" },
			[3] = { str = "Pegue o FP" },
			[3] = { str = "Sempre que voce voltar ao camp aqui verifique o vendor pela receita de stormshroud pants. Custa tipo 1.3g e voce pode facilmente vender por 10 ou 20g+ E uma receita limitada que restoca 1 por hora." },
			[4] = { str = "Va ate a tenda e entregue #INA Call To Arms: The Plaguelands!#, aceite #GETClear The Way#" },
			[5] = { str = "Va ate as 3 pessoas da Argent Dawn perto da outra tenda e entregue #INThe Everlook Report# e tambem complete #GETArgent Dawn Commission# nao e uma quest que voce tinha ela so usa pra te dar o trinket que voce deve sempre usar quando estiver em WPL e EPL porque da rep com AD e permite os scourge tokens droparem, ela tambem tem 3 quests novas de entrega desses. Voce provavelmente nao vai passar da primeira quest pois o resto sao mais de instancias." },
			[6] = { str = "Guarde os tokens ate eu mandar entregar" },
			[7] = { str = "Va pro NE ate #COORD[51,78]# e grinde os ghouls aqui ate ter o suficiente para #DOClear The Way#", x = 51, y = 78, zone = "Western Plaguelands" },
			[8] = { str = "Volte ate Chillwind Camp em #COORD[42,84]# e entregue #INClear The Way# aceite #GETAll Along the Watchtowers# e #GETThe Scourge Cauldrons#", x = 42, y = 84, zone = "Western Plaguelands" },
			[9] = { str = "Vire e entregue #INThe Scourge Cauldrons# aceite #GETTarget: Felstone Field#" },
			[10] = { str = "Voce deve estar agora a uns 5-10k do level 57" },
			[11] = { str = "Volte pro NE ate #COORD[48,72]# e passe pela ponte", x = 48, y = 72, zone = "Western Plaguelands" },
			[12] = { str = "Logo na cidade a esquerda em #COORD[47,71]# fica a 4a torre para #DOAll Along the Watchtowers#, tem elites dentro mas voce pode ficar fora de LOS na beirada e marcar as portas facilmente. 1a torre a Oeste daqui em #COORD[40,71]#. 2a torre NE daqui em #COORD[42,66]#. 3a torre NE daqui em #COORD[44,63]#. Logo atras dessa torre.", x = 47, y = 71, zone = "Western Plaguelands" },
			[13] = { str = "Va pro NW ate #COORD[37,56]# ate Felstone field, mate #NPCCauldron Lord Bilemaw# pela chave do caldeirao. Depois clique no caldeirao e entregue #INTarget: Felstone Field# aceite #GETReturn to Chillwind Camp#", x = 37, y = 56, zone = "Western Plaguelands" },
			[14] = { str = "Tem 2 casas no lado NE do campo em #COORD[38,54]#, entre na casa do norte e suba. Aceite #GETBetter Late Than Never pt.1#", x = 38, y = 54, zone = "Western Plaguelands" },
			[15] = { str = "Entre no celeiro ao lado e pegue a caixa no chao e entregue #INBetter Late Than Never pt.1# aceite #GETBetter Late Than Never pt.2#" },
			[16] = { str = "Volte ate Chillwind Camp em #COORD[42,84]# e entregue #INAll Along the Watchtowers#, aceite #GETScholomance# PULE a outra a menos que consiga umas 10-20 pessoas.", x = 42, y = 84, zone = "Western Plaguelands" },
			[17] = { str = "Entregue #INScholomance# logo atras dele, aceite #GETSkeletal Fragments Bones# isso vai demorar um pouco e dropa de qualquer esqueleto." },
			[18] = { str = "Perto do FP entregue #INReturn to Chillwind Camp# aceite #GETTarget: Dalson's Tears#" },
			[19] = { str = "Suba ate #COORD[46,52]# ate Dalson'Tears, mate #NPCCauldron Lord Malvinious# pela chave do caldeirao. Depois clique no caldeirao e entregue #INTarget: Dalson's Tears# aceite #GETReturn to Chillwind Camp#", x = 46, y = 52, zone = "Western Plaguelands" },
			[20] = { str = "Entre no celeiro aqui em #COORD[47,50]# e toque no diario no chao e complete, mais uma quest que nao e quest.", x = 47, y = 50, zone = "Western Plaguelands" },
			[21] = { str = "Va atras do celeiro e procure um Wandering Skeleton e pegue a Dalson Outhouse Key dele. Use pra abrir a casinha atras aqui e mate Farmer Dalson e pegue a Dalson Cabinet Key dele. Use a chave no armario trancado la em cima na casa em #COORD[47,49]# perto do celeiro e complete a quest #INLocked Away#", x = 47, y = 49, zone = "Western Plaguelands" },
			[22] = { str = "Volte ate Chillwind Camp em #COORD[42,84]# e entregue #INReturn to Chillwind Camp# aceite #GETTarget: Writhing Haunt#", x = 42, y = 84, zone = "Western Plaguelands" },
			[23] = { str = "Use Hearthstone pra IF depois voe pra SW" },
			[24] = { str = "Va ate o predio em #COORD[48,30]# no 2o andar da area da catedral e entregue #INBetter Late Than Never pt.2# aceite #GETGood Natured Emma#", x = 48, y = 30, zone = "Stormwind" },
			[25] = { str = "Emma anda entre a catedral e o trade district, ache ela e entregue #INGood Natured Emma# aceite #GETGood Luck Charm#" },
			[26] = { str = "Entre no keep em #COORD[78,17]# e aceite #GETThe First and the Last#", x = 78, y = 17, zone = "Stormwind" },
			[27] = { str = "Va ate #COORD[75,79]# e entregue #INThe First and the Last# aceite #GETHonor the Dead# depois entregue de volta, aceite #GETFlint Shadowmore#", x = 75, y = 79, zone = "Stormwind" },
			[28] = { str = "Voe de volta pra WPL" },
			[29] = { str = "Na frente da casa entregue #INFlint Shadowmore# aceite #GETThe Eastern Plagues#" },
			[30] = { str = "Volte ate Felstone field na casa la em cima em #COORD[38,54]# e entregue #INGood Luck Charm# aceite #GETTwo Halves Become One# Va la fora e procure um jabbering ghoul. Voce nao tem como errar ele carrega um forcado. Continue limpando na frente da casa ate achar. Isso vai dar um bom tempo pra pegar os skeletal fragments", x = 38, y = 54, zone = "Western Plaguelands" },
			[31] = { str = "Combine as metades e volte la em cima e entregue #INTwo Halves Become One#" },
			[32] = { str = "Va pro SE ate #COORD[53,65]# ate Writhing Haunt, mate #NPCCauldron Lord Razarch# pela chave do caldeirao. Depois clique no caldeirao e entregue #INTarget: Writhing Haunt# aceite #GETReturn to Chillwind Camp#", x = 53, y = 65, zone = "Western Plaguelands" },
			[33] = { str = "Na casa em #COORD[54,65]# aceite #GETThe Wildlife Suffers Too pt.1# agora va ao norte do haunt e mate os lobos doentes. Nao va mais pra leste pra achar esses so va pro Norte, talvez um pouco NW.", x = 54, y = 65, zone = "Western Plaguelands" },
			[34] = { str = "Volte ate #COORD[54,65]# e entregue #INThe Wildlife Suffers Too pt.1# aceite #GETThe Wildlife Suffers Too pt.2#", x = 54, y = 65, zone = "Western Plaguelands" },
			[35] = { str = "Volte ate Chillwind Camp em #COORD[42,84]# e entregue #INReturn to Chillwind Camp# aceite #GETTarget: Gahrron's Withering#", x = 42, y = 84, zone = "Western Plaguelands" },
			[36] = { str = "Va logo ao norte do Writhing Haunt entre as montanhas no mapa, #COORD[52,56]# e mate diseased grizzleys no caminho descendo ate #COORD[62,58]# para #DOThe Wildlife Suffers Too pt.2#", x = 52, y = 56, zone = "Western Plaguelands" },
			[37] = { str = "Va pro NE ate #COORD[62,58]# ate Gahrron's Withering, mate #NPCCauldron Lord Soulwrath# pela chave do caldeirao. Depois clique no caldeirao e entregue #INTarget: Gahrron's Withering# aceite #GETReturn to Chillwind Camp#", x = 62, y = 58, zone = "Western Plaguelands" },
			[38] = { str = "Volte ate #COORD[54,65]# e entregue #INThe Wildlife Suffers Too pt.2# aceite #GETGlyphed Oaken Branch#", x = 54, y = 65, zone = "Western Plaguelands" },
			[39] = { str = "Se voce ainda nao terminou Skeletal Fragments va ate a cripta em #COORD[54,79]# e mate os esqueletos ate ter 15 fragments", x = 54, y = 79, zone = "Western Plaguelands" },
			[40] = { str = "Volte ate Chillwind Camp em #COORD[42,84]# e entregue #INReturn to Chillwind Camp#", x = 42, y = 84, zone = "Western Plaguelands" },
			[41] = { str = "Vire pro cara na frente da tenda, e complete a quest #INMission Accomplished!# sem link porque nao e uma quest de novo lol. Agora veja que ir e voltar pareceu fora do caminho mas teve um boost grande de xp no final, e bom xp durante todo o processo." },
			[42] = { str = "A sua direita entregue #INSkeletal Fragments# PULE a proxima parte a menos que queira comecar sua chave de scholo." },
			[43] = { str = "Va pro leste ate #COORD[70,50]# e entre em Eastern Plaguelands (EPL)", x = 70, y = 50, zone = "Western Plaguelands" },
		}
	},

-----------57-58 Eastern Plaguelands
	--[512] = {
	[5758] = {
		title = "57-58 Eastern Plaguelands",
		--n = "57-58 Eastern Plaguelands",
		--pID = 511, nID = 513,
		--itemCount = 19,
		items = {
			[1] = { str = "57-58 Eastern Plaguelands" },
			[2] = { str = "Suba pela costa oeste ate 67,4 e aceite as 3 quests #GETDemon Dogs# #GETBlood Tinged Skies# e #GETCarrion Grubbage#", x = 67, y = 4, zone = "Eastern Plaguelands" },
			[3] = { str = "Essas sao quests chatas que podem demorar. A partir de agora ate terminar, mate qualquer plaguehound runt, carrion worm, ou plaguebat." },
			[4] = { str = "Daqui pra baixo ate a area maior, mate qualquer cachorro, verme, e morcego. Foque neles enquanto vai pro proximo passo" },
			[5] = { str = "Continue matando os cachorros e morcegos e va ate o esqueleto em #COORD[28,74]# abra e pegue a insignia para #DOThe Eastern Plagues# depois suba um pouco mais ate o proximo esqueleto em #COORD[27,74]# e pegue a insignia, ta praticamente na frente dele e voce tambem vai receber a mensagem de blightcaller found. Agora desca perto da estrada ate #COORD[28,79]# e loote a ultima insignia do esqueleto", x = 28, y = 74, zone = "Eastern Plaguelands" },
			[6] = { str = "Foque nos cachorros e morcegos enquanto vai ate Darrowshire em #COORD[36,90]# na casa destruida. Entregue #INSister Pamela# aceite #GETPamela's Doll# depois va ate as casas aqui, em qualquer uma das casas pode ter qualquer uma das 3 partes da boneca. Sao aleatorias. Fantasmas spawnam quando voce chega perto das partes entao fique atento. Depois de ter as 3 partes combine e volte ate #COORD[36,90]# e entregue #INPamela's Doll# aceite #GETAuntie Marlene# e #GETUncle Carlin#", x = 36, y = 90, zone = "Eastern Plaguelands" },
			[7] = { str = "Olhe no seu mapa em #COORD[48,76]# Isso alinha com aquela montanha do meio. Nao passe desse ponto pro leste ate ter seus kills de plaguehound runt para #DODemon Dogs# e plaguebats para #DOBlood Tinged Skies# porque nao tem nenhum depois desse ponto.", x = 48, y = 76, zone = "Eastern Plaguelands" },
			[8] = { str = "Nao esqueca de matar os grubs pelo caminho tambem para #DOCarrion Grubbage#, eles nao sao tao importantes porque estao por toda parte." },
			[9] = { str = "Mate Plaguehounds para Demon Dogs ao redor de #COORD[56,57]# isso e ao norte do scar e ao sul de blackwood lake. Nao esqueca dos grubs", x = 56, y = 57, zone = "Eastern Plaguelands" },
			[10] = { str = "Mate Frenzied Plaguehounds para #DODemon Dogs# ao redor de #COORD[61,41]# isso e ao norte de blackwood lake mas agora a oeste dela.", x = 61, y = 41, zone = "Eastern Plaguelands" },
			[11] = { str = "Va ate lights hope chapel em #COORD[81,58]# se voce ainda precisar de grub meat para #DOCarrion Grubbage#, entao mate eles enquanto vai", x = 81, y = 58, zone = "Eastern Plaguelands" },
			[12] = { str = "Pegue o FP" },
			[13] = { str = "Entregue #INUncle Carlin# aceite #GETDefenders of Darrowshire#" },
			[14] = { str = "Vire e entregue #INDuke Nicholas Zverenhoff#" },
			[15] = { str = "Va pro SW ate #COORD[79,63]# e aceite #GETZaeldarr the Outcast#", x = 79, y = 63, zone = "Eastern Plaguelands" },
			[16] = { str = "Voe de volta pra EPL" },
			[17] = { str = "Na frente da casa entregue #INThe Eastern Plagues# aceite #GETThe Blightcaller Cometh#" },
			[18] = { str = "Se voce estiver a 6.600 de upar entao use Hearthstone pra IF e voe pra SW, se nao grinde ate estar nessa faixa." },
			[19] = { str = "Va ate #COORD[78,18]# no keep e entregue #INThe Blightcaller Cometh# agora eu PULO a proxima parte mas e uma boa quest pra fazer no 60", x = 78, y = 18, zone = "Eastern Plaguelands" },
			[18] = { str = "Va pegar novas skills" },
			[19] = { str = "Voe de volta pra WPL" },
		}
	},

-----------58-58 Western Plaguelands
	--[513] = {
	[5857] = {
		title = "58-58 Western Plaguelands",
		--n = "58-58 Western Plaguelands",
		--pID = 512, nID = 514,
		--itemCount = 9,
		items = {
			[1] = { str = "58-58 Western Plaguelands" },
			[2] = { str = "Va pro NE ate a casa em #COORD[49,78]# e suba. Entregue #INPamela's Doll# aceite #GETA Strange Historian#", x = 49, y = 78, zone = "Western Plaguelands" },
			[3] = { str = "Logo ao norte da casa em #COORD[49,76]# voce vai ver uma lapide de cor diferente. Loote e pegue o anel de casamento para #DOA Strange Historian#", x = 49, y = 76, zone = "Western Plaguelands" },
			[4] = { str = "Entre pela entrada oeste de Andorhal em #COORD[39,71]# e voce deve ver o unico predio inteiro, parece um Inn em #COORD[39,68]#. Suba e entregue #INA Strange Historian# aceite #GETThe Annals of Darrowshire# tambem aceite #GETA Matter of Time#", x = 39, y = 68, zone = "Western Plaguelands" },
			[5] = { str = "Agora procure ao redor da cidade aqui por silos quebrados com uma luz azul saindo deles. Use o silo horn pra invocar os vermes, spawna 1-3 mobs para #DOA Matter of Time#. Depois de matar o ultimo eles tendem a spawnar outro. Tem mais no lado Leste da cidade" },
			[6] = { str = "Va ate o Town Hall perto de todos os mobs no meio da cidade, voce pode entrar sorrateiramente pelo lado SW. Pegue os livros no chao ate pegar #GETThe Annals of Darrowshire# Alguns vao spawnar mobs" },
			[7] = { str = "Volte ate o Inn em #COORD[39,68]# e no ultimo andar, entregue #INA Matter of Time# aceite #GETCounting Out Time# tambem entregue #INThe Annals of Darrowshire# aceite #GETBrother Carlin#", x = 39, y = 68, zone = "Western Plaguelands" },
			[8] = { str = "Va la fora e procure ao redor das casas quebradas por pequenas lancheiras de metal para #DOCounting Out Time#" },
			[9] = { str = "Volte ate o Inn em #COORD[39,68]# e entregue #INCounting Out Time# voce agora pode repetir essa quest por um dampener. Isso e usado contra o elite 61", x = 39, y = 68, zone = "Western Plaguelands" },
		}
	},

-----------58-58 Eastern Plaguelands
	--[514] = {
	[5858] = {
		title = "58-58 Eastern Plaguelands",
		--n = "58-58 Eastern Plaguelands",
		--pID = 513, nID = 515,
		--itemCount = 18,
		items = {
			[1] = { str = "58-58 Eastern Plaguelands" },
			[2] = { str = "Saia daqui e entre em EPL suba pro NW ate 7,43 e entregue as 3 quests #INDemon Dogs# #INBlood Tinged Skies# e #INCarrion Grubbage# aceite #GETRedemption# depois ouca ele e entregue de volta. Depois aceite #GETOf Forgotten Memories#", x = 7, y = 43, zone = "Eastern Plaguelands" },
			[3] = { str = "Va ate o Undercroft em #COORD[28,86]# e va atras dele. Toque na pilha de terra pra invocar Mercutio e 3 guardas. O jeito mais facil de fazer isso e kitar ele pra longe dos amigos ou pegar um grupo. Loote o corpo dele pelo martelo para #DOOf Forgotten Memories#", x = 28, y = 86, zone = "Eastern Plaguelands" },
			[4] = { str = "Agora va ate o fundo da cripta e mate o troll bem grande para #DOZaeldarr the Outcast# So pegue o scroll no chao se quiser" },
			[5] = { str = "Volte ate 7,43 e entregue #INOf Forgotten Memories# aceite #GETOf Lost Honor#", x = 7, y = 43, zone = "Eastern Plaguelands" },
			[6] = { str = "Va ate Light's Hope Chapel ou volte pra Chillwind e voe ate la" },
			[7] = { str = "Entregue #INBrother Carlin# aceite #GETVillains of Darrowshire#" },
			[8] = { str = "Desca ate #COORD[79,63]# e entregue #INZaeldarr the Outcast#", x = 79, y = 63, zone = "Eastern Plaguelands" },
			[9] = { str = "Desca logo ao Norte de Corin's Crossing ate #COORD[53,65]# e pegue a espada para #DOVillains of Darrowshire# Esta la no scar. Nao esqueca de fazer um pouco de #DODefenders of Darrowshire# em Corin's. So pegue o que puder", x = 53, y = 65, zone = "Eastern Plaguelands" },
			[10] = { str = "Va ao norte ate Blackwood Lake em #COORD[51,49]# e pegue o cranio debaixo d'agua para #DOVillains of Darrowshire#", x = 51, y = 49, zone = "Eastern Plaguelands" },
			[11] = { str = "Va pro NE ate #COORD[65,41]# e mate os zumbis para parte de #DODefenders of Darrowshire# tem bastante aqui voce provavelmente pode terminar", x = 65, y = 41, zone = "Eastern Plaguelands" },
			[12] = { str = "Va ate o lago em #COORD[71,33]# e pegue a bandeira perto da jaula, e dificil de ver e esta deitada para #DOOf Lost Honor#", x = 71, y = 33, zone = "Eastern Plaguelands" },
			[13] = { str = "Va pro NW ate a torre em #COORD[56,24]# e entregue #INTroubled Spirits of Kel'Theril# PULE a proxima parte", x = 56, y = 24, zone = "Eastern Plaguelands" },
			[14] = { str = "Va pro Oeste ate #COORD[45,34]# e loote os montes de cupim aqui para #DOA Plague Upon Thee pt.1# ate ter 100 cupins, tambem mate ghouls pra terminar #DODefenders of Darrowshire#", x = 45, y = 34, zone = "Eastern Plaguelands" },
			[15] = { str = "Va ate Lights Hope Chapel agora" },
			[16] = { str = "Va perto da tenda e entregue #INDefenders of Darrowshire# e #INVillains of Darrowshire#" },
			[17] = { str = "Voe pra WPL" },
			[18] = { str = "Perto da casa entregue #INA Plague Upon Thee pt.1# aceite #GETA Plague Upon Thee pt.2#" },
		}
	},

------------58-59 Western Plaguelands
	--[515] = {
	[5859] = {
		title = "58-59 Western Plaguelands",
		--n = "58-59 Western Plaguelands",
		--pID = 514, nID = 516,
		--itemCount = 19,
		items = {
			[1] = { str = "58-59 Western Plaguelands" },
			[2] = { str = "Suba ate #COORD[51,28]# e aceite #GETUnfinished Business pt.1#", x = 52, y = 30, zone = "Western Plaguelands" },
			[3] = { str = "Comece voltando pro SW ao redor de #COORD[47,32]# e limpe o caminho ate o moinho. Clique na caixa e coloque os cupins, depois clique no barril e entregue #INA Plague Upon Thee pt.2# aceite #GETA Plague Upon Thee pt.3#", x = 47, y = 32, zone = "Western Plaguelands" },
			[4] = { str = "Va logo ao sul de #COORD[49,42]# e mate 2 knights e mages para #DOUnfinished Business pt.1# depois #COORD[51,43]# para os hunters e medics", x = 49, y = 42, zone = "Western Plaguelands" },
			[5] = { str = "Va ate #COORD[51,28]# e entregue #INUnfinished Business pt.1# aceite #GETUnfinished Business pt.2#", x = 51, y = 28, zone = "Western Plaguelands" },
			[6] = { str = "Va ate #COORD[57,36]# e mate Huntsman Radly para #DOUnfinished Business pt.2# depois ao norte ate a torre em #COORD[55,23]# e mate Cavalier Durgen no topo", x = 57, y = 36, zone = "Western Plaguelands" },
			[7] = { str = "Saia direto da torre pelas montanhas ate #COORD[51,28]# e entregue #INUnfinished Business pt.2# fazer a 3a parte #DOUnfinished Business pt.3# e opcional. Algumas classes conseguem mais facil que outras. Voce tem que ir ao norte ate hearthglen e subir na torre grande no centro da cidade em #COORD[45,18]# e olhar pela beirada ate dizer completo.", x = 45, y = 18, zone = "Western Plaguelands" },
			[8] = { str = "Volte direto pro sul pelas montanhas ate #COORD[51,28]# e entregue #INUnfinished Business pt.3#", x = 51, y = 28, zone = "Western Plaguelands" },
			[9] = { str = "Entre em EPL e suba ate 7,43 e entregue #INOf Lost Honor# aceite #GETOf Love and Family pt.1#", x = 7, y = 43, zone = "Eastern Plaguelands" },
			[10] = { str = "Volte pra WPL e va/nade ate a ilha onde fica Scholo em #COORD[65,75]# e entregue #INOf Love and Family pt.1# PULE o resto ate voce fazer strat", x = 65, y = 75, zone = "Western Plaguelands" },
			[11] = { str = "Volte ate Chillwind Camp em #COORD[43,84]# e entregue #INA Plague Upon Thee pt.3#", x = 43, y = 84, zone = "Western Plaguelands" },
			[12] = { str = "Agora voce quer fazer 2 coisas aqui. Ficar friendly com Argent Dawn e ficar a 8-8.5k de upar. Voce pode fazer #DOAlas, Andorhal# se achar um grupo, nao e tao dificil mas pode precisar de 5-10 pessoas. Isso vai dar 8300 xp facil ao inves de grindar." },
			[13] = { str = "Agora voce quer ir ate andorhal e grindar ate ficar friendly, uma vez friendly volte pra Chillwind Camp e entregue todos seus scourge tokens. Isso permite voce comprar mana biscuits que restauram mana e vida e mais que comida normal. Se voce ainda precisar upar entao va grindar nos mobs em andorhal de novo ate estar 8-8.5k do level 59" },
			[14] = { str = "Quando estiver a 8k-8.5k de upar, voe pra Hinterlands e va todo o caminho pro NE ate a cachoeira em #COORD[80,46]# e pule. Debaixo d'agua loote o bau e termine #DOCortello's Riddle pt.3#", x = 80, y = 46, zone = "The Hinterlands" },
			[15] = { str = "Use Hearthstone pra IF" },
			[16] = { str = "Va ate a sala do trono em #COORD[43,52]# e aceite #GETAn Earnest Proposition# (escolha sua classe da lista) Voce precisa ter os bracers tier 0 da sua classe pra fazer essa quest. Voce pode comprar na AH", x = 43, y = 52, zone = "Ironforge" },
			[17] = { str = "Voe pra Menethil e pegue o barco pra Auberdine, voe pra Darnassus" },
			[18] = { str = "Va ate 35,8 no 2o andar e entregue #INGlyphed Oaken Branch#", x = 35, y = 8, zone = "Darnassus" },
			[19] = { str = "Voce deve estar level 59, voe pra Winterspring" },
		}
	},

------------59-60 Winterspring
	--[516] = {
	[5960] = {
		title = "59-60 Winterspring",
		--n = "59-60 Winterspring",
		--pID = 515, nID = 516,
		--itemCount = 31,
		items = {
			[1] = { str = "59-60 Winterspring" },
			[2] = { str = "A sua esquerda ao entrar entregue #INAre We There, Yeti? pt.3#" },
			[3] = { str = "Perto do fundo tem 2 hordes, aceite #GETLuck Be With You#" },
			[4] = { str = "Vire e entregue #INFelnok Steelspring# aceite #GETChillwind Horns#" },
			[5] = { str = "Faca #DOAn Earnest Proposition# so mate os sabers ate ter 15 blood" },
			[6] = { str = "Va logo pro SE daqui ao redor de #COORD[55,18]# e mate as chimeras para #DOChillwind Horns#", x = 55, y = 18, zone = "Winterspring" },
			[7] = { str = "Va ate Starfall Village em #COORD[52,30]# e aceite #GETEnraged Wildkin pt.1#", x = 52, y = 30, zone = "Winterspring" },
			[8] = { str = "Entregue #INChillwind Horns# PULE a outra a menos que queira ir la" },
			[9] = { str = "Va ao sul ate #COORD[59,59]# e toque na caixa e entregue #INEnraged Wildkin pt.1# aceite #GETEnraged Wildkin pt.2#", x = 59, y = 59, zone = "Winterspring" },
			[10] = { str = "Volte ate a estrada em #COORD[61,60]# e toque na carroça, entregue #INEnraged Wildkin pt.2# aceite #GETEnraged Wildkin pt.3# pegue a caixa na neve", x = 61, y = 60, zone = "Winterspring" },
			[11] = { str = "Va pro leste de novo ate #COORD[63,59]# e entregue #INFind Ranshalla# aceite #GETGuardians of the Altar#", x = 63, y = 59, zone = "Winterspring" },
			[12] = { str = "Agora proteja ela enquanto faz o que precisa. Certifique-se de pegar a pena de um owl para #DOEnraged Wildkin pt.3# Quando ela parar numa caverna, acenda a tocha pra ela. Se voce nao pegar a pena antes de terminar continue matando ate conseguir." },
			[13] = { str = "Va ao sul ate #COORD[62,69]# e loote as gemas para #DOLuck Be With You# hunters e locks podem usar pet pra distrair mobs enquanto loota, outras classes vao ter que grupar.", x = 62, y = 69, zone = "Winterspring" },
			[14] = { str = "Use Hearthstone pra Everlook" },
			[15] = { str = "Entregue #INLuck Be With You# nos 2 hordes perto do fundo de everlook" },
			[16] = { str = "Voce deve estar uns 25% no level 59 agora." },
			[17] = { str = "Aceite #GETCache of Mau'Ari# se quiser. Isso so te da um item que permite os mobs aqui droparem coisas que voce pode entregar por buffs" },
			[18] = { str = "Suba ate Starfall Village em #COORD[52,30]# e entregue #INEnraged Wildkin pt.3#", x = 52, y = 30, zone = "Winterspring" },
			[19] = { str = "Va ate #COORD[31,45]# e entregue #INMystery Goo# aceite #GETToxic Horrors#", x = 31, y = 45, zone = "Winterspring" },
			[20] = { str = "Entre em Felwood e va ate #COORD[48,24]# e mate toxic horrors para #DOToxic Horrors# esses tambem dropam essence of waters", x = 48, y = 24, zone = "Felwood" },
			[21] = { str = "Voe pra Rut'theran Village e va ate a casa em #COORD[55,92]# e entregue #INGuardians of the Altar# aceite #GETWildkin of Elune#", x = 55, y = 92, zone = "Teldrassil" },
			[22] = { str = "Entre em Darnassus e suba ate o topo da torre em 34,8 e entregue #INWildkin of Elune#", x = 34, y = 8, zone = "Darnassus" },
			[23] = { str = "Voe de volta pra Felwood" },
			[24] = { str = "Volte subindo ate Winterspring e va ate #COORD[31,45]# entregue #INToxic Horrors# aceite #GETWinterfall Runners#", x = 31, y = 45, zone = "Winterspring" },
			[25] = { str = "Agora pra achar os runners. Eles viajam de qualquer lugar da Timbermaw Cave pro leste ate #COORD[53,34]# depois ao redor das montanhas ao norte de everlook ate Winterfall Village. Se voce nao viu eles da caverna ate aqui, va pro leste. Voce nao precisa matar todos os 3", x = 53, y = 34, zone = "Winterspring" },
			[26] = { str = "Depois de pegar a caixa volte ate #COORD[31,45]# Entregue Winterfall Runners uma emboscada vai vir do lago, se voce nao sair da tenda eles nao vao dar aggro. PULE a proxima parte a menos que consiga grupo", x = 31, y = 45, zone = "Winterspring" },
			[27] = { str = "Use Hearthstone pra Everlook" },
			[28] = { str = "Voce deve estar 45-50% no level 59. Agora eu me certifico que tenho meus mana bisquits e comeco a grindar ate estar a 6600 do level 60. Qualquer lugar serve onde tem bastante mob. E tudo questao de preferencia. Eu escolho o owl wing thicket em #COORD[64,62]# ou qualquer coisa ao norte de everlook. Eu gosto de matar furlbogs por rep de timbermaw tambem.", x = 64, y = 62, zone = "Winterspring" },
			[29] = { str = "Se voce nao quiser grindar essa quantidade grande entao faca BRD, scholo, ou strat. Voce tem muitas quests nesses lugares pra fazer" },
			[30] = { str = "Quando estiver a 6600 do 60 va pra IF e entregue #INAn Earnest Proposition#" },
			[31] = { str = "Parabens pelo 60!" },
		}
	},
}
